### ISSUE TITLE
Issue logging in using youtube

### ISSUE THREAD

**Issue by imkevinabraham** [jeremykenedy/laravel-auth#10]
First of all great package, My issue is that I tried logging in via youtube. It goes through to google then gets the account but when returning back I get an error that reads 

`FatalErrorException in Provider.php line 77:
Call to undefined method SocialiteProviders\YouTube\Provider::getAccessToken()`

Talking to the guys over at draper studio who manage the socialite providers package. I believe this is due to using an older package. See https://github.com/SocialiteProviders/YouTube/issues/5.

**Comment by jeremykenedy** [comment]
@imkevinabraham Thank you for the compliment and reporting the error. I will get this updated as soon as I get chance.

Thank you again

**Comment by jeremykenedy** [comment]
Socialite has been updated and this has been fixed. If you need to update this on an existing project you need to update composer.json and EventServiceProvider.php.

### Update Composer Socialite providers:
```
"laravel/socialite": "^2.0",
"socialiteproviders/youtube": "^2.0",
"socialiteproviders/twitch": "^2.0",
"socialiteproviders/instagram": "^2.0",
"socialiteproviders/37signals": "^2.0"
```

### Update EventServiceProvider.php:
```
protected $listen = [
    'event.name' => [
        'EventListener',
    ],
     \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        'SocialiteProviders\YouTube\YouTubeExtendSocialite@handle',
        'SocialiteProviders\Twitch\TwitchExtendSocialite@handle',
        'SocialiteProviders\Instagram\InstagramExtendSocialite@handle',
        'SocialiteProviders\ThirtySevenSignals\ThirtySevenSignalsExtendSocialite@handle',
    ],
];
```
### Then update composer:
```
sudo composer update
```

**Comment by imkevinabraham** [comment]
Thanks, that worked.

**Comment by jeremykenedy** [comment]
No prob
