### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jeremykenedy** [jeremykenedy/laravel-auth#100]
The project needs some documentation.

I love building this open source project and sharing it with the community.

This project grew further than I ever expected and I feel amongst a couple of needs one of them is documentation. It started as me wanting to record myself doing basic Laravel authentication which then expanded into wanting 2 step email verification, then social authentication, and so on...

It grew past the basic Laravel documentation in some ways and can use a little helping explanation for the explorers out there :)

I am hoping to get this in one day but I do get paid to develop too :)

**Comment by Tutuldot** [comment]
I'm interested to this to enhance my documentation skill. :) Will inform if I am ready to do this.

**Comment by denomon** [comment]
I have used this project on one of my sites and it really helped getting me started quickly. Great Project

**Comment by hansje69** [comment]
Same here! Thanks @jeremykenedy

**Comment by mdrashedulislam11** [comment]
Great Project
