### ISSUE TITLE
Google 2FA (2 step auth)

### ISSUE THREAD

**Issue by hansje69** [jeremykenedy/laravel-auth#102]
Suggested labels; [new feature][request][enhancement]

Possible to add **Google 2FA** (2 step auth/verification) for increased  security?
I noticed that only ReCaptcha is available as second layer, to prevent bots from entering, but this doesn't increase actual security.

Would like some feedback, what others think, worth it?

**Comment by jeremykenedy** [comment]
I think it is totally possible just requires some more code time.

I am working on my own 2 step verification which is about %85 done. The project I am creating is a stand-alone 2 step verification which will send the code via email in v1, then I was going to use a service like sendinblue for sms notifications in v1.X

The project will go on GH and packagit once I am done: https://bitbucket.org/jeremykenedy/laravel2step


Looking out here I also found these resources for using Googles API:
https://www.codementor.io/slavko/google-two-step-authentication-otp-generation-du1082vho 
https://github.com/PHPGangsta/GoogleAuthenticator

**Comment by XanderLuciano** [comment]
Example project in laravel: https://github.com/sitepoint-editors/google-laravel-2fa

Article: https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/
