### ISSUE TITLE
service mail not working

### ISSUE THREAD

**Issue by lucas94lbr** [jeremykenedy/laravel-auth#106]
Hello Jeremy,
I am currently working on an application where I need to use email services, so they are not working. I can not find the cause, my servers are properly configured. I can not sign up, send password reset emails. Can you help me?

the error is as follows

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_PARSE)
Parse error: syntax error, unexpected '?', Expecting variable (T_VARIABLE)

[error image
](https://tinyurl.com/ycdrxh8a)

**Comment by jeremykenedy** [comment]
I cannot duplicate. Did you publish the assets?
