### ISSUE TITLE
I can't access api endpoints

### ISSUE THREAD

**Issue by mapsiva** [jeremykenedy/laravel-auth#107]
Hi Everyone, 

I'm trying to access api endpoints, but all requests are redirected to /home.

`Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

Route::middleware('auth:api')->get('/users/{page}/{limit}', 'UserController@usersByPage');`

/api/users/10/10 => redirect to /home
/api/user => redirect to /home

**Comment by jeremykenedy** [comment]
I am now sure, that route is not part of the project. 

Thanks.

**Comment by jeremykenedy** [comment]
But this could be caused because that is the route defined to redirect web users to in the protectected variable.

‘protected $redirectTo = '/home';’

As laid out in https://laravel.com/docs/5.5/authentication
