### ISSUE TITLE
app.css not found

### ISSUE THREAD

**Issue by highdev2016** [jeremykenedy/laravel-auth#108]
Hello,

I've installed laravel-auth on my local and enter http://localhost/laravel-auth/public/login on my chrome browser. But it could not find the app.css and app.js.
The error message of the chrome console is the following:
GET http://localhost/css/app.css?id=21f487a0ac6196a1a2f6 net::ERR_ABORTED
GET http://localhost/js/app.js?id=c54f5e028608f87fb87b net::ERR_ABORTED

How can I fix it?

Thank you.

**Comment by jeremykenedy** [comment]
Step 12.
https://github.com/jeremykenedy/laravel-auth#opening-an-issue
