### ISSUE TITLE
Edit user profile location

### ISSUE THREAD

**Issue by elraghifary** [jeremykenedy/laravel-auth#11]
Hello, it seems I can't manage to use maps in this case.

Everytime I want to input data into location forms in edit profile page, it's directly change to readonly with error.

If I manually insert location from database server, in profile show page, it's doesn't show the map, latitude and longitude is empty.

I put my API key into .env with GOOGLEMAPS_API_KEY=XXXX

How to implement this feature Google Maps API?

Thanks.

**Comment by jeremykenedy** [comment]
Hi, It's pretty strait forward, you just have to put the key in the .env file. I just tested this is and everything worked as it should.
