### ISSUE TITLE
User profile route is accessible to other users.  

### ISSUE THREAD

**Issue by waqas61** [jeremykenedy/laravel-auth#110]
How can we restrict to other user to view my profile. Middleware should be implement.

Route Url   http://localhost:8000/profile/sorxrob 

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
         'as'   => '{username}',
         'uses' => 'ProfilesController@show',
     ]);

Not applicable to restrict

**Comment by jeremykenedy** [comment]
Middlware:  `currentUser`

As outlined in `web.php` for other routes.

Profiles are viewable by other users unless you wanted to change that in your own project.

https://github.com/jeremykenedy/laravel-auth/blob/master/routes/web.php#L62

**Comment by waqas61** [comment]
Thanks jeremykenedy.
But by commenting this route my profile is viewable to other users.

**Comment by waqas61** [comment]
Can we check it together ?

**Comment by jeremykenedy** [comment]
What if you move the whole block from lines 55-58 after line 75, that should do it.

Thanks for checking out the project.

**Comment by waqas61** [comment]
Jeremykenedy user profile route is accessible after your last suggestion implemented.Please check it.
Can we check it together.Middleware should be implemented.
