### ISSUE TITLE
Add Search by username/email

### ISSUE THREAD

**Issue by evnix** [jeremykenedy/laravel-auth#111]
Allow Admin to search users by their username or email.
You absolutely need this when user base grows above a few thousand users.
Currently I have to query the database manually, find the user ID and enter the ID manually in the URL and then go ahead and manage the user.

**Comment by jeremykenedy** [comment]
There are 2 options:
1. Modify the built on UsersManagement functionality 
2. Or you can modify this package and integrate it into this project. - https://github.com/jeremykenedy/laravel-users

Eventually, the plan is to change out users management to use the package so option 2 is the preferred.

**Comment by evnix** [comment]
Although Option 2 sounds enticing, I would most likely want to go with option 1.
This is more for practical reasons,  I don't want to manage or learn and keep track of another repository.
Right now contributing a feature is easy, set up is easy too, everything is available right in front of you in the same repo and everything works out of the box.

**Comment by jeremykenedy** [comment]
I will be circling back to add this on at some point.

**Comment by jeremykenedy** [comment]
@evnix It has been added in commit https://github.com/jeremykenedy/laravel-auth/commit/394777489575df60438254b6a7a15a85c5bb9d2b
