### ISSUE TITLE
User waiting for email activation fails even if admin elevates privlige

### ISSUE THREAD

**Issue by jdloaner** [jeremykenedy/laravel-auth#116]
If you sign up as a new user and don't activate your email, then from and Admin account you elevate that user's privilege level off of "unverified" user still gets activation error on login.

Deleting this user and re-creating directly from admin account works fine.

**Comment by jeremykenedy** [comment]
This has been fixed in commit https://github.com/jeremykenedy/laravel-auth/commit/58f026bda592b7afb551d0b1236209015d20081b

Thank you
