### ISSUE TITLE
After deleting user logged/registered by social network, unable to register again

### ISSUE THREAD

**Issue by francardenas** [jeremykenedy/laravel-auth#117]
When users login/register via social network (tested with Facebook) for first time it works correctly. But after deleting and destroying this user (via users administration options), if this user tries to register again with same Facebook account, next error is being showed and user is not being created:

![image](https://user-images.githubusercontent.com/4690749/36539640-c40d16b2-17d7-11e8-88b6-3ebef11bb403.png)

It seems this could be caused because deleting users via users administration doesn't delete related entries for this user login via social network? Because I tested manually deleting entry on social_logins table related with this removed user, and then I was able to register again by using same Facebook account.

Also, regarding registering with Facebook, how is password being generated in case of users registered via social network?

**Comment by jeremykenedy** [comment]
Looks like a security feature from the service provider.
