### ISSUE TITLE
Problem with phpinfo

### ISSUE THREAD

**Issue by MEXXIO** [jeremykenedy/laravel-auth#118]
I have a problem with entering the address /phpinfo
`"Class jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController does not exist"`

**Comment by jeremykenedy** [comment]
I cannot replicate.

**Comment by MEXXIO** [comment]
It did not help me.

**Comment by jeremykenedy** [comment]
I am thinking it is a namespace issue.

I have updated the codebase for php-info to have capital `App` in place of a lowercase `app` in the actual path.

https://github.com/jeremykenedy/laravel-phpinfo/commits/master
https://github.com/jeremykenedy/laravel-phpinfo/tree/master/src

**Comment by MEXXIO** [comment]
Now it works, just change from app to App.
Thanks for help ;)
