### ISSUE TITLE
Avatar images not showing after upload

### ISSUE THREAD

**Issue by RiverFlowingSeeds** [jeremykenedy/laravel-auth#120]
The avatar is uploaded in the storage folder/user/id/1/images/avatar
The url of the avatar in the upload box  is: http://localhost/images/profile/1/avatar/avatar.jpg?1519700121446
So it does not show. 

However my clean installation was executed until the command: npm run production
It got stuck at 95% and after 25 min quited the shell. 

Could this be the cause or is there something i'm not seeing right?

**Comment by jeremykenedy** [comment]
It is possible that npm choked.

remove the entire `node_modules` folder and run `npm install` again.

**Comment by RiverFlowingSeeds** [comment]
It's not showing anywhere. Not just upon changing it while in profile edit section.

After running npm install ik got these warnings: [http://www.celandiawebdesign.nl/temp/Screenshot_1.jpg](url)

Running xampp on a windows 10 o.s.. Can be assumed that as the avatar is uploaded the permissions are right?

**Comment by brunofaust** [comment]
Hi Jeremy.

I have the same problem, v6.0.0.

Browser error:
avatar.JPG:1 GET http://192.168.0.51/images/profile/1/avatar/avatar.JPG 404 (Not Found)

centos 7 files:
[root@web web]# ls /var/www/web/storage/users/id/1/uploads/images/avatar/avatar.JPG
-rw-r--r-- 1 nginx nginx 16K Sep 15 23:50 storage/users/id/1/uploads/images/avatar/avatar.JPG

after "chmod -R 775 storage/users":
-rwxrwxr-x 1 nginx nginx 16K Sep 15 23:50 storage/users/id/1/uploads/images/avatar/avatar.JPG

But, the error remains.


Request URL: http://192.168.0.51/images/profile/1/avatar/avatar.jpg
Request Method: GET
Status Code: 404 Not Found
Remote Address: 192.168.0.51:80
Referrer Policy: no-referrer-when-downgrade
HTTP/1.1 404 Not Found
Server: nginx
Date: Sun, 15 Sep 2019 22:02:27 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Content-Encoding: gzip
GET /images/profile/1/avatar/avatar.jpg HTTP/1.1
Host: 192.168.0.51
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
DNT: 1
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Referer: http://192.168.0.51/profile/Bruno%20Faust/edit
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9,pt-BR;q=0.8,pt;q=0.7,en;q=0.6

**Comment by brunofaust** [comment]
nginx error:

2019/09/16 00:15:32 [error] 8109#0: *170 open() "/var/www/web/public/profile/ /images/profile/1/avatar/avatar.jpg" failed (2: No such file or directory), client: 192.168.0.50, server: web request: "GET /profile/%20/images/profile/1/avatar/avatar.jpg HTTP/1.1", host: "192.168.0.51"

**Comment by brunofaust** [comment]
The problem was the nginx config.
You need to add this (if you have other locations with match with your URL - in my case "location ~* .jpg$"):

location ^~ /images/profile/ {
  try_files $uri $uri/ /index.php?$query_string;
}
