### ISSUE TITLE
Duplicate Entry users_name_unique When Registering With Google

### ISSUE THREAD

**Issue by Wasca** [jeremykenedy/laravel-auth#124]
Getting this error when registering using Google and two users have the same name.

**User 1**.  Joe@joe.com (Google Business account with custom domain), Name in Google Account = Joe Blogs

**User 2**. Joe.Blogs@gmail.com, Name in Google Account = Joe Blogs 

Joe@joe.com registers using the **Google Social button** option at https://laravelauth.dev/register

It logs in and he is fully registered and happy! Yay!

Joe.Blogs@gmail.com then registers using the **Google Social button** option at https://laravelauth.dev/register

Joe then sees this message...

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'JoeBlogs' for key 'users_name_unique' (SQL: insert into `users` (`name`, `first_name`, `last_name`, `email`, `password`, `token`, `activated`, `signup_sm_ip_address`, `updated_at`, `created_at`) values (JoeBlogs, Joe, Blogs, Joe.Blogs@gmail.com, $2y$10$zENiW6XMprhDYh9i0qx0COLpAT0nqkKE44lUF0MvDRWo7Z7fEdUfG, qupGYoZKLWsLYU67ul0J4xE16K0hgxCwNRMG0CgtfhhiURoD0LDS7Uc9NiylPLdY, 1, 127.0.0.1, 2018-03-01 07:23:47, 2018-03-01 07:23:47))`

Is there any way around this situation?

**Comment by jeremykenedy** [comment]
You can either put a validation rule in place in the social controller or make a migration to alter the users table to remove the unique key constraint on the name field in the users table.

**Comment by Wasca** [comment]
Thanks @jeremykenedy appreciate your advice.

**Comment by jeremykenedy** [comment]
np :)
