### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by subhashp** [jeremykenedy/laravel-auth#125]
Hello,

I did a fresh install of laravel-auth and logged in as admin@admin.com. Everything works out of the box! Except when I click http://127.0.0.1:8000/activity. I get following error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Locale' not found

Regards,
Subhash
![laravelerror](https://user-images.githubusercontent.com/655176/36906740-bdc64f9a-1e5c-11e8-9804-f7db5611628a.jpg)

**Comment by jeremykenedy** [comment]
What version of php are you running?

**Comment by jeremykenedy** [comment]
how are you serving it?

**Comment by jeremykenedy** [comment]
It is a PHP configuration error that is specific to your PHP configuration. 

http://php.net/manual/en/book.intl.php

**Comment by danielin** [comment]
Hi , am facing the same issue. 
How can i fix this?

**Comment by subhashp** [comment]
You need to enable the intl PHP extension in your PHP configuration (.ini)

Check this https://stackoverflow.com/questions/26153837/class-locale-not-found-issue-on-cakephp-3

**Comment by subhashp** [comment]
You need to enable the intl PHP extension in your PHP configuration ( .ini )
Check this [(https://stackoverflow.com/questions/26153837/class-locale-not-found-issue-on-cakephp-3)]

**Comment by judyanntaniegra** [comment]
I updated my php to vs 7.2 i am still getting the same error

**Comment by judyanntaniegra** [comment]
open your xampp>apache>config>PHP(php.ini)>*add* extension=php_intl.dll > save
