### ISSUE TITLE
/routes ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by chienit2k** [jeremykenedy/laravel-auth#127]
/routes -> /routes/ -> /routes -> /routes/ -> /routes -> ...

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by chienit2k** [comment]
I have too many redirection errors when accessing the routes page from the admin account. I used the cloud9 environment to test and encountered that error when clone this repository.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by ExtinctAmoeba** [comment]
@chienit2k 
To fix your issue, just change route name from `Route::get('routes', 'AdminDetailsController@listRoutes');` to `Route::get('YOUR_ROUTE_NAME', 'AdminDetailsController@listRoutes'); `
**File location:** /routes/web.php

And it should work fine.
