### ISSUE TITLE
Theme rendering problems

### ISSUE THREAD

**Issue by quickfood** [jeremykenedy/laravel-auth#128]
![bild 1](https://user-images.githubusercontent.com/37481475/37557918-136ea090-2a0c-11e8-9c57-b53817183453.png)
Hello together

I cloned right now the repository without any problems, followed the npm install steps, so far so good. but when starting localhost based in xampp windows 7, i get a naked construct of html elements withoud any design rendering. like if css files are missing, but i get  no errors when running npm install, watch or run dev.

I checked the app files, webpack but can't find any error. hope any of you could help me :-)

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by quickfood** [comment]
could you help me please?

**Comment by jeremykenedy** [comment]
Is this file there 'https://github.com/jeremykenedy/laravel-auth/blob/master/public/css/app.css' and readable by the file system?

If you view the page source does it show you the link to the css file?

**Comment by jeremykenedy** [comment]
This sound like it may be an issue specific to using XAMPP also:

https://stackoverflow.com/questions/40682748/assets-not-referencing-to-public-folder-laravel
https://laravel.io/forum/09-17-2014-problem-asset-not-point-to-public-folder
https://stackoverflow.com/questions/28214499/laravel-5-not-finding-css-files

**Comment by jeremykenedy** [comment]
Something is weird with your environment based on the screenshot you provided.

`/laravel-auth/public/login` is not a valid route.

Once the project is setup on the environment and if you chose to use localhost as your projects url then the route would be `/login`.

**Comment by quickfood** [comment]
hello jermey it works. I changed the file resources/views/layouts/app.blade.php like this:

![app](https://user-images.githubusercontent.com/37481475/37666967-14b297f2-2c61-11e8-9844-55052ac4f9a5.jpg)

the highlighted part in source (see attachment) i changed from mix to asset, and now it works :dancer:

**Comment by quickfood** [comment]
the only problem is that dropwdowns doesn't seem wo work when clicking

**Comment by jeremykenedy** [comment]
do the same here https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/layouts/app.blade.php#L72

**Comment by quickfood** [comment]
I did it after. Some font awesome icons in admin section (buttons) doesnt work. maybe a unicode error?

**Comment by quickfood** [comment]
when I want to call the activity route, I got this error:
![error](https://user-images.githubusercontent.com/37481475/37667859-54320d0c-2c63-11e8-8cab-7ecc40da99e4.jpg)

**Comment by quickfood** [comment]
how can i make the 2-step-verification work? in admin dashboard or where? I set it true in .env-file but when trying to log in i came this error: 
![2step](https://user-images.githubusercontent.com/37481475/37669396-063d6502-2c67-11e8-8f5e-79c075dc4207.jpg)

**Comment by jeremykenedy** [comment]
This is an issue with php artisan serve

https://stackoverflow.com/questions/29739734/how-to-include-css-in-laravel-5-running-with-artisan?rq=1

**Comment by kbtonmoy** [comment]
> I did it after. Some font awesome icons in admin section (buttons) doesnt work. maybe a unicode error?

Getting the same issue. Got any solution?

**Comment by Edbtvplays** [comment]
@jeremykenedy  i did what was done in this, and my icons arnt working. i am not using a enviroment because my PC doesnt allow for virtulisation.
