### ISSUE TITLE
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.

### ISSUE THREAD

**Issue by danielin** [jeremykenedy/laravel-auth#129]
when i do 
$ npm install
I got below warning:
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.

Kindly help!

**Comment by jeremykenedy** [comment]
Its a warning of a node package, shouldn't stop `node` or `npm`. If you wanted to remove it you would run `npm install ajv` but it doesn't seem needed.

**Comment by danielin** [comment]
npm install ajv 
this works! 
Thanks a lot!

**Comment by DevSluggish** [comment]
It worked for me as well thanks.
