### ISSUE TITLE
Auto load Issue

### ISSUE THREAD

**Issue by DhanapalMadheswaran** [jeremykenedy/laravel-auth#13]

**Comment by DhanapalMadheswaran** [comment]
Vendor File Missing

**Comment by jeremykenedy** [comment]
Not a clue. what you are talking about. This is not a real issue. Sorry, its user error. Please use some sort of search function. Closing non issue.

**Comment by jeremykenedy** [comment]
After further thinking through this, The vendor directory is generated in Step 5, when running composer. Please take the time to read the instructions before randomly creating an issue. Its bad practice.  Thanks.
