### ISSUE TITLE
Redirect to Different Page on Login

### ISSUE THREAD

**Issue by Wasca** [jeremykenedy/laravel-auth#130]
Hi Guys

I'm a little stumped, be kind to me I'm new to Laravel.

I'm simply trying to redirect user@user.com to a different url on login. Currently it goes to /home I'd like to go to /feed

I've made this change in web.php

```
//Homepage Route - Redirect based on user role is in controller.
//Route::get('/home', ['as' => 'public.home',   'uses' => 'UserController@index']);
Route::get('/feed', ['as' => 'public.feed',   'uses' => 'UserController@index']);
```

And this is in UserController.php

```
public function index()
    {
        $user = Auth::user();

        if ($user->isAdmin()) {
            return view('pages.admin.home');
        }

        //return view('pages.user.home');      
        return view('pages.user.feed', ['user' => $user]);
    }
```

After making these changes it still goes to /home. I have created the pages.user.feed blade template and and I can manually browser to /feed successfully.

What else am I missing?

Thanks

**Comment by jeremykenedy** [comment]
Are your routes cached?

**Comment by jeremykenedy** [comment]
If it’s a social registration you may also need to update https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/SocialController.php#L120

**Comment by jeremykenedy** [comment]
What happens when you run php artisan route:list? Does that list your feed route?

**Comment by jeremykenedy** [comment]
By [default](https://laravel.com/docs/5.6/authentication#included-authenticating), Laravel redirects to `/home` after a user is authenticated.

If you wanted to redirect the users to the route `/feed` after login you would specify the protected variable in the `LoginController` Example would be adding `protected $redirectTo = "/feed";` to line 32 of https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/LoginController.php

That would change all authenticated users including admins to redirect to `/feed`. You will need to add logic if you want only users to redirect.

Changing `return view('pages.user.home');` in `UserController.php` will just change the view for the `/home` route.

Be aware that there is more logic throughout this that is programmed with the assumption that the default redirects to `/home` and its logic is in place. 

Files to be aware of based on the statement above:
`ActivateController.php`, `ResetPasswordController.php`,  `SocialController.php`, `CheckIsUserActivated.php`, and `RedirectIfAuthenticated.php`,

**Comment by Wasca** [comment]
Thanks @jeremykenedy that's given me a heap more to work with, I should be right from here, I was unaware of the default routing to /home by Laravel.

Cheers Mate!

**Comment by price2b** [comment]
Just a question on this topic, and what about to redirect user back after login?.  because it seems that in laravel typical installation you can do:

if (Auth::attempt(['email' => $email, 'password' => $password])) {
    return redirect()->back();
}
being back -> back to last page. 

Do you know a way to use $redirectAfterLogout:

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectAfterLogout = '/home';

in order to return to last page? brgds.
