### ISSUE TITLE
Several social_logins for a user ?

### ISSUE THREAD

**Issue by DonDiegoAA** [jeremykenedy/laravel-auth#132]
Hello,

in the User model, the relationship with solcial_logins is 
`$this->hasMany('App\Models\Social');`

But in SocialController this line `if (empty($userCheck)) {` prevents a user from having more than one social_logins.

Is there a logical reason for this, or is it just a choice that can be changed in SocialController without problems?

Thank you.

**Comment by jeremykenedy** [comment]
You are wrong. I cannot reproduce.

https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by DonDiegoAA** [comment]
How am I wrong ?

In SocialController -> getSocialHandle, there is this code:

```
// Check if email is already registered
$userCheck = User::where('email', '=', $socialUserObject->email)->first();
$email = $socialUserObject->email;
if (!$socialUserObject->email) {
    $email = 'missing'.str_random(10).'@'.str_random(10).'.example.org';
}
if (empty($userCheck)) {
  ....
  //social_logins is created here
}
```
So if I connect with google, and then with facebook (same email accounts), the social_logins for facebook will never be created.

**Comment by DonDiegoAA** [comment]
By the way, it was only a question, not really an issue, but I don't know how to create a simple question on github...
