### ISSUE TITLE
HTML not found - if phpunit is used by GitLab CI

### ISSUE THREAD

**Issue by PrimeGhostDE** [jeremykenedy/laravel-auth#134]
Error:
PHP Fatal error:  Uncaught Error: Class 'HTML' not found in /app/Logic/Macros/HtmlMacros.php:3

![grafik](https://user-images.githubusercontent.com/13138756/38201743-911c44b8-3699-11e8-8d00-66a5f995d443.png)

I am using the latest version of laravel-auth

I hope you can help me solving this issue. Because I dont know anything else to do. As I was doing the phpunit test on my computer it didnt do the coverage - maybe the issue is in there....

Thank you.

**Comment by jeremykenedy** [comment]
I do not know, here is where that alias is defined:
https://github.com/jeremykenedy/laravel-auth/blob/master/config/app.php#L224
It is part of the this package: https://laravelcollective.com/docs/5.4/html

**Comment by PrimeGhostDE** [comment]
I have changed HTML to HtmlBuilder with a use Statement out of: Collective\Html\HtmlBuilder

The Code then looks alike:
`
<?php

use Collective\Html\HtmlBuilder;

HtmlBuilder::macro('image_link', function ($url = '', $img = '', $alt = '', $link_name = '', $param = '', $active = true, $ssl = false) {
    $url = $ssl == true ? URL::to_secure($url) : URL::to($url);
    $img = HtmlBuilder::image($img, $alt);
    $img .= $link_name;
    $link = $active == true ? HtmlBuilder::link($url, '#', $param) : $img;
    $link = str_replace('#', $img, $link);

    return $link;
});

HtmlBuilder::macro('icon_link', function ($url = '', $icon = '', $link_name = '', $param = '', $active = true, $ssl = false) {
    $url = $ssl == true ? URL::to_secure($url) : URL::to($url);
    $icon = '<i class="'.$icon.'" aria-hidden="true"></i>'.$link_name;
    $link = $active == true ? HtmlBuilder::link($url, '#', $param) : $icon;
    $link = str_replace('#', $icon, $link);

    return $link;
});

HtmlBuilder::macro('icon_btn', function ($url = '', $icon = '', $link_name = '', $param = '', $active = true, $ssl = false) {
    $url = $ssl == true ? URL::to_secure($url) : URL::to($url);
    $icon = $link_name.' <i class="'.$icon.'" aria-hidden="true"></i>';
    $link = $active == true ? HtmlBuilder::link($url, '#', $param) : $icon;
    $link = str_replace('#', $icon, $link);

    return $link;
});

// SHOW USERNAME
HtmlBuilder::macro('show_username', function () {
    $the_username = (Auth::user()->name === Auth::user()->email) ? ((is_null(Auth::user()->first_name)) ? (Auth::user()->name) : (Auth::user()->first_name)) : (((is_null(Auth::user()->name)) ? (Auth::user()->email) : (Auth::user()->name)));

    return $the_username;
});
`

It is now working for me.
Would be very nice, if you could show me some site, where I can test, if these changes affect new bugs.
(Or if you can check that for me, it would be much easier - because (IMHO) I cannot be the only one, which is affected though the bug Ive described in this issue)

Thank you very much for building this repository - it is very helpful for me and Time-Saving!
Very well done!
