### ISSUE TITLE
Route /logout/ redirects to /home/

### ISSUE THREAD

**Issue by SzymonDukla** [jeremykenedy/laravel-auth#138]
Everything installed and configured, but each time when I'm logged in and I try to go to /logout I got redirected to /home and I'm still logged in. Any ideas?

**Comment by PrimeGhostDE** [comment]
Everything working properly here. What version are you using?
Are you using the sociallite login?

**Comment by SzymonDukla** [comment]
Yes, I'm using socialite google+ login integration on the latest Laravel Auth version pulled directly from this repository.

**Comment by PrimeGhostDE** [comment]
Sorry, I dont use it. Cant help you there...
But @jeremykenedy is normally giving feedback in about 24h.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue
