### ISSUE TITLE
is it possable to disable the captcha

### ISSUE THREAD

**Issue by aaronhawkins101** [jeremykenedy/laravel-auth#14]
when working on a local dev it is impossable to get a api key for the captcha as they require a propper domain not a ip adress.

**Comment by jeremykenedy** [comment]
https://developers.google.com/recaptcha/docs/start

**Comment by aaronhawkins101** [comment]
Thank you for the quick reply. i am still having issues.
do you offer support for your package.

i currently work on a development environment that is port forwarded. 
i have set up a .tk domain so i now have a proper top level domain. 
i have set up a api key with the link provided above. i have added this to my .env file. After checking that this is on the server with the code in my .env file, i checked online, on my source code and i can see that the code has not gone from my .env file to the blade template. it seems like the code is not going from the .env file to the blade. 
i am not sure if this is a bug or something i am doing wrong. 

again thnx for the great support provided, up to now. any help with this issue would be great but i understand if you do not provide support.

Aaron

**Comment by jeremykenedy** [comment]
Its most likely an issue with your local dev environment.

To work past it while in dev you can also disable (comment out) the captacha validation check in the controller so it does not fail and proceeds with input validation.

Example:
In file  [/app/Http/Controllers/Auth/AuthController.php](https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/AuthController.php)  

You would comment out lines 87 - 90:

```
if($this->captchaCheck() == false)
{
    return redirect()->back()->withErrors(['Sorry, Wrong Captcha'])->withInput();
}
```

This allows removed the captcha validation check allowing it to continue to the input validation.

Hope that helps.

**Comment by jeremykenedy** [comment]
The project is now on Laravel 5.4 with this option on the `.env` file.
