### ISSUE TITLE
activity log "App\User' not found"

### ISSUE THREAD

**Issue by MACscr** [jeremykenedy/laravel-auth#142]
Fresh install on php 7.2 system. First got a locale error and realized i had to installed php7.2-intl. Got that sorted and now get the following error when i try to go the activity log (/activity). My logger values in my .env are the defaults. Not sure what i could be missing. What other information should i provide to help troubleshoot this and even pointing me in the right direction would be great!

```
local.ERROR: Class 'App\User' not found {"userId":1,"email":"admin@admin.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\User' not found at /var/www/laravel-app/laravel-auth/vendor/jeremykenedy/laravel-logger/src/app/Http/Controllers/LaravelLoggerController.php:53)
[stacktrace]
```

**Comment by PrimeGhostDE** [comment]
I am not at home, so got no computer to check that, but as I might remember, that should be `app\Models\User`.

**Comment by MACscr** [comment]
I are you thinking I need to change the .env file value of LARAVEL_LOGGER_USER_MODEL=App\Models\User to LARAVEL_LOGGER_USER_MODEL=app\Models\User?
Do I need to run something after I make that change? It didn’t seem to make a difference on the error.

- Mark

**Comment by MACscr** [comment]
Ah, needed to run 'php artisan config:cache' afterwords. Seems to be working now. Thanks!

**Comment by PrimeGhostDE** [comment]
No Problem :)

@MACscr 
Ive checked this environment variable in my project - its not `app` its `App`, so it was right before.
Maybe that command by artisan solved the problem.
