### ISSUE TITLE
Disable Need for Username?

### ISSUE THREAD

**Issue by MACscr** [jeremykenedy/laravel-auth#144]
I looked and didn't see anyone mention this yet and a bit surprised since email addresses are used for the actual logins, but any general advice for removing the need for usernames? Seems I would have to manually remove references from the views and change the routes to reference the user id maybe instead? I am not sure why they were even really included when emails are used for authentication. To me, they just add confusion. I am trying to go about removing them without breaking everything without doing hackish workarounds (random usernames automatically generated, but hidden. lol).

Any advice would sincerely be appreciated as I know you are simply donating your time for this project and we all really appreciate your hard work. Thanks!

**Comment by jeremykenedy** [comment]
There is no way automatically way to remove it as it part of the design. 

I wanted the username originally in addition to first and last name fields.

You have to manually remove instances of it to suit your needs.

Thank you for checking out the project.

**Comment by MACscr** [comment]
No problem. I figured that was the case. Now my hunt begins to find out where all i have to remove it.
