### ISSUE TITLE
Trying to get property 'theme_id' of non-object

### ISSUE THREAD

**Issue by PrimeGhostDE** [jeremykenedy/laravel-auth#145]
Ive fixed this by changing:

![grafik](https://user-images.githubusercontent.com/13138756/39081984-a3aba522-454b-11e8-8c16-4081589bb55d.png)

AND

![grafik](https://user-images.githubusercontent.com/13138756/39081990-b399ed9a-454b-11e8-9422-bdde3d9f3126.png)

Appears if there is no profile for new created user.

**Comment by PrimeGhostDE** [comment]
![grafik](https://user-images.githubusercontent.com/13138756/39082002-12eb856a-454c-11e8-985d-6ade5d1063c3.png)

**Comment by PrimeGhostDE** [comment]
Now it shows "No profile yet" in every settings menu - should that be expected?

**Comment by jeremykenedy** [comment]
I think that’s a modification not a fix. A profile is created once a user is activated or immediately for socialite logins.
