### ISSUE TITLE
No secret provider

### ISSUE THREAD

**Issue by Dammie234** [jeremykenedy/laravel-auth#148]
I have registered for Google reCAPTCHA and have put the secret key and site key in my .env but each time I try to register, I get an error of no secret provided. 
RuntimeException thrown with message "No secret provided"

Stacktrace:
#60 RuntimeException in C:\laragon\www\laravel-auth\vendor\google\recaptcha\src\ReCaptcha\ReCaptcha.php:62
#59 ReCaptcha\ReCaptcha:__construct in C:\laragon\www\laravel-auth\app\Traits\CaptchaTrait.php:16
#58 App\Http\Controllers\Auth\RegisterController:captchaCheck in C:\laragon\www\laravel-auth\app\Http\Controllers\Auth\RegisterController.php:60
#57 App\Http\Controllers\Auth\RegisterController:validator in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Auth\RegistersUsers.php:31
#56 App\Http\Controllers\Auth\RegisterController:register in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#55 call_user_func_array in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#54 Illuminate\Routing\Controller:callAction in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#53 Illuminate\Routing\ControllerDispatcher:dispatch in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#52 Illuminate\Routing\Route:runController in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#51 Illuminate\Routing\Route:run in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Router.php:659
#50 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\app\Http\Middleware\RedirectIfAuthenticated.php:25
#48 App\Http\Middleware\RedirectIfAuthenticated:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:67
#42 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#39 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#36 Illuminate\Session\Middleware\StartSession:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#33 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:59
#30 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#27 Illuminate\Pipeline\Pipeline:then in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Router.php:661
#26 Illuminate\Routing\Router:runRouteWithinStack in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Router.php:636
#25 Illuminate\Routing\Router:runRoute in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Router.php:602
#24 Illuminate\Routing\Router:dispatchToRoute in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Router.php:591
#23 Illuminate\Routing\Router:dispatch in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#22 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php:65
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\fideloper\proxy\src\TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\laragon\www\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in C:\laragon\www\laravel-auth\public\index.php:52

**Comment by jeremykenedy** [comment]
Open another issue without reading the reader will get you blocked.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue
