### ISSUE TITLE
Error while installing bs4 branch

### ISSUE THREAD

**Issue by JasperMulder** [jeremykenedy/laravel-auth#152]
When running npm install i'm getting the following error:

`npm ERR! code E404
npm ERR! 404 Not Found: node-sass@https://registry.npmjs.org/node-sass/-/node-sass-4.8.0.tgz`

This is probably due to the bootstrap dependency.

**Comment by WebWeave** [comment]
I have been working with @JasperMulder on this and I can reproduce this.

**Comment by jeremykenedy** [comment]
Is it on the dev branch?
