### ISSUE TITLE
sql constrain violation error in social registration

### ISSUE THREAD

**Issue by ajitdas123** [jeremykenedy/laravel-auth#157]
Hi, jeremy.
I was working with this project of your. when i was trying to do social login with facebook it was giving me SQL error stating name should be unique on this line
[On this line]
(https://github.com/jeremykenedy/laravel-auth/blob/8cff63d3cd119b9ca9eb0708ad5b9a33759f27dc/app/Http/Controllers/Auth/SocialController.php#L76)
I know this was because of the name that i m trying to create user with is already exist with same name but diff email.

So i changed it to `'name'       => md5(date('d-m-Y H:m').$email),`
That fixed the issue, but i thought of letting you know probably you can replace with something even better. :))

Thank you

**Comment by carlosiv** [comment]
i tried this solution

`// Check if email is already registered line 45
        $userCheck = User::where('email', '=', $socialUserObject->email)->first();

       if (!empty($userCheck)) {

       $nameCheck = User::where('name', '=', $socialUserObject->nickname)->first();
      
       if (!empty($nameCheck)) {
       					$username = //any logic you want here
   				}
   }`

**Comment by ajitdas123** [comment]
@carlosiv  yea, i am aware of that.i just inform about the issue. So jermy can take a look

**Comment by jeremykenedy** [comment]
Hello, this issue has been resolved in https://github.com/jeremykenedy/laravel-auth/commit/d4f1d7120ba8a4f8d6a2cf208a818a1e5be51d99

Thank you again for letting me know,

Cheers!

Jeremy
