### ISSUE TITLE
remember me checkbox is missing

### ISSUE THREAD

**Issue by judyanntaniegra** [jeremykenedy/laravel-auth#159]
Hi Guys, see picture below

![nawawala](https://user-images.githubusercontent.com/40265763/41505661-13f6b1b6-7240-11e8-9a92-e33217f6fa11.PNG)

**Comment by jeremykenedy** [comment]
Hi, this issue has been fixed in commit https://github.com/jeremykenedy/laravel-auth/commit/dc9e076ea9b2a137f87a359bb52fe8f546d33be0

Thank you!

Jeremy

**Comment by judyanntaniegra** [comment]
thank you so much!
