### ISSUE TITLE
laravel-logging

### ISSUE THREAD

**Issue by wattsie** [jeremykenedy/laravel-auth#160]
Hi,
  Found a strange issue with the ENV settings.
  Reason is, AWS Beanstalk is limited to total 4KB for all ENV variables which I am exceeding.

  As such, I have been modifying the default config parameters that are of little or no security issues so I dont need to specify them within the ENV.

  So what I am finding, on both local and hosted version, when commenting out all "laravel-logging" ENV variable in the ".env" file or ENV system, then I try to view "activity" it fails, as it is trying to look for "app/User.php", however you have it located in the App/Models/User.

  If I put the ENV variable back in, it works.

  To confirm, I did a "php artisan vendor:publish --tag=laravellogger" I modified the "﻿﻿config/laravel-logger.php" entry to
> 'defaultUserModel' => env('LARAVEL_LOGGER_USER_MODEL', 'App\Models\User')

  As such, it appears that the published config file might be ignored.

  Any suggestions.

  If not, I will keep digging later.

Cheers.

**Comment by jeremykenedy** [comment]
Hi, it is directly related to this issue: https://github.com/jeremykenedy/laravel-logger/issues/11

**Comment by wattsie** [comment]
My bad, should have looked harder in the closed issues.
Many thanks.

**Comment by jeremykenedy** [comment]
No worries, thank you very much for checking out the project! :)
