### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by mmourani** [jeremykenedy/laravel-auth#164]
Hi jeremy, 

I really like your work and coding. As such I intend to use it for my own project as a boilerplate. I wanted to know if you have some more documentation on the Auth, roles, etc and how you call the routes in the middleware. Or if you can guide me on how to add some more functionalities. 

Maroun

**Comment by jeremykenedy** [comment]
Only the readme's for the different packages used.

**Comment by romancmm** [comment]
Hello, jeremy kenedy
I'm New on Laravel.
So I can not install your laravel-auth project to see your instalation direction.
please make a instalation video tutorial, for me.
I think your laravel-auth project so helpful.
Please Its so urjent !!

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth/blob/master/README.md#installation-instructions
