### ISSUE TITLE
Command does not work

### ISSUE THREAD

**Issue by rextech03** [jeremykenedy/laravel-auth#165]
I read the instruction about making an issue but I am new to laravel I ran the command    'sudo chmod ...' but i get an error say sudo is not a recognised command please what am I doing wrong other command run perfectly. Thanks for the repo

**Comment by rextech03** [comment]
Sorry I think I sorted this out. it not a laravel issue it just to grant permission to file

**Comment by jeremykenedy** [comment]
I am glad you were able to get past it. It is a permission thing, that command a linux/mac machine will make those folders writable by the system for the cache. 

If you are a windows machine you just need to make sure those folders are writable.

Thank you for checking out the project,

Cheers! 👍
