### ISSUE TITLE
Just moving a step further

### ISSUE THREAD

**Issue by rextech03** [jeremykenedy/laravel-auth#168]
I was able to get the project work on my localhost thanks to you. I appreciate a lot but I was hoping to take a step further to add a payment gateway after login but my country can not use stripe or braintree which are the laravel supported payment gateway so I looking to implement a native php or javascript api from authorize or paystack how do I go about this any tut online or tips would help and I would greatly appreciate. Or to rephrase how do use a native php/javascript api in laravel

**Comment by jeremykenedy** [comment]
You can use a service like stripe, currently there is payment systems as part of this project. Thanks

**Comment by rextech03** [comment]
stripe is not allowed for my country that why I have to use another but most of the api come as a single .php or .js file. please assist
