### ISSUE TITLE
how to add a payment gateway

### ISSUE THREAD

**Issue by rextech03** [jeremykenedy/laravel-auth#169]
stripe and braintree are not allowed for my country that why I have to use another but most of the api come as a single .php or .js file. please assist I need to add this as I am developing the project into a membership site

**Comment by jeremykenedy** [comment]
It’s not an issue, it’s something you need to figure out.,

**Comment by jeremykenedy** [comment]
What country is it in? 

There's other services like OmniPay or BlueSnap
