### ISSUE TITLE
Why you deleted the "web" Middleware Group?

### ISSUE THREAD

**Issue by Khalilbz** [jeremykenedy/laravel-auth#17]
I'm trying to include thedevdojo/chatter with this package and I'm getting error about the class web, After looking into the kernel.php I didn't find the $middlewareGroups , What should I do ?

**Comment by jeremykenedy** [comment]
Hi there, thank you for using the repo. I did not delete the the `$middlewareGroups` from k=`kernel.php`, that is how the kernel file looked in 5.1 when this project was originally created. I later updated to 5.2 but did not touch the kernel upon updating.  I would suggest looking at the update guide to update the groups if thats what is needed.

Update from 5.1 to 5.2 Guide:
https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0

5.2 Kernel:
https://github.com/laravel/laravel/blob/5.2/app/Http/Kernel.php

5.1 Kernel:
https://github.com/laravel/laravel/blob/5.1/app/Http/Kernel.php

**Comment by jeremykenedy** [comment]
I went through thedevdojo/chatter package and was able to get it setup on L5.3 and L5.4.  It looks like the out the gates that the package is built for 5.3+ but I will git it a further look when time allows about getting going for L5.2.

**Comment by Khalilbz** [comment]
Thank you so much for your effort, Chatter is working fine on Laravel 5.2, And I'm just a beginner that's why I didn't thought about upgrading the Laravel package, and thank you so much again, because I should verify things like that from the beginning before asking the question ^_^, **So sorry**, :) :)

**Comment by jeremykenedy** [comment]
The project is now on Laravel 5.4 with the `web` middlware group.
