### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by allotmentandy** [jeremykenedy/laravel-auth#171]
this is just the sort of project i am looking for,wanted to say thanks and ask a couple of questions:

1. is there a way to disable registration with a setting? i want to use it for a closed list of people and dont want people to register.

2. is there a way to actually logout if you use google + socialite? i press the logout button, but can still access the pages. it doesnt really log me out.

thanks once again for a cool repo.

**Comment by jeremykenedy** [comment]
You would have to override the registration methods on the registration controller and remove all custom registration routes from the web.php file.
