### ISSUE TITLE
profile settings, 'save changes' button always disabled.

### ISSUE THREAD

**Issue by 181** [jeremykenedy/laravel-auth#173]
![screen shot 2018-08-14 at 4 50 04 pm](https://user-images.githubusercontent.com/6262815/44076065-2d337540-9fe2-11e8-8ff3-87655cc2ffd2.png)

**Comment by 181** [comment]
Solved by deleted the button class attribute "disabled" - line 141

**Comment by AkkuFresh** [comment]
This issue was appeared at me also, and the suggested solving works.

**Comment by jeremykenedy** [comment]
This issue has been fixed in commit: https://github.com/jeremykenedy/laravel-auth/commit/9e611dcd9620fde82572bbf889d53f9b93de5eed

Thanks!
