### ISSUE TITLE
Missing 'App\User', the app uses 'App\Models\User' path the the User model

### ISSUE THREAD

**Issue by AkkuFresh** [jeremykenedy/laravel-auth#175]
Hello Jeremy,
In the file: .../config/laravel2step.php
'defaultUserModel' => env('LARAVEL_2STEP_USER_MODEL', 'App\User'),

In the file: .../vendor/jeremykenedy/laravel2step/src/config/laravel2step.php
'defaultUserModel' => env('LARAVEL_2STEP_USER_MODEL', 'App\User'),

In the file: .../config/laravel-logger.php
'defaultUserModel' => env('LARAVEL_LOGGER_USER_MODEL', 'App\User'),

In the file: .../vendor/jeremykenedy/laravel-logger/src/config/laravel-logger.php
'defaultUserModel' => env('LARAVEL_LOGGER_USER_MODEL', 'App\User'),

in the file: .../database/factories/UserFactory.php
$factory->define(App\User::class, function (Faker $faker) {

and in the files:
.../vendor/jeremykenedy/laravel-roles/seeds/UsersTableSeeder.php
.../vendor/jeremykenedy/laravel-roles/seeds/RolesTableSeeder.php
.../vendor/jeremykenedy/laravel-roles/seeds/PermissionsTableSeeder.php
.../vendor/jeremykenedy/laravel-roles/seeds/ConnectRelationshipsSeeder.php
.../database/seeds/RolesTableSeeder.php
use App\User;

was used the 'App\User' path to the model, when the model files are located in the 'App\Models\User' path.
It cases a missing model issue.
Changing the described model path the issue was resolved.
I suggest to change the model path, or make a notice for the installation.
Unfortunately the clean Laravel 5.6 install use the 'App\User' instead of the 'App\Models\User' path.

**Comment by jeremykenedy** [comment]
The first spot you said it’s wrong calls out to the env file so you can change it there to what you need.
