### ISSUE TITLE
Broken top menu drop-downs on the Activity log page

### ISSUE THREAD

**Issue by AkkuFresh** [jeremykenedy/laravel-auth#176]
Hello Jeremy

I have just started to play with Laravel and packages, so I may write sometimes something strange, and I'm sorry for the not-fluent English.  

Testing the all features of this setup in my install in the /activity rout there was an issue with the top level drop-down menus. Both of them was broken and only this page was involved in this issue.

The necessary CSS an JS files were loaded **before** the <!DOCTYPE html> opening tag in this page.

The image will show the routes:

![activity_2018-08-16_1546](https://user-images.githubusercontent.com/6353141/44213055-2d668200-a16d-11e8-9ada-9bedc1d22b57.png)

Changing the .env parameters to true 
```
LARAVEL_LOGGER_BLADE_CSS_PLACEMENT_ENABLED=false
LARAVEL_LOGGER_BLADE_JS_PLACEMENT_ENABLED=false
```

The pagination was broken, the necessary CSS and JS was loaded **after** the <!DOCTYPE html> opening tag, but the top level menus does not work.

What you suggest, how to handle it?

**Comment by jeremykenedy** [comment]
I was unable to replicate this. They all seemed to work for me. Maybe you need to recompile the CSS with mix...
