### ISSUE TITLE
added new role (manager role)

### ISSUE THREAD

**Issue by emailsample24** [jeremykenedy/laravel-auth#179]
Hi,

I followed the steps on creating new role (manager role) and  tried to login but its directing to user page,  how to create a new page for manager role
![manager](https://user-images.githubusercontent.com/42670610/44578024-21aa3980-a7c5-11e8-8e3c-83b6cfd2e8e5.PNG)

**Comment by emailsample24** [comment]
sorry I forgot to start this post, and now I already did please help me

**Comment by jeremykenedy** [comment]
There should be a few ways to check the role.

You can do it in the routing file using a middleware group, within the controller, or inline in a blade file.


I. Here is an example in the routing file `web.php`:

```
Route::group(['middleware' => ['role:manager']], function () {
     // The manager routes 
});
```

II. Here is an example directly in a controller:
a. Using the constructor to make all methods require it:
```
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('role:manager');
    }
```
b. Check inline in the controller directly against a user object:
```
if ($user->hasRole('manager')) { // you can pass an id or slug
    // admin proceed.
}
```

III. Inline in a blade template:
a. Check against the manager role only:
```
@role('manager') // @if(Auth::check() && Auth::user()->hasRole('manager'))
    // user has manager role
@endrole
```

b. Check against multiple roles including the manager role:
```
@role('admin|manager', true) // @if(Auth::check() && Auth::user()->hasRole('admin|manager', true))
    // user has admin and manager role
@else
    // user does NOT have admin AND manager role
@endrole
```

I hope that helps :)

**Comment by jeremykenedy** [comment]
I will leave the issue open a little longer to see you though it.

**Comment by jeremykenedy** [comment]
I hope you got it going. Thanks again!

**Comment by emailsample24** [comment]
I will try those steps above and get back to you once its done, thank you so much for your help! I really really appreciate it :)

**Comment by emailsample24** [comment]
Hello, I've successfully create a page for the new role, thank you so much for your clear instruction!
