### ISSUE TITLE
Invalid text representation when IP can not be identified

### ISSUE THREAD

**Issue by sumtui** [jeremykenedy/laravel-auth#18]
Under some circumstances the IP can not be found and in this case the IP 'UNKNOWN' is returned. This value causes an exception, see below.

I got this error when running a fresh install using php artisan serve and accessing the site from the same host.

./storage/logs/laravel.log:1480:Next Illuminate\Database\QueryException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type inet: "UNKNOWN" (SQL: update "users" set "activated" = 1, "signup_confirmation_ip_address" = UNKNOWN, "updated_at" = 2017-03-31 03:04:56 where "id" = 7) in /home/username/code/laravel/laravel-auth/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

$ipAddress->getClientIp() and $this->ipAddress() returns 'UNKNOWN'.

This problem exists in the DatabaseSessionHandler.php, ActivtionRepository.php, RegisterController.php and ActivateController.php files.

**Comment by gcshri** [comment]
Around line 37 of app/Traits/CaptureIpTrait.php switch $ipaddress = 'UNKNOWN' to $ipaddress = '0.0.0.0' or whatever else you want.

**Comment by sumtui** [comment]
Thanks, that should work.

**Comment by jeremykenedy** [comment]
Thank you for letting me know. I have updated the repo to reflect the change and the default not found IP address can be managed in the `.env` file.
