### ISSUE TITLE
"Class 'Locale' not found"

### ISSUE THREAD

**Issue by SiNi-Si** [jeremykenedy/laravel-auth#180]
First great stuff mate!!  

I have everything working fine with bootstrap 3 and can use every admin task/page but loading...
http://localhost/activity

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Locale' not found

I have tried to look into my problem
1 - laravel_logger_activity Table is full of data - check
2 - checked all my settings in the .env file - check
3 - I did try adding "jeremykenedy\LaravelLogger\LaravelLoggerServiceProvider::class," under providers, 
      by it said I should not need to do that with laravel 5.6 - check
4 - ran a fresh composer require jeremykenedy/laravel-logger and cleared all cache - check
5 - tried php artisan vendor:publish --tag=laravellogger - not sure what this does.
6 - tried google for same issue - check

Is there any thing I can check?  Thanks for any insight!

Si

**Comment by SiNi-Si** [comment]
https://www.sinisoftware.net/images/log.jpg
it even shows in routes

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth/issues/125

**Comment by jeremykenedy** [comment]
It’s just a php configuration issue

**Comment by SiNi-Si** [comment]
Thanks!  Fixed.

Sorry, i didn't think to look in closed issues.  First time to GitHub.

**Comment by jeremykenedy** [comment]
No worries, thank you for checking the project out:)

**Comment by kennyendowed** [comment]
> Thanks! Fixed.
> 
> Sorry, i didn't think to look in closed issues. First time to GitHub.

pls how did u fix urs cos i cant find the solution pls

**Comment by jeremykenedy** [comment]
@kennyendowed what version of PHP are you running on what OS?

You need to install a PHP module into your server.

**Comment by kennyendowed** [comment]
> @kennyendowed what version of PHP are you running on what OS?
> 
> You need to install a PHP module into your server.
> 
> Here is the solution(s)
> 
> https://stackoverflow.com/questions/26153837/class-locale-not-found-issue-on-cakephp-3
> 
> You may need to adjust `sudo apt-get install php5-intl` to match your version of php

what version of PHP are you running on what OS?  am using 7.2 on ubuntu
and tnx for the solution 
i did this sudo apt-get install php7.2-intl
and then this  sudo service apache2 restart
