### ISSUE TITLE
Password reset problems

### ISSUE THREAD

**Issue by elirao** [jeremykenedy/laravel-auth#181]
I have problems reseting the password of user, for example when user login with gmail and than log out, how can he log in again without password. I tried to reset a password but when I click link that I receive on email it show error.
<img width="953" alt="screen shot 2018-09-09 at 17 43 57" src="https://user-images.githubusercontent.com/28750865/45266225-f3c92400-b457-11e8-8ea1-2389dd28a9b1.png">

Thanks a lot for this fantastic project!

**Comment by jeremykenedy** [comment]
Closing the issue for now. let me know if it persists and please provide duplication steps.
