### ISSUE TITLE
Swift_TransportException Cannot send message without a sender address

### ISSUE THREAD

**Issue by SiNi-Si** [jeremykenedy/laravel-auth#188]
I'm getting this message with the register form.  I'm setup for local hostmail from xampp, and when I test the mail with plain php.  The mail works fine.

Other than the .env

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=info@mydomain.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=null

and the config/mail.php
'sendmail' => '\"C:\xampp\sendmail\sendmail.exe\" -t',

what else do I need to update?  This is my error message

Swift_TransportException 
Cannot send message without a sender address
```
if (!$reversePath = $this->getReversePath($message)) {
            $this->throwException(new Swift_TransportException(
                'Cannot send message without a sender address'
                )
            );
        }
```

I have also cleared all my cache
php artisan cache:clear
php artisan route:cache
php artisan view:clear
php artisan config:cache

thanks Si

**Comment by pauubach** [comment]
Same problem.

**Comment by jeremykenedy** [comment]
You need configure email in your env.

**Comment by pauubach** [comment]
It seems to don't be taking the info from the .env file.

**Comment by jeremykenedy** [comment]
It’s all standard Laravel implementation. It’s probably your environment or your autoloader needs to be cleared.

**Comment by jeremykenedy** [comment]
https://stackoverflow.com/questions/31871806/laravel-homestead-swift-cannot-send-message-without-a-sender-address

**Comment by duytung112** [comment]
You should use the from method within your mailable class' build method, Follow the link below for more details:
https://laravel.com/docs/master/mail

**Comment by ritshidze** [comment]
php artisan config:cache

Fixed the issue for me

**Comment by aralvi** [comment]
same issue

**Comment by SufeeLatif** [comment]
php artisan config:cache
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
php artisan serve

after all this command still email not sending working
Cannot send message without a sender address

**Comment by SufeeLatif** [comment]
what should do it is laravel 8

**Comment by jeremykenedy** [comment]
Configure your email correctly.

**Comment by SufeeLatif** [comment]
Am configure it properl;y in env file too

**Comment by SufeeLatif** [comment]
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=sufeelatif@gmail.com
MAIL_PASSWORD=123456
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

**Comment by SufeeLatif** [comment]
check am addedd this in env file too

**Comment by Anupamanand3028** [comment]
Just set the MAIL_FROM_ADDRESS = from@example.com or with correct value you will not get any error.

**Comment by SufeeLatif** [comment]
> Just set the MAIL_FROM_ADDRESS = [from@example.com](mailto:from@example.com) or with correct value you will not get any error.

thanks
