### ISSUE TITLE
Improving PermissionsTableSeeder.php

### ISSUE THREAD

**Issue by gcshri** [jeremykenedy/laravel-auth#19]
Hi @jeremykenedy - Would it be possible for you to review how the databases and in particular permissions are seeded? Right now, we have the following code which seeds the initial database.

````
        if (Permission::where('name', '=', 'Can View Users')->first() === null) {
			Permission::create([
			    'name' => 'Can View Users',
			    'slug' => 'view.users',
			    'description' => 'Can view users',
			    'model' => 'Permission',
			]);
        }
````

Am never too keen to seed based on translatable strings, not very future proof and could result in errors.

I think the more appropriate way might be to use the slug as that remains a constant through the code and not an editable entity.

`````
        if (Permission::where('slug', '=', 'view.users')->first() === null) {
			Permission::create([
			    'name' => 'Can View Users',
			    'slug' => 'view.users',
			    'description' => 'Can view users',
			    'model' => 'Permission',
			]);
        }
`````

Thanks for your time and energy in creating this starter. :)

**Comment by jeremykenedy** [comment]
Closing to add to laravel-roles package.
