### ISSUE TITLE
subcopy ?

### ISSUE THREAD

**Issue by VConsulting** [jeremykenedy/laravel-auth#193]
Hello,
I just installed auth and I have the error:
Undefined variable: subcopy
After login attempt

An idea ?

**Comment by jeremykenedy** [comment]
Hello,

Thank you for checking out the project, it can possibly be something with the mail and you need to run the publish commands.

Thanks,

**Comment by VConsulting** [comment]
I will resume the install of 0
:)

**Comment by VConsulting** [comment]
To send the test mail I use MailDev a report?
https://danfarrelly.nyc/MailDev/

**Comment by VConsulting** [comment]
After reinstalling everything it's ok
Thank you :)

**Comment by VConsulting** [comment]
After reinstall always the problem.

**Comment by jeremykenedy** [comment]
I cannot replicate

**Comment by VConsulting** [comment]
I erased the line: {{$ subcopy}} from the file
/resources/views/vendor/mail/html/layout.blade.php
and it works.
What was this line used for?
