### ISSUE TITLE
How to enable 2 step verification?

### ISSUE THREAD

**Issue by yassersharaf** [jeremykenedy/laravel-auth#195]
Hi,

I'm trying to find the 2 step verification at login but can't find where can I enable it. Provide assist please. 

Image from features:

https://camo.githubusercontent.com/082ea22eed79af68ab655739dc477cb7e71cb6b6/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f6769746875622d70726f6a6563742d696d616765732f6c61726176656c32737465702f312d766572696669636174696f6e2d706167652e6a706567

Thanks and regards.

**Comment by jeremykenedy** [comment]
Please let me know if you need help. Thanks.
