### ISSUE TITLE
User Role ?

### ISSUE THREAD

**Issue by VConsulting** [jeremykenedy/laravel-auth#196]
Hello,

I wonder if it is possible to assign several Role to a User?

**Comment by jeremykenedy** [comment]
Currently, there is not. Thanks.

**Comment by jeremykenedy** [comment]
The best way is to have a role with permissions attached to it and check off the permissions.

**Comment by Tobaino1** [comment]
you can assign different roles to user but there will be a limits or set of priviledges inorder to differentiate between user ,admin and super admin
