### ISSUE TITLE
Change login from: email and password to username and password

### ISSUE THREAD

**Issue by AeroPwn** [jeremykenedy/laravel-auth#198]
I'm new to Laravel, how would i change the login page to only work with a username and a password?

**Comment by jeremykenedy** [comment]
Hello,

Thank you for checking out the project. It may take a little work but to get started you would modify a few things:

* Migration
* Model
* Model Factory
* Controllers/Methods
* Views
* Language Files

You may have to search the codebase for `first_name ` and `last_name` to catch all the places.

Here  is a list of places on the backend side of things to get started:

https://github.com/jeremykenedy/laravel-auth/blob/master/database/migrations/2014_10_12_000000_create_users_table.php

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Models/User.php

https://github.com/jeremykenedy/laravel-auth/blob/master/database/factories/ModelFactory.php

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/SocialController.php

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/UsersManagementController.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/auth/register.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/create-user.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/show-users.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/show-user.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/show-deleted-users.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/show-deleted-user.blade.php

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/usersmanagement/edit-user.blade.php

I hope that helps.
