### ISSUE TITLE
allow non-registered users to view profiles

### ISSUE THREAD

**Issue by AeroPwn** [jeremykenedy/laravel-auth#199]
Sorry for bothering you with another one of these questions but when I visit a profile page it redirects to the login. How would I allow anyone visiting the site to view a profile without being logged in?

**Comment by AeroPwn** [comment]
i tried putting:
`    
// Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'   => '{username}',
        'uses' => 'ProfilesController@show',
    ]);
`

inside of the:

`
// Public Routes
Route::group(['middleware' => ['web', 'activity']], function () {
...
}
`

**Comment by jeremykenedy** [comment]
That is protected via the controller

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/ProfilesController.php#L32

**Comment by AeroPwn** [comment]
Thanks, I managed to make it visible to everyone. It's a bit hacky but its better than nothing.

**Comment by jeremykenedy** [comment]
You can create another controller to access the profile and then re route to said controller.
