### ISSUE TITLE
Getting HttpException in Application.php line 882: on callback from Instagram

### ISSUE THREAD

**Issue by coco-itu** [jeremykenedy/laravel-auth#2]
Getting HttpException in Application.php line 882: on callback from Instagram

**Comment by jeremykenedy** [comment]
Can you give a little more specifics please, make sure that the callback is to a live web server that is originally sending the request.  Most of them cannot callback to a local dev environment.  

Do the other socialite logins work?

Sometimes for testing I can get a callback to a live website and then I copy the url data string and append it to the local URL I sent it from to trip it into thinking it just receive that response.

**Comment by jeremykenedy** [comment]
Worked fine for me.
