### ISSUE TITLE
registration form error? 

### ISSUE THREAD

**Issue by mohammedabdallah** [jeremykenedy/laravel-auth#20]
when i register say that 
"Failed to authenticate on SMTP server with username "mohamad.abdalllah@gmail.com" using 3 possible authenticators"

am used the version before this and work fine for me i'am created the app password 
and all configuration i think it's goes right 
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=465
MAIL_USERNAME=mohamad.abdalllah@gmail.com
MAIL_PASSWORD=secret
MAIL_ENCRYPTION=tls

so why this error occur ?

**Comment by jeremykenedy** [comment]
Your email is not configured correctly.

**Comment by jeremykenedy** [comment]
https://support.google.com/a/answer/176600?hl=en

**Comment by mohammedabdallah** [comment]
thnx Fixed now @jeremykenedy
