### ISSUE TITLE
Adding support in laguage in PT-Br 

### ISSUE THREAD

**Issue by nibri10** [jeremykenedy/laravel-auth#201]
I have translated all the messages into Brazilian Portuguese if you do not mind.

[translation-message-larave-auth-master.zip](https://github.com/jeremykenedy/laravel-auth/files/2522425/translation-message-larave-auth-master.zip)

**Comment by jeremykenedy** [comment]
Thank you so much!! 👍

**Comment by jeremykenedy** [comment]
Thank you so much!! 👍 This has been added :)
