### ISSUE TITLE
Multiple user authentication

### ISSUE THREAD

**Issue by aneeshaji** [jeremykenedy/laravel-auth#202]
Currently this plugin works only for single user. If there are multiple type of users like employee, admin, its still  redirect to the main login page instead of respective login pages. I am not able to find the activate function nor the redirect function of the this plugin through the email activation. 
Expecting quick replies. 
Thanks in advance.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php

**Comment by aneeshaji** [comment]
Hey,
I know that the redirect goes to ActivateController. Let me know which function is executed on Activate button click in the activation email. I think it is activate() in the ActivateController, but i can't add an echo or dd for checking this. 
Please let me know the reason ?
