### ISSUE TITLE
Email Activation Button Redirect

### ISSUE THREAD

**Issue by aneeshaji** [jeremykenedy/laravel-auth#203]
I know that the redirect goes to ActivateController. Let me know which function is executed on Activate button click in the activation email. I think it is activate() in the ActivateController, but i can't add an echo or dd for checking this.
Please let me know the reason ?

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth/blob/master/routes/web.php#L28

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L177

**Comment by aneeshaji** [comment]
@jeremykenedy 

Hope you are doing good.
In my project there are two types of users, students and faculties. I used this plugin to activate both students and faculties. For that I have used same controller. But in the current situation, whenever the user (student/faculty) clicked the activation url in the email, it redirects to the general login page(student login page). I need to redirect it to faculty login if the activation urls is for the faculty rather goes to the student.
So, I checked the **ActivateController**. But it seems its not working. I even rename the **activate** function, but clicking the link still redirect to the general login page. Then I change **Auth\ActivateController@activate** to **Auth\ActivateController@activate1**. But still there is no error.  I dnot know whats the issue here. Is the **activate function** in the **ActivateController** correct controller or not?. It will be great if you can suggest a solution for this issue.
