### ISSUE TITLE
Multiple User Activations

### ISSUE THREAD

**Issue by aneeshaji** [jeremykenedy/laravel-auth#205]
Hope you are doing good.
In my project there are two types of users, students and faculties. I used this plugin to activate both students and faculties. For that I have used same controller. But in the current situation, whenever the user (student/faculty) clicked the activation url in the email, it redirects to the general login page(student login page). I need to redirect it to faculty login if the activation urls is for the faculty rather goes to the student.
So, I checked the **ActivateController**. But it seems its not working. I even rename the **activate** function, but clicking the link still redirect to the general login page. Then I change **Auth\ActivateController@activate** to **Auth\ActivateController@activate1**. But still there is no error.  But commenting the lines correponding to the **ActivateController** in the **routes** gives error. I don't know whats the issue here. Is the **activate function** in the **ActivateController** correct controller or not?. It will be great if you can suggest a solution for this issue.

_Originally posted by @aneeshaji in https://github.com/jeremykenedy/laravel-auth/issues/203#issuecomment-434558504_

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by aneeshaji** [comment]
Hi,
Could you please answer to question ?
Now you are closing every issue without responding properly. 
Atleast please go through the mentioned comments.

**Comment by aneeshaji** [comment]
Hi,

Thanks for your great support. Keep it up...
Great day....

**Comment by jeremykenedy** [comment]
I am sorry that you cannot follow step 1. Best of luck!
