### ISSUE TITLE
Is there Step by Step How to SetUp   Twitter API in Apllication Management 

### ISSUE THREAD

**Issue by jmmedel** [jeremykenedy/laravel-auth#207]

**Comment by jeremykenedy** [comment]
Hi,
You should be able to go https://apps.twitter.com/ and complete the steps there. Once you have your credentials you should be able to plug them into the [.env](https://github.com/jeremykenedy/laravel-auth/blob/master/.env.example#L133) file.

That is to use them as a socialite provider. I am not sure how far you were wanting to take the twitter api. Thanks!


https://github.com/jeremykenedy/laravel-auth#get-socialite-login-api-keys

**Comment by jeremykenedy** [comment]
Please let me know if I can help out :)

**Comment by jmmedel** [comment]
Thanks for the reply I'm just want to set all the  Socialite Login API Keys: in the .env. The first Step is the hard part for me Step by step in the twitter developer  page create your app set in there is over overwhelming 
![screencapture-apps-twitter-app-15951050-show-2018-11-07-23_12_24](https://user-images.githubusercontent.com/32299866/48136452-0ab6b600-e2e3-11e8-8c59-004b7145fbd8.png)

Callback URL url I'm using localhost try to login  i get some error 404 not found  i dont know where to find in internet like some off the tutorial there are old i have exp on facebook socialite login system in laravel .
can You update or add to your documentation for the newbie
