### ISSUE TITLE
CRUD User Roles Management

### ISSUE THREAD

**Issue by Luigidefra** [jeremykenedy/laravel-auth#211]
Hi,
is it possible to add a view for managing user roles by the administrator? I have not found a way to add new user roles in addition to those added by seed

**Comment by jeremykenedy** [comment]
My concern with a roles CRUD is how the logic within the project that plays off the seeded roles. I could perhaps set a rule that will not allow the core ones to be changed/deleted. 

I just need more hours in the day.

**Comment by Luigidefra** [comment]
Only the role of administrator can create and modify roles.
If a role has a level higher than a seeded or already created role then he has the permissions to perform the operation.
If a role is deleted, it may not be allowed if there are users with that role or they can be downgraded to the first role with the lower level ...
I hope i helped you
