### ISSUE TITLE
  Class 'SocialiteProviders\Manager\ServiceProvider' not found  

### ISSUE THREAD

**Issue by ohakubi** [jeremykenedy/laravel-auth#214]
it s giving me this error when I try to run it.

**Comment by jeremykenedy** [comment]
I cannot replicate this.

**Comment by jeremykenedy** [comment]
It’s an environment issue. I use homestead for dev.

**Comment by jeremykenedy** [comment]
That will also he cause by if you did not run Step 5:
https://github.com/jeremykenedy/laravel-auth#installation-instructions
