### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by Sarfroz** [jeremykenedy/laravel-auth#215]
mail after registration is getting failed.

> "Cannot send message without a sender address"

**Comment by jeremykenedy** [comment]
You need to configure it in the .env file

**Comment by Sarfroz** [comment]
Silly me. Thanks working fine now.

**Comment by jeremykenedy** [comment]
No worries

**Comment by techmahedy** [comment]
https://techmahedy.com/blog/how-to-send-email-via-smtp-server/
See this link post to know briefly
