### ISSUE TITLE
Jquery and Moment for a datepicker

### ISSUE THREAD

**Issue by warmwhisky** [jeremykenedy/laravel-auth#217]
I'm trying to get a datepicker working on custom forms, but do not know where and if I need to load jquery.js or moment.js? Is this loaded with app.js or node?

**Comment by warmwhisky** [comment]
Actually I am having difficulty getting any jquery to work without breaking his package.

What is the procedure to load jquery and other third party packages?

**Comment by jeremykenedy** [comment]
It should be compiled into app js. jQuery is already loaded. If your not using it in order then it may be calling your code before it’s loaded.

**Comment by jeremykenedy** [comment]
If it’s a carriage before the horse issue you may need to call your code that is jQuery dependent inside a footer_scripts block like this: 
https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/profiles/edit.blade.php#L398

**Comment by jeremykenedy** [comment]
jQuery gets loaded for compilation here:

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/assets/js/bootstrap.js#L12

**Comment by warmwhisky** [comment]
Hey thanks for the pointer to using.
```
@section('footer_scripts')
js/css
@endsection 
```
I have only just got this working.
I was using this on another laravel-auth installation with no issue. but until I changed it to 
```
@section('footer_scripts1')
@parent
js/css
@stop

Then inside the app layout

@section('footer_scripts1') 
@show 
```
It wouldn't work. I have no idea why, but that's how I finally got my initiator code below the compiled app js

I was also having service worker and https issues which was confusing my issue further!

**Comment by warmwhisky** [comment]
> jQuery gets loaded for compilation here:
> 
> https://github.com/jeremykenedy/laravel-auth/blob/master/resources/assets/js/bootstrap.js#L12

Thanks for showing where the files are.
This package is really nice and the way it installs is so smooth!
