### ISSUE TITLE
Being Picky typo in settings.php / CaptureIpTrait.php

### ISSUE THREAD

**Issue by gcshri** [jeremykenedy/laravel-auth#22]
(Apologies, I still have to figure out how to do pull requests from my environment).

Line 23 of settings.php is:

````
nullIpAddess
````

should really be:

````
nullIpAddress
````

(missing an "r")

Corresponding change on like 37 of CaptureIpTrait.php

**Comment by jeremykenedy** [comment]
Hi,
Thank you for letting me know. I have updated the typo.
Thanks again,
Jeremy
