### ISSUE TITLE
Sendpulse with Notifications

### ISSUE THREAD

**Issue by warmwhisky** [jeremykenedy/laravel-auth#225]
Is it possible to use SendPulse to send out the activation emails and other emails that are part of your package?

Since I have SendPulse setup I find that notifications are being successfully sent to the database queue, but upon running queue:work there are no attempts in the database jobs table.

**Comment by jeremykenedy** [comment]
I would think they should be sending using the same way since they are sending off the smtp credentials from the .env file.

**Comment by jeremykenedy** [comment]
However, they are using notifications to send those.

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Logic/Activation/ActivationRepository.php#L71

Which leads me to believe you may need to use the queueble trait.

https://laravel.com/docs/5.7/notifications#queueing-notifications

**Comment by warmwhisky** [comment]
Hey,
I changed the queue value in the jobs table from `social` to `default` then it sent ok. 

Should I change the value from `social` to `default` in the construst of SendActivationEmail?

   ```
 /**
     * Create a new notification instance.
     *
     * SendActivationEmail constructor.
     *
     * @param $token
     */
    public function __construct($token)
    {
        $this->token = $token;
        $this->onQueue('social');   // Change social to default??
    }
```

**Comment by jeremykenedy** [comment]
Did you try:

```
$this->onQueue('emails');
```

**Comment by warmwhisky** [comment]
What I tried, with success, was to comment out this line `$this->onQueue('emails');` Though I am not sure if that would affect any of the other features?, but it makes activation emails work on my queue which is set `'default' => env('QUEUE_DRIVER', 'database'),` in `config/queue.php `

**Comment by jeremykenedy** [comment]
Cool, I think that will work :)

**Comment by warmwhisky** [comment]
Great! I will close this issue. Thanks so much for your help.
