### ISSUE TITLE
Disable broadcast driver and other outgoing requests

### ISSUE THREAD

**Issue by warmwhisky** [jeremykenedy/laravel-auth#226]
Hey, Happy new year!

I am trying to disable the broadcast driver with "null" but it throws an error when I "php artisan optimize" I also tried changing it to "file" but it still doesn't like that. 

I am running this on an internal intranet that has no internet by default. I am trying to stop as many outgoing requests as possible to speed up requests.

**Comment by jeremykenedy** [comment]
If you want to have 

```
BROADCAST_DRIVER=null
```

You will need to comment you line [158 of `app.php`](https://github.com/jeremykenedy/laravel-auth/blob/master/config/app.php#L158)

**Comment by warmwhisky** [comment]
Thanks Jeremy,

I did try it set to log which got me past php artisan optimize. I've now commented out [158 of app.php](https://github.com/jeremykenedy/laravel-auth/blob/master/config/app.php#L158) then setting `BROADCAST_DRIVER=null` in my .env but am still getting `app.js?id=990095a55fd3848968bd:1 GET https://stats.pusher.com/timeline/v2/jsonp/1?session=MzM3MzYyNzc2 net::ERR_NAME_NOT_RESOLVED`
This doesn't appear to be firing every few seconds now that I have commented it out of my app.php config file though.

Thanks so much for your help here.

**Comment by warmwhisky** [comment]
Thanks! This did indeed fix my issue. 

> If you comment out lines [55-64 in bootstrap.js](https://github.com/jeremykenedy/laravel-auth/blob/master/resources/assets/js/bootstrap.js#L55) then recompile the assets with `npm` or `yarn` that may fix the js error.

**Comment by warmwhisky** [comment]
Hi,

I still get these errors, but don't really understand what pusher is actually trying to push too?

I'm working on a local app. Though I have internet I always have these errors in the console.

![Untitled-1](https://user-images.githubusercontent.com/579186/74513022-42fb6a00-4f12-11ea-8a08-5b85ae3d6437.gif)

**Comment by jeremykenedy** [comment]
Is this still happening?

**Comment by warmwhisky** [comment]
Yep. Still happening and I still cannot get rid of it. 

I'd like to know what it is doing if that possible?
