### ISSUE TITLE
Integrity constraint violation: 

### ISSUE THREAD

**Issue by kennyendowed** [jeremykenedy/laravel-auth#232]
Illuminate \ Database \ QueryException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mcremm`.`profiles`, CONSTRAINT `profiles_theme_id_foreign` FOREIGN KEY (`theme_id`) REFERENCES `themes` (`id`)) (SQL: insert into `profiles` (`user_id`, `updated_at`, `created_at`) values (1, 2019-01-22 08:36:11, 2019-01-22 08:36:11))

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

I cannot duplicate this issue.

**Comment by kennyendowed** [comment]
> https://github.com/jeremykenedy/laravel-auth#opening-an-issue
> 
> I cannot duplicate this issue.

i dont get u ???

**Comment by jeremykenedy** [comment]
If you provide steps replicate the issue it’s easier to look into.

Thanks

**Comment by kennyendowed** [comment]
OK no p have fix the issues i was having i didnt installed the seed data .thank ur reply made me notice i didnt complete my installation
