### ISSUE TITLE
After Login Redirect to Intended URL

### ISSUE THREAD

**Issue by price2b** [jeremykenedy/laravel-auth#234]
I've been working with Url Previous and Redirect to Intended URL after Login.

For Url Previous I used the following code in LoginController.php and work like a charm

```
    public function showLoginForm()
    {
        session(['link' => url()->previous()]);
        return view('auth.login');
    }
    protected function authenticated(Request $request, $user)
    {
        return redirect(session('link'));
    }
```

For Intended URL I tried to Use 

`        session()->put('url.intended',url()->previous());
`
instead of 
`        session(['link' => url()->previous()]);
`
But its not working, Im receiving error:

> Object of class Illuminate\Routing\Redirector could not be converted to string

I believe this functionality is very important for eg: Ecommerce Companies. Examples are:

- Customer press button Add To Cart with a product.
- Platform request to log in the platform to move to cart.
- After Customer log in the platform, it moves to cart.

I have to questions probably you could shed light on it.

1. Do you have a suggestion of what code can I used to move customer into ('url.intended')
2. In your knowledge, do you know if other part of your code using    

>  protected $redirectAfterLogout = '/';

will be affected If I change the code in this page. Im asking because I read in -> https://github.com/jeremykenedy/laravel-auth/issues/130 and you refer to that possible situation.

thank you so much, excellent repository.

**Comment by jeremykenedy** [comment]
Your very welcome.

Is this an issue or opinion?

**Comment by price2b** [comment]
Hi Jeremy, I dont know how to create a post that its not an issue on Github. 

Based on your question, I believe it could be a good enhancement for the business case I comment in my post.

I figured out and share how to perform previousurl but I cannot figure how to create intended.url. and if will affect other areas of the code.

thank you so much.

**Comment by jeremykenedy** [comment]
I believe you would use the request class for that with something along the lines of

redirect()->intended()->getTargetUrl();

**Comment by price2b** [comment]
On Laravel 5.6 I've been working with Redirect to Intended URL after Login. The following code seems to be working ok:

    public function showLoginForm()
    {
        session(['link' => url()->previous()]);
        return view('auth.login');
    }
    public function authenticate(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            // Authentication passed...
            redirect()->intended()->getTargetUrl();

        }
    }
