### ISSUE TITLE
 Google+ APIs and OAuth requests are being shutdown on March 7, 201

### ISSUE THREAD

**Issue by keniWilliamsEst** [jeremykenedy/laravel-auth#236]
Hi there,
Do I need to do anything about this? I'm using login with google

**Comment by jeremykenedy** [comment]
It will stop working and you will have to use another service provider.

**Comment by keniWilliamsEst** [comment]
Thank you Jeremy,
Could this be an alternative to google+ ?
[https://developers.google.com/people/](https://developers.google.com/people/)
