### ISSUE TITLE
fixed error in translation for pt-br in refactoring  deleted users view  and messages for translation english and portuguese.

### ISSUE THREAD

**Issue by nibri10** [jeremykenedy/laravel-auth#237]
[resources.zip](https://github.com/jeremykenedy/laravel-auth/files/2873591/resources.zip)
Hello @jeremykenedy !

Adjustment to the new software version
I'am fixed error in translation for pt-br in refactoring  deleted users view and messages for translation english and portuguese.

Thanks!
@nibri10

**Comment by jeremykenedy** [comment]
Thank you:)

**Comment by jeremykenedy** [comment]
These have been add in PR https://github.com/jeremykenedy/laravel-auth/commit/b8014f7ab56d3b5622fa40e1614e0dd29d12a914

Thank you again!
