### ISSUE TITLE
Social Login Url Issue

### ISSUE THREAD

**Issue by sargbah84** [jeremykenedy/laravel-auth#25]
Hi, I just clone this repo, followed all the steps. Added my facebook, twitter and google+ Api keys. When I try to test logging in with Facebook, it says "The redirect_uri URL is not supported." When I try logging in with twitter, I get a 404 "Not Found" page. Can you tell me what I'm doing wrong? I have my domain names in the app settings and the .env file.

**Comment by jeremykenedy** [comment]
You redirect Uri registered with those services is invalid. Those services may not support local host or a local redirect. 

When you register for those services they ask for a callback uri. Check out the socialite documentation.
