### ISSUE TITLE
You are not logged in: You are not logged in. Please log in and try again.

### ISSUE THREAD

**Issue by mohammedabdallah** [jeremykenedy/laravel-auth#27]
when l register with FB give me this error when i logged from any where which i dont logged in facebook before ?
it should give me a sign in form of facebook to continue

**Comment by jeremykenedy** [comment]
Hi,

Thank you for reporting an error. I am not sure which error you are referring to without any error messages provided in the ticket.

I did go over the `SocialController.php` and `CheckIsUserActivated.php` and found that I need needed to update a few lines from `return redirect()->route('public.home')` to `return redirect('home')`. 

* In `SocialController.php`Lines 120 and 128.
* In `CheckIsUserActivated.php`Lines 79 and 82.

I have made the updates and pushed the code to the repository.  I was able to confirm that FaceBook login and registration is working. Looks like Facebook now allows `.local` to be a callback. 

Thank you again!
