### ISSUE TITLE
API route not executing when nested in .app 

### ISSUE THREAD

**Issue by Creekmore108** [jeremykenedy/laravel-auth#278]
I have a page which calls an API (Routes/API) and it works great when I create a page at the Views level. When I recreate it under the pages sub directory and use .app and yield(content) the API is not executing.
It doesn’t show up in the debugger bar or Telescope.
Any help with this is greatly appreciated.

**Comment by jeremykenedy** [comment]
What does the route look like in api.php?

Is it listed when you run `php artisan route:list`?

**Comment by Creekmore108** [comment]
The line of code in routes/api:
Route::resource(‘events’, ‘ScheduleController’)




Sent from my iPhone

**Comment by Creekmore108** [comment]
I can run it from the path in the browser and it returns the JSON

[image: Screen Shot 2019-04-06 at 12.45.09 PM.png]

**Comment by Creekmore108** [comment]
When I load the page by itself at the Views level rather than Views\Pages
it functions great.
Does that make any sense?

[image: Screen Shot 2019-04-06 at 1.00.06 PM.png]

**Comment by jeremykenedy** [comment]
What does the controller method look like?

**Comment by Creekmore108** [comment]
I believe it’s a JavaScript error, using DHTMLX scheduler.
I’ve rebuilt the environment a couple of times and it looks like a conflict in the JavaScript.
Thanks for looking at it.

Cheers!
Steve
