### ISSUE TITLE
ErrorException in SendActivationEmail.php line 50:

### ISSUE THREAD

**Issue by webdesign7** [jeremykenedy/laravel-auth#28]
Hello, 

Just tried a new installation and I got this error:

ErrorException in SendActivationEmail.php line 50:
Trying to get property of non-object
in SendActivationEmail.php line 50
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/var/www/servicebucket/app/Notifications/SendActivationEmail.php', 50, array('notifiable' => object(User), 'message' => object(MailMessage))) in SendActivationEmail.php line 50

Its related to namespacing .. 

Shouldnt it work out of the box or I have to adjust something ? 

What you think 

Thanks
Sergiu

<img width="1678" alt="screen shot 2017-04-21 at 14 34 55" src="https://cloud.githubusercontent.com/assets/2030016/25279886/dfc6e10a-269f-11e7-8f05-9873ce36d46e.png">

**Comment by webdesign7** [comment]
ohh.. thats after registering a new user..I am sure you know ;)

**Comment by webdesign7** [comment]
if I remove gravatar from here then it works ... 

so is the namespacing confgured okay out of the box as I see there is some incosistency around here 

What you think ?

<img width="988" alt="screen shot 2017-04-21 at 15 02 58" src="https://cloud.githubusercontent.com/assets/2030016/25280966/a7118a46-26a3-11e7-9896-f01acc6526fd.png">

Thanks
Sergiu

**Comment by jeremykenedy** [comment]
The errors are related to another error I introduced with the named route of `home` and trying to send the username in the email.  

I will fix those and let you know when they are completed.

Thank you for letting me know.

**Comment by jeremykenedy** [comment]
I need to fix line 49 of `web.php` to remove `->name('home');` and line 50 of `SendActivationEmail.php` by removing the username passed along.

**Comment by jeremykenedy** [comment]
This has been fixed and tested. Thank you again for letting me know.

**Comment by jeremykenedy** [comment]
See commit https://github.com/jeremykenedy/laravel-auth/commit/b192aca7626df0e4a93df24b9695bf62f1464089
