### ISSUE TITLE
how to integrate it with a management panel

### ISSUE THREAD

**Issue by xaiborweb** [jeremykenedy/laravel-auth#283]
how to integrate it with a management panel such as:

https://github.com/viralsolani/laravel-adminpanel
https://github.com/the-control-group/voyager
https://github.com/jeroennoten/Laravel-AdminLTE
etc...

I am a rookie in laravel I would appreciate your contribution

**Comment by jeremykenedy** [comment]
I don’t know without doing work to actually do that. It will just take some exploring. I would start with composer.
