### ISSUE TITLE
Error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() 

### ISSUE THREAD

**Issue by kwedsd** [jeremykenedy/laravel-auth#284]
I am receiving the following error:

Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in C:\laragon\www\fyw\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php on line 297

the issue occurs when a user deletes an account (Facebook), and then tries to once again login with a Facebook account, any help fixing would be appreciated.

Thanks

**Comment by jeremykenedy** [comment]
You have to remove the user from soft deletes.
