### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelauth.permissions.deleted_at' isn't in GROUP BY (SQL: select `permissions`.*, 

### ISSUE THREAD

**Issue by sscotti** [jeremykenedy/laravel-auth#285]
Not sure if this is related to my install configuration of a bug related to my MySQL version.  There is apparently a use_strict setting in MySQL v 5.7.  I am using 5.6.

The error that I am getting is for a fairly long query.

`SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelauth.permissions.deleted_at' isn't in GROUP BY (SQL: select `permissions`.*, `permission_role`.`created_at` as `pivot_created_at`, `permission_role`.`updated_at` as `pivot_updated_at` from `permissions` inner join `permission_role` on `permission_role`.`permission_id` = `permissions`.`id` inner join `roles` on `roles`.`id` = `permission_role`.`role_id` where (`roles`.`id` in (1) or `roles`.`level` < 5) and `permissions`.`deleted_at` is null group by `permissions`.`id`, `permissions`.`name`, `permissions`.`slug`, `permissions`.`description`, `permissions`.`model`, `permissions`.`created_at`, `permissions`.`updated_at`, `pivot_created_at`, `pivot_updated_at`) (View: /Users/sscotti/Desktop/laravel-auth-master/resources/views/panels/welcome-panel.blade.php) (View: /Users/sscotti/Desktop/laravel-auth-master/resources/views/panels/welcome-panel.blade.php)`

It happens right after I login with the Admin credentials, and it looks like I am getting signed in because there are entries in the database.

I am pretty new to Laravel.  I was using code from a project call "Huge" on Github, which a pretty nice bare bones MVC framework, but I was thinking about migrating to Laravel, which will require refactoring quite a bit of the code, but many of my classes will not need much modification.  Mostly the controllers and parts of the views

**Comment by sscotti** [comment]
Actually may have "solved" it.

In the database config file there is a setting to change the strict mode:

`        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', '127.0.0.1'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
            'engine'    => null,
        ],`

That seems to have fixed it, but I should probably upgrade my version of MySQL.

**Comment by Super-Chama** [comment]
I'd recommend to only disable `ONLY_FULL_GROUP_BY` mode rather than completely turning off strict mode as explained [here](https://mattstauffer.com/blog/strict-mode-and-other-mysql-customizations-in-laravel-5-2/). Add the following to _database.php_ and disable strict mode.
```
'mysql' => [
    ...
    'modes' => [
        'STRICT_ALL_TABLES',
        'ERROR_FOR_DIVISION_BY_ZERO',
        'NO_ZERO_DATE',
        'NO_ZERO_IN_DATE',
        'NO_AUTO_CREATE_USER',
    ],
],
```

**Comment by sscotti** [comment]
Thank you for the info.

Stephen D. Scotti M.D.
Some Idiots are Savants
5832 Lincoln Drive, Box 287, Edina, MN 55436
 
+16513130209
+16513130209
sscotti@sscotti.org
      

Confidentiality Notice:  

The contents of this e-mail message and any attachments are intended solely for the addressee(s) and may contain private and privileged information, and may be and should be legally protected from disclosure.  If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender, Stephen Douglas Scotti.  You should also delete this message and any attachments immediately, but that is up to your own discretion.

If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

---
Stephen D. Scotti
sscotti@sscotti.org
