### ISSUE TITLE
icons not displaying

### ISSUE THREAD

**Issue by Edbtvplays** [jeremykenedy/laravel-auth#286]
My icons on my login pages are not displaying properly or at all, this could be a Unicode error but i am new to laravel and theming and i am not sure how to fix it. 
![image](https://user-images.githubusercontent.com/31439728/59162804-4f136a00-8aef-11e9-80f6-b1c039a989cd.png)

**Comment by jeremykenedy** [comment]
Can’t replicate

**Comment by Edbtvplays** [comment]
i did what was recommened in another issue i changed the style link to asset in app.blade.php because no themeing  was displaying.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue
