### ISSUE TITLE
i got problem Address in mailbox 

### ISSUE THREAD

**Issue by reynaldy96** [jeremykenedy/laravel-auth#287]
hello sir, i got problem with
email addres..
can u tell me how to fix that ?

"Swift_RfcComplianceException
Address in mailbox given [] does not comply with RFC 2822, 3.6.2."

"    private function assertValidAddress($address)
    {
        if (!$this->emailValidator->isValid($address, new RFCValidation())) {
            throw new Swift_RfcComplianceException(
                'Address in mailbox given ['.$address.'] does not comply with RFC 2822, 3.6.2.'
            );
        }
    }"

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by kbtonmoy** [comment]
I'm facing the same problem. Can you please help?

**Comment by jeremykenedy** [comment]
You need to configure your email correctly in the end file.
