### ISSUE TITLE
Installed as shown, but error returns

### ISSUE THREAD

**Issue by Christian1998** [jeremykenedy/laravel-auth#288]
Hi, as first, thanks for the package!
I tried installing, all worked as expected but after i signed up one user and tried to login the following issue was shown: Call to a member function with() on boolean
<img width="1679" alt="error" src="https://user-images.githubusercontent.com/13522681/59570311-98872a80-9096-11e9-9058-565b98e6788c.png">

Thanks for your help.

**Comment by jeremykenedy** [comment]
1) https://github.com/jeremykenedy/laravel-auth#opening-an-issue

2) what’s the stack trace look like?

**Comment by Christian1998** [comment]
Reinstalled it completly, disabled mysql strict mode and now its all working.
