### ISSUE TITLE
Error Exception in show-user.blade.php 

### ISSUE THREAD

**Issue by webdesign7** [jeremykenedy/laravel-auth#29]
Also when I go into admin/ show a particular user it shows error below 

Did i configure the app all okay .. sorry I am a bit new to laravel so maybe I am missing something 

thanks for your assistance 
Regards
Sergiu

<img width="1677" alt="screen shot 2017-04-21 at 14 39 28" src="https://cloud.githubusercontent.com/assets/2030016/25280024/6ad90354-26a0-11e7-82e3-742bd987f66e.png">

**Comment by webdesign7** [comment]
just realised that this errors are coming up only in relation to a new user , if I click  show admin .. then it works

**Comment by webdesign7** [comment]
its related to namespace Gravatar ... which for some reason my installation cant find it .. its in vendor , in providers etc.. so not sure why is not working .. any ideas ?

**Comment by jeremykenedy** [comment]
Give me a few, I gotta get ready and go work :)

**Comment by webdesign7** [comment]
I am trying to be helpful so I am sending the screenshot with where is the Gravatar called 

<img width="988" alt="screen shot 2017-04-21 at 15 02 58" src="https://cloud.githubusercontent.com/assets/2030016/25281785/521ed9be-26a6-11e7-84f2-d9c4dbcc1711.png">

**Comment by webdesign7** [comment]
hey, sorry to have confused you .. I think the error is within this:
@if ($user->profile->avatar_status == 1)

**Comment by webdesign7** [comment]
it all works if I create a user from admin, but it doesnt work if I create a user from the frontend , probably because profile is not being automatically created , because when you show user in admin it seeks for $user->profile , which obviously doesnt exist

**Comment by jeremykenedy** [comment]
I have fixed this error.

I needed to change `$user->profile->avatar_status == 1` to `$user->profile && $user->profile->avatar_status == 1`

Thank you again.

**Comment by jeremykenedy** [comment]
See commit https://github.com/jeremykenedy/laravel-auth/commit/a6350aaf7dfac05d298c333efe5bf95e252fcb67

**Comment by webdesign7** [comment]
Perfect @jeremykenedy  all works :) Many thanks for your prompt assistance

**Comment by Quaxxon** [comment]
This fix needs to be added to the 'show-deleted-user.blade' also.  was pulling my hair out until I came here and then realized the error only appeared on unverified accounts.

**Comment by Quaxxon** [comment]
My first thought was that it was unverified accounts giving the error but after some investigation, this error only appears on ONE user account. 

that user account for some reason doesnt have a corresponding record in the 'profile' table which is throwing the error out. 

I have noticed i have multiple records with the same user_id in the profile table, will have to keep investigating. Anyway the fix you mentioned helped in my case anyway :)

**Comment by jeremykenedy** [comment]
How do I reproduce this?

**Comment by Quaxxon** [comment]
Create a new account from the /register page.
Do not activate the account
open a different browser window and /login with your admin account
go to user management in the dropdown
find user and delete
go to delete users list and click 'show' on the deleted user. 

unverified accounts dont produce a record in the profiles table which gives the error when using the account.

**Comment by Quaxxon** [comment]
I do have activation by email turned on
