### ISSUE TITLE
Wrong value at the email field of the password reset form

### ISSUE THREAD

**Issue by syssi** [jeremykenedy/laravel-auth#291]
**Describe the bug**

If I click the "password reset link" (route: /password/reset/TOKEN?email=user@user.com) the input field of the email address is populated with the value "1". If I open the URL with email parameter removed the input field is empty. 

**To Reproduce**
1. Click on 'Passwort reset'
2. Open the passwort reset mail and click the link
3. Check the value of the form input "email"

**Expected behavior**
The input field should be populated with user@user.com

**Comment by jeremykenedy** [comment]
You are going to have to take that up with Laravel as that’s out the box functionality.

**Comment by syssi** [comment]
Alright. :-)
