### ISSUE TITLE
Setup master password

### ISSUE THREAD

**Issue by imanghafoori1** [jeremykenedy/laravel-auth#294]
You may use the laravel-masterpass to enable setting up the master password to the login form to enhance the user impersonation.

https://github.com/imanghafoori1/laravel-masterpass

master password can reside in the database tables
restriction to certain roles can be defined and etc.

**Comment by jeremykenedy** [comment]
You can and if you want that as part of your app you are welcome to add.

This may be something you want for your app but not all users need this.
