### ISSUE TITLE
Is 'Login with Twitter' working? Login with Google, Github etc work fine.

### ISSUE THREAD

**Issue by connecteev** [jeremykenedy/laravel-auth#295]
Is 'Login with Twitter' working? Login with Google, Github etc work fine.

**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed
I did take a look at these. I believe this issue is new.

**Did you star the repo?**
Yes!

**Describe the bug**
Login with Twitter isn't working. I was able to get login with Google to work (and Github) to work.

**To Reproduce**

1. First I copied my app id and app secret from https://developer.twitter.com/en/apps/xxxxxx into my .env file:
```
TW_ID=xxxxxxxxxxx
TW_SECRET=xxxxxxxxxx
TW_REDIRECT=http://127.0.0.1:8000/social/handle/twitter
```
Note: TW_REDIRECT matches the app's Callback URL: http://127.0.0.1:8000/social/handle/twitter

2. Then I go to http://127.0.0.1:8000/ and click on "Login with Twitter"
3. I am immediately taken to 
https://api.twitter.com/oauth/authenticate?oauth_token=xxxxxxxxxxxxxxxxx
I do NOT see an oAuth / authorization screen from Twitter.
4. I get redirected to 
http://127.0.0.1:8000/social/handle/twitter?oauth_token=xxxxxxxxxxxxxxxxx&oauth_verifier=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
and the page shows a "Internal Server Error 500".
Also, VERY ODD...but in the users table I see an entry created with name=my twitter handle and with email: 'missingl0tPhIuT4A@HvW21egFoe.example.org'

So 
1. the email isn't being captured
2. a 500 error is seen
(although subsequent 'login with twitter' attempts allow me to access the app)

See the screenshot here: https://1ce.org/1#HylsVniMS

**Desktop:**
 - OS: Mac High Sierra
 - Browser Latest Chrome

**Comment by jeremykenedy** [comment]
You have register your app with twitter and they not allow callback to a lovalhost.

What’s the stack trace?

**Comment by connecteev** [comment]
@jeremykenedy I do have a registered app with Twitter (See above). The callback URL matches the TW_REDIRECT setting. 

I enabled debug=true in my .env and tried everthing again. This is what I now see:

```
Undefined property: Laravel\Socialite\One\User::$screen_name
ErrorException 
…/app/Http/Controllers/Auth/SocialController.php119
61
Illuminate\Foundation\Bootstrap\HandleExceptions handleError
…/app/Http/Controllers/Auth/SocialController.php119
1
Illuminate\Foundation\Http\Kernel handle
```

**Comment by jeremykenedy** [comment]
What happens if you `dd($socialUserObject)`? What does that data show in regards to keys?

**Comment by jeremykenedy** [comment]
Maybe take a look at: https://socialiteproviders.netlify.com/providers/twitter.html

**Comment by connecteev** [comment]
@jeremykenedy 
This is what i see when I do a dd($socialUserObject): 

```
User {#725 ▼
  +token: "xxxxxxxxxx"
  +tokenSecret: "xxxxxxxxxxxxxxx"
  +id: "25786037"
  +nickname: "connecteev"
  +name: "Kunal Punjabi 🇺🇸🌀😃"
  +email: null
  +avatar: "http://pbs.twimg.com/profile_images/1018313901845372928/H2tnEGu3_normal.jpg"
  +user: array:41 [▼
    "id_str" => "25786037"
    "entities" => array:1 [▶]
    "protected" => false
    "followers_count" => 180
    "friends_count" => 824
    "listed_count" => 9
    "created_at" => "Sun Mar 22 05:28:25 +0000 2009"
    "favourites_count" => 168
    "utc_offset" => null
    "time_zone" => null
    "geo_enabled" => true
    "verified" => false
    "statuses_count" => 117
    "lang" => null
    "status" => array:23 [▶]
    "contributors_enabled" => false
    "is_translator" => false
    "is_translation_enabled" => false
    "profile_background_color" => "000000"
    "profile_background_tile" => false
    "profile_link_color" => "FF691F"
    "profile_sidebar_border_color" => "000000"
    "profile_sidebar_fill_color" => "000000"
    "profile_text_color" => "000000"
    "profile_use_background_image" => false
    "has_extended_profile" => false
    "default_profile" => false
    "default_profile_image" => false
    "following" => false
    "follow_request_sent" => false
    "notifications" => false
    "translator_type" => "none"
    "suspended" => false
    "needs_phone_verification" => false
    "url" => null
    "profile_background_image_url" => "http://abs.twimg.com/images/themes/theme1/bg.png"
    "profile_background_image_url_https" => "https://abs.twimg.com/images/themes/theme1/bg.png"
    "profile_image_url" => "http://pbs.twimg.com/profile_images/1018313901845372928/H2tnEGu3_normal.jpg"
    "profile_image_url_https" => "https://pbs.twimg.com/profile_images/1018313901845372928/H2tnEGu3_normal.jpg"
    "location" => "San Francisco, CA"
    "description" => "Product Management, Design, Growth & Operations | Startup Advisor | Stanford Instructor | Speaker"
  ]
  +"avatar_original": "http://pbs.twimg.com/profile_images/1018313901845372928/H2tnEGu3.jpg"
}
```

As you can see, the email is NULL.
The DB users table stores this: missingn4Q4Rb3uUt@qV9bnuJSQn.example.org

**Comment by connecteev** [comment]
@jeremykenedy btw I did go through steps 1-4 at https://socialiteproviders.netlify.com/providers/twitter.html and confirmed everything. 

1. First time I try to log in with twitter (fresh DB):
https://prnt.sc/olle9f
(and as you can see from my previous comment, the email is NULL. The DB users table stores this: missingn4Q4Rb3uUt@qV9bnuJSQn.example.org)

2. Subsequent attempts:
https://prnt.sc/olldsk

**Comment by jeremykenedy** [comment]
It looks like this line https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/SocialController.php#L119

Needs to be changed from:
```
$user->profile()->twitter_username = $socialUserObject->screen_name;
```

to:
```
$user->profile()->twitter_username = $socialUserObject->nickname;
```

**Comment by connecteev** [comment]
@jeremykenedy yes, good catch. Tried that and this error went away: https://prnt.sc/olle9f
The front-end user experience is smooth now.

However, the email still does not populate and I see missingn4Q4Rb3uUt@qV9bnuJSQn.example.org. Does it populate for you?
Naturally the email is the most important piece of information here when you're providing a "Login with" anything.

**Comment by jeremykenedy** [comment]
There is no real email to populate if it missing and that populates from https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/SocialController.php#L64

If the user wants to use an email to login they will need to update it in their settings/profile page.

Otherwise, they will need to use their twitter account or another provider.

**Comment by connecteev** [comment]
@jeremykenedy curious if you get an email back with Twitter? I dont. 
This is really surprising that Twitter doesnt give you an email back.

**Comment by jeremykenedy** [comment]
It depends if they have an email associated with twitter account. They may have signed up through another provider on twitters end.

**Comment by connecteev** [comment]
@jeremykenedy I'm not sure I follow. The account I am using has an email associated with my Twitter account. In fact, every Twitter account *has* to have an email. Not sure if Twitter has stopped sending the email back (which would be really surprising).

**Comment by jeremykenedy** [comment]
If Twitter doesn't return it there is nothing that can be done.

**Comment by connecteev** [comment]
@jeremykenedy 
I just tried signing up for dev.to using twitter and the email gets populated in my profile. Try it!
I believe this is a bug because Twitter should return the email. Would you mind reopening this issue?

**Comment by jeremykenedy** [comment]
If Twitter doesn’t return the data I don’t think there is anything I can do. I’ll take al ok when time allows but it’s the data being returned.

**Comment by connecteev** [comment]
@jeremykenedy I know, my point is that we're probably not hitting the right Twitter endpoint and/or sending the data correctly...appreciate you taking a look.

**Comment by jeremykenedy** [comment]
From doing a quick search of the issue, it looks like it may be a security feature of the twitter API and you need to apply to get that data for your application. 

https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558/194

**Comment by connecteev** [comment]
@jeremykenedy thank you for the link. I'll reach out to Twitter to see if this can be resolved.

**Comment by jeremykenedy** [comment]
I was able to get the data to return an email with twitter.
In your twitter config located at https://developer.twitter.com/en/apps, you need to edit it,

1. Got your app settings.
2. Click on the `Permissions` tab.
3. Click edit.
4. Check the box next to `Request email address from users`.
5. Click Save.

You can see it working at https://consultjeremy.com/login

**Comment by connecteev** [comment]
@jeremykenedy that worked! Thanks for digging into it and also outlining the steps so clearly. I can't believe Twitter buried that option. Submitting a PR for Twitter now.
