### ISSUE TITLE
Add Login with Linkedin

### ISSUE THREAD

**Issue by connecteev** [jeremykenedy/laravel-auth#296]
@jeremykenedy thanks for the amazing repo. Can we add the ability to log in via Linkedin?
I tried to do it (with the intention of submitting a PR), but ran into this error and dont know how to proceed. Perhaps you can help / add this functionality to the repo?

I added this to config/services.php:
```
    'linkedin' => [
        'client_id'     => env('LINKEDIN_ID'),
        'client_secret' => env('LINKEDIN_SECRET'),
        'redirect'      => env('LINKEDIN_REDIRECT'),
    ],
```
Added this to the env file:
```
# https://www.linkedin.com/developers/apps/
LINKEDIN_ID=xxxxxxxxx
LINKEDIN_SECRET=xxxxxxxxx
LINKEDIN_REDIRECT=http://127.0.0.1:8000/social/handle/linkedin
```
I registered the app at https://www.linkedin.com/developers/apps/
and made sure that the redirect URL (under 'OAuth 2.0 settings') was set to the same LINKEDIN_REDIRECT=http://127.0.0.1:8000/social/handle/linkedin

I then went to http://127.0.0.1:8000/social/redirect/linkedin
It took me to the LinkedinAuth screen, where I gave permissions. It then redirected me back to 
```
http://127.0.0.1:8000/social/handle/linkedin?code=xxxxxxxxxxxxxxxxxxxx
```
with this error:
```
GuzzleHttp \ Exception \ ClientException (410)
Client error: `GET https://api.linkedin.com/v1/people/~:(id,first-name,last-name,formatted-name,email-address,headline,location,industry,public-profile-url,picture-url,picture-urls::(original))` resulted in a `410 Gone` response: { "errorCode": 0, "message": "This resource is no longer available under v1 APIs", "requestId": "JF28QS393D", "s (truncated...)

GuzzleHttp\Exception\ClientException 
…/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php113
74
GuzzleHttp\Exception\RequestException create
…/vendor/guzzlehttp/guzzle/src/Middleware.php66
73
GuzzleHttp\Middleware GuzzleHttp\{closure}
…/vendor/guzzlehttp/promises/src/Promise.php203
72
GuzzleHttp\Promise\Promise callHandler
…/vendor/guzzlehttp/promises/src/Promise.php156
71
GuzzleHttp\Promise\Promise GuzzleHttp\Promise\{closure}
…/vendor/guzzlehttp/promises/src/TaskQueue.php47
70
GuzzleHttp\Promise\TaskQueue run
…/vendor/guzzlehttp/promises/src/Promise.php246
69
GuzzleHttp\Promise\Promise invokeWaitFn
…/vendor/guzzlehttp/promises/src/Promise.php223
68
GuzzleHttp\Promise\Promise waitIfPending
…/vendor/guzzlehttp/promises/src/Promise.php267
67
GuzzleHttp\Promise\Promise invokeWaitList
…/vendor/guzzlehttp/promises/src/Promise.php225
66
GuzzleHttp\Promise\Promise waitIfPending
…/vendor/guzzlehttp/promises/src/Promise.php62
65
GuzzleHttp\Promise\Promise wait
…/vendor/guzzlehttp/guzzle/src/Client.php131
64
GuzzleHttp\Client request
…/vendor/guzzlehttp/guzzle/src/Client.php89
```

**Comment by jeremykenedy** [comment]
Did you take a look at: https://socialiteproviders.netlify.com/providers/linked-in.html

**Comment by connecteev** [comment]
@jeremykenedy I did, and this is where things "die":

In app//Http/Controllers/Auth/SocialController.php:
        $socialUserObject = Socialite::driver($provider)->user();

which calls
Laravel\Socialite\Two\LinkedInProvider getUserByToken
…/vendor/laravel/socialite/src/Two/AbstractProvider.php216

```
     * @return string
     */
    protected function formatScopes(array $scopes, $scopeSeparator)
    {
        return implode($scopeSeparator, $scopes);
    }
 
    /**
     * {@inheritdoc}
     */
    public function user()
    {
        if ($this->hasInvalidState()) {
            throw new InvalidStateException;
        }
 
        $response = $this->getAccessTokenResponse($this->getCode());
 
        $user = $this->mapUserToObject($this->getUserByToken(
            $token = Arr::get($response, 'access_token')
        ));
```

THis is the culprit: $token = Arr::get($response, 'access_token')

How does this tie into this?
https://socialiteproviders.netlify.com/providers/linked-in.html#retrieving-the-access-token-response-body

**Comment by jeremykenedy** [comment]
It makes it more flexible rather than tie it to a single provider.

**Comment by connecteev** [comment]
I'm just not sure how to proceed from here.

**Comment by jeremykenedy** [comment]
You may need to write a custom handler to work with LinkedIn if the out the box socialite one does not work.

You may also want to reach out to the socialite repo.

**Comment by jeremykenedy** [comment]
@connecteev I am digging into it more now.

I was able to replicate the error and in my research, I came across this: https://github.com/laravel/socialite/issues/309

**Comment by connecteev** [comment]
@jeremykenedy thanks, that's an interesting find. Seems weird that Linkedin broke their own APIs in 2018? Out of curiosity did [this](https://github.com/laravel/socialite/issues/309#issuecomment-448186024) work for you?

**Comment by jeremykenedy** [comment]
No, I am commenting on that thread as well. I'm going to sleep and will pick up when more time allows.

**Comment by connecteev** [comment]
@jeremykenedy ok sounds good..thank you for looking into it.

**Comment by connecteev** [comment]
@jeremykenedy take a look at https://github.com/ranahamza23/LinkedInAuth which is a very quick and dirty implementation of Linkedin auth. Linkedin credentials are also in the .env.example file.

The code is very basic and needs work. Also, the user info (name, email, picture, username) doesn't get saved to the DB...but most of the data is accessible in the object that comes back. Could be a good starting point.

**Comment by connecteev** [comment]
nevermind, the example above no longer works. Not sure what changed.

**Comment by jeremykenedy** [comment]
Is this still an issue? 

I never got time to circle back to this.

**Comment by connecteev** [comment]
Not anymore, I got it working...thanks! :)

**Comment by jeremykenedy** [comment]
Sweet, what was needed?

**Comment by connecteev** [comment]
I think I implemented Linkedin without using this package...can't quite remember but if I do I'll let you know.

**Comment by connecteev** [comment]
@jeremykenedy I have Linkedin working here https://github.com/connecteev/laravel-nuxt-authentication  (see the readme for detailed steps) & I think that can be easily integrated into this repo.
