### ISSUE TITLE
Getting Exception while seding emails from application 

### ISSUE THREAD

**Issue by rrajesh145** [jeremykenedy/laravel-auth#3]
Hi , I am getting flowing error while sending emails (i.e) wherever the emails is triggered in application 

Error : 
Swift_TransportException in AbstractSmtpTransport.php line 383:
Expected response code 220 but got code "", with message ""
in AbstractSmtpTransport.php line 383
at Swift_Transport_AbstractSmtpTransport->_assertResponseCode('', array('220')) in AbstractSmtpTransport.php line 289
at Swift_Transport_AbstractSmtpTransport->_readGreeting() in AbstractSmtpTransport.php line 117
at Swift_Transport_AbstractSmtpTransport->start() in Mailer.php line 79

**Comment by jeremykenedy** [comment]
The authentication failed, you need to make sure you have the mail configured in your .env file.

http://stackoverflow.com/questions/29100877/trying-to-get-laravel-5-email-to-work

**Comment by rrajesh145** [comment]
I have checked the authentication part in .env file but still i am facing this issue . And the link which have above has the error mentioned as "  "530 5.7.1 Authentication required" but it is not in my case .

**Comment by jeremykenedy** [comment]
Same issue, your auth credentials failed.
