### ISSUE TITLE
Error in composer update

### ISSUE THREAD

**Issue by vahidrezazadeh** [jeremykenedy/laravel-auth#30]
Hi
i have a problem
after run "composer update" , I see this error : 
`composer update`
`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Nothing to install or update`
`Generating autoload files`
`> Illuminate\Foundation\ComposerScripts::postUpdate`
`> php artisan optimize`
`Script php artisan optimize handling the post-update-cmd event returned with error code 255`
and when i run artisan command nothing happens

thanks guys
**vahid rezazadeh**

**Comment by jeremykenedy** [comment]
Hi,
It sounds like an issue with your environment and not the package. Are you using homestead on a windows machine?
