### ISSUE TITLE
upgrading from 5.7

### ISSUE THREAD

**Issue by evnix** [jeremykenedy/laravel-auth#300]
I have a hard time upgrading from 5.7 to 5.8

I ran the composer update, ran the migrations.
saw that there were `deleted_at` column missing for table: permissions, roles

currently have this issue:
```
ErrorException (E_ERROR)
Route [laravelroles::roles.index] not defined. (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php) (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php) (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php)

```

**Comment by avierr** [comment]
I solved that issue, but I don't know how to solve the error described above:

```
ErrorException (E_ERROR)
Route [laravelroles::roles.index] not defined. (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php) (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php) (View: /Applications/MAMP/htdocs/laravel-auth/resources/views/partials/nav.blade.php)


```

**Comment by evnix** [comment]
@jeremykenedy 
tried `composer dump-autoload`, it runs but I get the same error.
please re-open the issue, I am sure others will face the same issue while upgrading.

**Comment by jeremykenedy** [comment]
Did you make a migration to add the deleted_at column?

**Comment by jeremykenedy** [comment]
You may need to update the roles package with `composer update`

**Comment by jeremykenedy** [comment]
I am having trouble replicating this.

**Comment by evnix** [comment]
ok the other thing I missed was to copy the variables from ENV. It is working now.

so here is probably a rough upgrade guide:

- pull and merge from master branch
- composer update
- composer dump-autoload
- make sure you copy over all the new variables defined in the .env.example file
- php artisan vendor:publish everything given in the readme
- manually fix any problems missed in migration scripts

(may be polish it a bit and add it to readme?)

**Comment by eltjor** [comment]
I had the same probem. it was caused by using another .env file [MDL project]. After updating the .env file the issue was solved.
