### ISSUE TITLE
Default Admin password differs from README

### ISSUE THREAD

**Issue by aviezab** [jeremykenedy/laravel-auth#301]
**Did you star the repo?**
Yes I did

**Describe the bug**
I have followed the instruction on README, and realized the admin password seeded differs from the README after tried the USER.

![image](https://user-images.githubusercontent.com/34294278/64097202-cde60f00-cd8d-11e9-94ee-1979eedc8bab.png)

**To Reproduce**
1. Follow README carefully
2. Run `php artisan serve host=0.0.0.0`
3. Go to localhost:8000
4. Login as admin with default password: `password`

**Expected behavior**
Expected: Successfully logged in

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1903 H1
 - Browser: Opera
 - Version: 62.0.3331.116

**Comment by aviezab** [comment]
For now, I copied the USER password from database's column to Admin's, and I have successfully logged in.
![image](https://user-images.githubusercontent.com/34294278/64097336-2ddcb580-cd8e-11e9-89f5-eb67a3f6bf55.png)

**Comment by jeremykenedy** [comment]
It has to be something with the way your machine is connecting to the db.

The password is outlined in this see:
https://github.com/hamzamugabo/laravel-auth/blob/master/database/seeds/UsersTableSeeder.php#L31

and here is the user model:
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Models/User.php#L41

You may need to clear your cache with `composer dump-autoload`
