### ISSUE TITLE
Avatar with extension in uppercase

### ISSUE THREAD

**Issue by brunofaust** [jeremykenedy/laravel-auth#305]
**Did you star the repo?**
Yes

**Describe the bug**
When i upload a image with extension in uppercase, i can see the avatar.

**To Reproduce**
1. Upload profile with a image with lowercase extension - OK, i can see the avatar
2. Upload profile with a image with uppercase extension - ERROR, i can´t see the avatar, 2 images in storage folder, the avatar remains the old, with the lowercase extension.

**Expected behavior**
I can´t see the avatar after upload a image with uppercased extension.

**Desktop (please complete the following information):**
 - OS: Windows 10 / Server: Centos 7
 - Browser: Chrome
 - Version: ?

**Additional context**
none

**Comment by jeremykenedy** [comment]
Is this still an issue?
