### ISSUE TITLE
Laravel 6 don´t have the Input class

### ISSUE THREAD

**Issue by brunofaust** [jeremykenedy/laravel-auth#306]
**Did you star the repo?**
Yes

**Describe the bug**
You need to change the Input class to Request class with Laravel 6 - Input was deprecated.

**To Reproduce**
1. Update profile with a local image - error with upload.
2. Other error in another pages.

**Additional context**
I change this files:

app/Http/Controllers/ThemesManagementController.php;
app/Traits/CaptchaTrait.php;
app/Http/Controllers/Auth/SocialController.php;
app/Http/Controllers/ProfilesController.php;

1 - Change all variables "Input::" to "Request::"
2 - change "use Illuminate\Http\Request;" to "use Illuminate\Support\Facades\Request;"

**Comment by dircm** [comment]
Hi I have added a pull request to update to use Illuminate\Support\Facades\Request

**Comment by jeremykenedy** [comment]
Fixed in https://github.com/jeremykenedy/laravel-auth/pull/308
