### ISSUE TITLE
Theme index not error

### ISSUE THREAD

**Issue by Rahulsharma0810** [jeremykenedy/laravel-auth#31]
getting Error on localhost/themes

`Whoops, looks like something went wrong.
2/2
ErrorException in 0d7da4803c3fadc8dc0a815b1ea3db0e7dbc9c47.php line 75:
Trying to get property of non-object (View: /laravel-auth/resources/views/themesmanagement/show-themes.blade.php)`

**Comment by jeremykenedy** [comment]
Hello, 

Thank you for reporting this.

To fix this change line 75 of `show-themes.blade.php` from

`if($user->profile->theme_id === $aTheme->id) {`

to

`if($user->profile && $user->profile->theme_id === $aTheme->id) {`

Thanks again!

**Comment by Rahulsharma0810** [comment]
Page showed up correctly but theme operation not working
### Theme Edit and Theme View showing up error

```
Whoops, looks like something went wrong.

1/1
ErrorException in ThemesManagementController.php line 104:
Trying to get property of non-object
```

**Comment by jeremykenedy** [comment]
Same issue, same fix. It just needs to make sure that the profile exists for a user. Thanks again.
