### ISSUE TITLE
ProfilesController + ThemesManagementController use old/deprecated API

### ISSUE THREAD

**Issue by rgasch** [jeremykenedy/laravel-auth#310]
**Did you star the repo?**
Yes

**Describe the bug**
Both ProfilesController and ThemesManagementController use the "Input::" API ... code like this:
    $input = Input::only(....)
should be updated to be like this: 
    $input = $request->only(...)

**To Reproduce**
Nothing really to reproduce, it's a pure code issue.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
Linux, Chome, Apache, doesn't really matter

**Smartphone (please complete the following information):**
N/A

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth/pull/308/files
