### ISSUE TITLE
Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients  "

### ISSUE THREAD

**Issue by FlukRocker** [jeremykenedy/laravel-auth#312]
Did you star the repo?
Yes

Describe the bug
Hi i install laravel-auth by follow your docs but i have some problem
With Send Activation Email
you can create demo here
https://www.shirokami.me/

To Reproduce
Nothing really to reproduce, it's a pure code issue.

Expected behavior
N/A

Screenshots
N/A

Desktop (please complete the following information):
Client: Chrome ,Windows 10
Server: Centos7 ,Litespeed

Smartphone (please complete the following information):
N/A

**Comment by jeremykenedy** [comment]
Have to configure email in the env.
