### ISSUE TITLE
How to pull new changes

### ISSUE THREAD

**Issue by Alyssa-Cuan** [jeremykenedy/laravel-auth#313]
**First, take a look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes!

**Please describe what you are needing help with below:**
Hi, I am a student developer and my team wanted to use laravel-auth for our website. We were just wondering how we might pull new changes should you make new features or security fixes. Would we have to fix the merge conflicts ourselves? What do people normally do? Thank you so much for your time!

**Comment by jeremykenedy** [comment]
Hello,

Pull requests are welcome.

1. fork the repo.
2. Make the changes on your fork.
3. make a PR for review.

If it’s a security thing than you can email me.

Thanks,

**Comment by jeremykenedy** [comment]
And for new changes to the project, you would have to pull them in and yes resolve your merge conflicts within your project.
