### ISSUE TITLE
CDNs are making Ignition hang

### ISSUE THREAD

**Issue by warmwhisky** [jeremykenedy/laravel-auth#317]
**Did you star the repo?**
Yes 

**Please describe what you are needing help with below:**

Is there anyway to disable CDNs? I keep getting hangs on Ignition pages whilst its waiting for https://use.fontawesome.com/releases/v5.7.0/css/all.css
z

**Comment by jeremykenedy** [comment]
It may be an issue with the cdn being blocked by your network but it seems load fine for me.

**Comment by warmwhisky** [comment]
Yes. My ISP is terrible. Is there anyway I can disable CDNs so I can stop the lag?

**Comment by jeremykenedy** [comment]
You can pull it into your project with npm and the have the needed icon library copy and setup the pathing for that in the font awesome scss

**Comment by jeremykenedy** [comment]
Here is an example on another project of how to localize Font Awesome:

https://github.com/jeremykenedy/larablog/blob/master/package.json#L13
https://github.com/jeremykenedy/larablog/blob/master/webpack.mix.js#L36
https://github.com/jeremykenedy/larablog/blob/master/resources/sass/app.scss#L14

**Comment by jeremykenedy** [comment]
And thank you for all your support and for using this project!! :)

**Comment by warmwhisky** [comment]
Thank you for the pointers on how to localise Font Awesome. I have done some digging and realised it was in fact Ignition that was linking out to Font Awesome. I found someone else working in exactly the same scenario as myself; on a closed network: https://github.com/facade/ignition/issues/134

**Comment by fgilio** [comment]
👋 there's a new release of Ignition that fixes this issue 🎉 https://github.com/facade/ignition/pull/208
