### ISSUE TITLE
Upgrading from previous version

### ISSUE THREAD

**Issue by desyashasyi** [jeremykenedy/laravel-auth#321]
is there any guide how to upgrade from old version (I used Laravel Auth with Laravel 5.5)?

**First, take a look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes or No

**Please describe what you are needing help with below:**

**Comment by jeremykenedy** [comment]
Not at this time. Look through the old issues.

https://github.com/jeremykenedy/laravel-auth#opening-an-issue
