### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.roles' doesn't exist (SQL: select * from `roles` where `slug` = unverified and `roles`.`deleted_at` is null limit 1)

### ISSUE THREAD

**Issue by yogeshsharmahr** [jeremykenedy/laravel-auth#325]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.roles' doesn't exist (SQL: select * from `roles` where `slug` = unverified and `roles`.`deleted_at` is null limit 1)

**Comment by jeremykenedy** [comment]
Gotta follow the install guide.
