### ISSUE TITLE
Permission Table not found after migrate

### ISSUE THREAD

**Issue by lYesterdaYl** [jeremykenedy/laravel-auth#326]
I fresh installed the project today, and after I ran migrate. There is no permission table. And the seeding throw error cause permission table is not found. Maybe other tables are missing as well, hard to tell.

**Comment by jeremykenedy** [comment]
I cannot replicate this issue. Either your .env is misconfigured or you missed an installation step.

**Comment by lYesterdaYl** [comment]
Hi, I can see there is no create permission table file in the migration folder. is this normal?

**Comment by jeremykenedy** [comment]
It comes from the roles package and if the .env is not configured properly it will not add that migration. You have to run through all the installation steps.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles/tree/master/src/Database/Migrations
https://github.com/jeremykenedy/laravel-roles/tree/master/src/Database/Migrations
