### ISSUE TITLE
Register with Social Network with existing username

### ISSUE THREAD

**Issue by AbrarAhmed99** [jeremykenedy/laravel-auth#33]
I am really sorry for the confusion of previous post. The gif was not working properly, here is the video for it. 

https://whatsmag.com/auth.mp4

**Comment by jeremykenedy** [comment]
Still unable to reproduce
![Unable to Reproduce](https://s3-us-west-2.amazonaws.com/github-project-images/laravel-auth/laravel-auth-unable-to-replicate-round2.gif)

**Comment by jeremykenedy** [comment]
Here is that in reverse order which is working as well
![Unable to reproduce](https://s3-us-west-2.amazonaws.com/github-project-images/laravel-auth/laravel-auth-unable-to-replicate-round2a.gif)
