### ISSUE TITLE
[QUESTION] Repository Licensing

### ISSUE THREAD

**Issue by nicotravassos** [jeremykenedy/laravel-auth#330]
Hi @jeremykenedy,

I would like to use this repository within my portfolio at **nicotravassos.co.za**  but unsure of licensing as my project is private. Is the licensing required to be displayed on my site under **licensing**, **credits** or is this not required and I can just include the licensing within my repository?

Please keep in mind I will not be cloning this project and not including the commits - I will be copying most of it as I do not require some parts.

**Comment by jeremykenedy** [comment]
Hi, it’s covered under the mit license for you to use as you wish.

https://opensource.org/licenses/MIT

Thanks,

Jeremy

**Comment by nicotravassos** [comment]
Thank you @jeremykenedy
