### ISSUE TITLE
'/exceeded' goes error when visited directly

### ISSUE THREAD

**Issue by safly** [jeremykenedy/laravel-auth#335]
'/exceeded' goes error when visited directly, if the user doesn't verify his email and also doesn't reach the sending limit.
Meet this bug on refreshing after emptying the 'activations' table.

```
Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function with() on bool 
app/Http/Controllers/Auth/ActivateController.php:298
```

Besides, thank you and your awesome work!

**Comment by jeremykenedy** [comment]
Sounds about right. It should error if they didn’t confirm their email.

**Comment by safly** [comment]
Thanks for your quick response :)
I mean, it should not be a PHP Fatal Error

**Comment by safly** [comment]
![qwe](https://user-images.githubusercontent.com/10373139/76642577-73283e00-658e-11ea-8987-74493c5226c8.PNG)

**Comment by safly** [comment]
#336

**Comment by jeremykenedy** [comment]
In PR.
