### ISSUE TITLE
Should Show 404 if image does not exist

### ISSUE THREAD

**Issue by AbrarAhmed99** [jeremykenedy/laravel-auth#34]
Read the email I sent to you for the previous issue.
Here the image name "wrongname.jpg" does not exist so it should show 404 page instead of "server error page"
![image](https://cloud.githubusercontent.com/assets/10310727/26527515/6eee69a4-434a-11e7-8cc5-d75edb2776e8.png)

**Comment by jeremykenedy** [comment]
Please stop opening fake issues.
