### ISSUE TITLE
Cannot find Middleware VerifyRole

### ISSUE THREAD

**Issue by starofsky** [jeremykenedy/laravel-auth#340]
Hi,
I have suddenly error today, below is description:
 
Illuminate\Contracts\Container\BindingResolutionException
Target class [jeremykenedy\LaravelRoles\Middleware\VerifyRole] does not exist. 

![image](https://user-images.githubusercontent.com/5322431/76697367-ffd71700-66c8-11ea-8564-385dc372bbf5.png)

How can I fix it?
Thank you so much.

**Comment by starofsky** [comment]
Found root cause: conflict with Airlock package.

**Comment by starofsky** [comment]
Can we use with Airlock?

**Comment by jeremykenedy** [comment]
Airlock is a feature included in laravel 7.

This project has not been updated yet.
