### ISSUE TITLE
Roles Dashboard ('/roles'): Something gets over the <!DOCTYPE html>

### ISSUE THREAD

**Issue by safly** [jeremykenedy/laravel-auth#341]
Roles Dashboard ('/roles'): Something gets over the \<!DOCTYPE html\>

![qwe](https://user-images.githubusercontent.com/10373139/76723119-31131e00-6781-11ea-9be0-3187af724c21.PNG)
![asd](https://user-images.githubusercontent.com/10373139/76723156-4e47ec80-6781-11ea-8696-15525c6efd09.png)

**Comment by jeremykenedy** [comment]
Did you change any of the following variables:

https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L136
https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L139
https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L140
https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L141

**Comment by safly** [comment]
I didn't.  But after hours of debugging I found that it is the wrong place of Placement.

https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L127
Currently laravel-auth's app.blade uses 'template_linked_css' while it is 'inline_template_linked_css', so that the css and js won't display.

https://github.com/jeremykenedy/laravel-roles/blob/master/src/resources/views/laravelroles/crud/dashboard.blade.php#L98
But it's yield here again instead of app.blade, so it will exceed the html tag.

https://github.com/jeremykenedy/laravel-auth/blob/master/config/laravelblocker.php#L55
https://github.com/jeremykenedy/laravel-auth/blob/master/.env.example#L118
So does 'laravelblocker' in this project, but the default .env config successfully prevent this problem :)
