### ISSUE TITLE
Broken .env syntax

### ISSUE THREAD

**Issue by DBX12** [jeremykenedy/laravel-auth#343]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue :heavy_check_mark: 
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed :heavy_check_mark: 

**Did you star the repo?**
No, why should I do that for a bug report?

**Describe the bug**
Usage of `//` to comment a line instead of `#`

**To Reproduce**
1. Open `.env.example` and read line 144

**Expected behavior**
Line is commented correctly with `#` according to [spec](https://github.com/vlucas/phpdotenv#comments)

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
Not the issue described in #235 

**Note** I created this issue because I don't want to make a full fork of the project to fix one issue the IDE of the committing developer should have caught in the first place.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue
