### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by carloquilala** [jeremykenedy/laravel-auth#347]
**First, take a look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes

**Please describe what you are needing help with below:**
I was just anoyed of this deprecation warning

> Deprecation Notice: Class jeremykenedy\laravel2step\App\Http\Middleware\Laravel2step located in ./vendor/jeremykenedy/laravel2step/src/app/Http/Middleware/Laravel2step.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///tmp/build_a7ceb0c4a0e39f7906a291a18e407f33/.heroku/php/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
remote:        Deprecation Notice: Class jeremykenedy\laravel2step\App\Http\Controllers\TwoStepController located in ./vendor/jeremykenedy/laravel2step/src/app/Http/Controllers/TwoStepController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///tmp/build_a7ceb0c4a0e39f7906a291a18e407f33/.heroku/php/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

It also occurs on my local, anybody who has an idea how to fix this?

**Comment by jeremykenedy** [comment]
The standard is composers 1

**Comment by jeremykenedy** [comment]
https://getcomposer.org/

**Comment by carloquilala** [comment]
I believe I'm using

Composer version 1.9.3 2020-02-04 12:58:49

**Comment by carloquilala** [comment]
How to fix this? 

I'm using Composer version 1.9.3 2020-02-04 12:58:49
