### ISSUE TITLE
Create new profile along with account creation when email verification is set to false

### ISSUE THREAD

**Issue by peacewalkers** [jeremykenedy/laravel-auth#350]
I am trying to turn off email verification, but when I set email verification to false in .env file, activationtrait is not triggered. When a user registers for an account I have noticed that the profile is not getting created. Could you please help me find a way to create a profile along with new account creation even when the email verification is set to false.

**Comment by jeremykenedy** [comment]
It does not use the build it email verification but has its own and cannot be turned off.

**Comment by peacewalkers** [comment]
Just wanted to check if I disable email verification and upon RegisterController create function, can I skip initiate email verification and replace it with activate function in ActivateController? do you think doing that should be good?

**Comment by jeremykenedy** [comment]
After further reviewing the code I need to make an update to account for that.

**Comment by peacewalkers** [comment]
I am sure you must be busy and do not want to disturb you a lot. I am new to Laravel coding stuff, if you could please give some suggestion to implement profile creation upon registering for an account while email verification is turned off, I will try it myself.

**Comment by jeremykenedy** [comment]
This has been updated in https://github.com/jeremykenedy/laravel-auth/commit/146a4385e1291ade0a711fcb96a60f039af590c8

In the `.env` just set `ACTIVATION=false`.
