### ISSUE TITLE
Not Activated User are able to login into system

### ISSUE THREAD

**Issue by shresthasaroj0001** [jeremykenedy/laravel-auth#354]
I have been using your works alot in my project. Recently when i made a project using laravel-auth (latest), First thing i notice is login process is taking a lot time.
But my main concern is that when user registers to application, it will send email (Activation). but if user is not activated, i don't want them to login rather send them to activation required page or log out their session. something code is missing in login controller

**Comment by jeremykenedy** [comment]
You will have to adjust the flow of the app and will require some recoding. 

Once logged in they get a message that stops them from using it until they activate. So being able to initially login is part of it.

the `activated` is what stops them from going any further once logged in.
