### ISSUE TITLE
Is it possible to use this to my existing project, e.g. composer require ...?

### ISSUE THREAD

**Issue by sprklinginfo** [jeremykenedy/laravel-auth#355]
**First, take a look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
No

**Please describe what you are needing help with below:**

I am still pretty new to Laravel. I already have a project with some functions developed. but now I am thinking to add user profile/dashboard/user management related functions. But from the installation instruction, it seems that I need to clone this repo as my starting point of a new project. am I right? Thanks for any help.

**Comment by jeremykenedy** [comment]
Hi,

Sorry, it is not a package. It is a template/build-out. 

Thank you.
