### ISSUE TITLE
Discord socialite login creates # in User Profile resulting in 404 errors

### ISSUE THREAD

**Issue by dreamgeekcoder** [jeremykenedy/laravel-auth#356]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes

**Describe the bug**
When social login happens with discord.. all discord usernames are USERNAME#1234... The profile that gets created has the # in the URL and you can not edit or view the profile because of this.

**To Reproduce**
1. Install Discord Socialite Provider https://socialiteproviders.com/Discord/
2. login and authorize... user is created USERNAME#1234
3. Click View profile - https://www.xxx.com/profile/USERNAME#1234
4. 404 not found

**Expected behavior**
As all Discord usernames have this number sign ... number sign needs to be  removed when the account is created as USERNAME1234 or alternative. Name should be checked for all kinds of improper symbols?

This might be a discord socialite issue as well.. but i figured i'd ask if it was easier to fix here first as this is the script that is storing the variables.

**Comment by jeremykenedy** [comment]
You will most likely have to intercept the save in the social controller and put some logic in place to assist with that:

Somewhere in this area...

https://github.com/kepps2113/livestreamfest-laravel/blob/master/app/Http/Controllers/Auth/SocialController.php#L121
