### ISSUE TITLE
ability to check session if user session already exists or is active

### ISSUE THREAD

**Issue by peacewalkers** [jeremykenedy/laravel-auth#359]
I think the admin panel should have a condition to check if the user session already active/exists or return the user to the login page 

How is this effecting? If the user is currently logged in to the application and leaves the page inactive in the background, when the user returns to the same page at a later period of time, now when the user attempts to access a page they are redirected to 419 as the session has expired.  It would be better if they are redirected to login page rather than 419 error if the session does not exists or has expired.

**Comment by goodmuyis** [comment]
This should be Laravel issue and I think maintaining the 419 error page is ok and to let the user know what had happen, customizing the 419.blade.php with more details is much better.
It will be confusing if the user is suddenly sent to login page without notice or know what is going on.

But if you still want to go ahead with the redirection, create a middleware to handle that.

**Comment by jeremykenedy** [comment]
I agree that is is a Laravel issue. The current app is using out the box session and session lifetime. 

Like @goodmuyis suggested you can customize the 419.blade.php or add a redirect middleware to handle that.

Here is also some info on it: https://bobcares.com/blog/laravel-error-419-session-expired/
