### ISSUE TITLE
"View PHP info" puts a page within a page

### ISSUE THREAD

**Issue by judgej** [jeremykenedy/laravel-auth#36]
The `phpinfo()` command generates a complete page - all elements needed, including `html` and `body` elements. The output of `phpinfo()` seems to have been just plonked into the middle of the page without regard for this. It needs to have its body content stripped out, and just that content put into the page. Or maybe open in a new window on its own, or perhaps in an auto-resizing iframe.

**Comment by jeremykenedy** [comment]
Just replace `phpinfo()` with: 

```
				@php
					ob_start();
					phpinfo();
					$pinfo = ob_get_contents();
					ob_end_clean();
					$pinfo = preg_replace( '%^.*<body>(.*)</body>.*$%ms','$1',$pinfo);
					echo $pinfo;
				@endphp
```

**Comment by jeremykenedy** [comment]
I have updated the template and styling. Thanks for letting me know.
