### ISSUE TITLE
Error on remove permissions

### ISSUE THREAD

**Issue by kinzinho666** [jeremykenedy/laravel-auth#360]
**Did you star the repo?**
Yes

**Please describe what you are needing help with below:**

When access  http://localhost/roles, click to remove permission, open modal with:

Confirm
×
Are you sure? 

i click on CONFIRM and get error:

IMG error: 
https://ibb.co/jZ1hVsL

jquery-3.3.1.min.js:2 jQuery.Deferred exception: $(...).tooltip is not a function TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (http://localhost:8000/roles:1837:42)
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (roles:1837)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
(anonymous) @ roles:1837
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
w.readyException @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/js/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
roles:1829 Uncaught TypeError: Cannot read property 'submit' of undefined
    at HTMLButtonElement.<anonymous> (roles:1829)
    at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)

**Comment by jeremykenedy** [comment]
You may need to adjust the settings in your `.env` for where it is extending the js to.

**Comment by kinzinho666** [comment]
I use default installation, don´t change nothing.

**Comment by kinzinho666** [comment]
Error:

Uncaught TypeError: Cannot read property 'submit' of undefined

Script
$(function() {
        // Confirm Form Submit Modal
        $('#confirmDelete').on('show.bs.modal', function (e) {
            var message = $(e.relatedTarget).attr('data-message');
            var title = $(e.relatedTarget).attr('data-title');
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-body p').text(message);
            $(this).find('.modal-title').text(title);
            $(this).find('.modal-footer #confirm').data('form', form);
        });
        $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
            $(this).data('form').submit();
        });
    });

**Comment by kinzinho666** [comment]
Resolved:

Put FALSE on config/roles.php

 // jQuery
'enablejQueryCDN'               => env('ROLES_GUI_JQUERY_CDN_ENABLED', false),
'JQueryCDN'                     => env('ROLES_GUI_JQUERY_CDN_URL', 'https://code.jquery.com/jquery-3.5.1.min.js'),

Problem:
Jquery conflict
