### ISSUE TITLE
Error when calling "artisan db:seed"

### ISSUE THREAD

**Issue by RobertGasch** [jeremykenedy/laravel-auth#362]
**First, take look at:**
OK

**Did you star the repo?**
Yes

**Describe the bug**
Following your install instructions (code checked out against "35851ca yesterday 584 commits", I get the following error when running "php artisan db:seed"

-----------------------------------------------
    ~/Apache/html/: php artisan db:seed
    Seeding: DefaultBlockedTypeTableSeeder
    Seeding: DefaultBlockedItemsTableSeeder
    
    Illuminate\Contracts\Container\BindingResolutionException 

    Target class [Database\Seeds\BlockedTypeTableSeeder] does not exist.
    at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807▕ 
    808▕         try {
    809▕             $reflector = new ReflectionClass($concrete);
    810▕         } catch (ReflectionException $e) {
    ➜ 811▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812▕         }
    813▕ 
    814▕         // If the type is not instantiable, the developer is attempting to resolve
    815▕         // an abstract type such as an Interface or Abstract Class and there is
-------------------------------------------------

**To Reproduce**
Follow the install instructions until get you to "_php artisan db:seed_"

**Expected behavior**
I expected the DB to seeded without errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS (running the latest XAMPP)
 - Browser: N/A
 - Version: N/A

**Comment by jeremykenedy** [comment]
Is this is an update or a new installation?

**Comment by jeremykenedy** [comment]
If its an update. Laravel 8 changed the name of the seed folder from `seeds` to `seeders`.

In the most recent update to Laravel 8 changed it to match the conventions.

You may have either republish the seeds using the --force flag or manually update the files located here:

https://github.com/jeremykenedy/laravel-auth/tree/master/database/seeders

**Comment by zkwu168** [comment]
Hi jeremykenedy ,
I have the same problem with a newly installed Laravel 8,

**Comment by zkwu168** [comment]
I resolve the problem by changing the following in the vendor\jeremykenedy\laravel-blocker\src\LaravelBlockerServiceProvider.php

line 84,88 from : \Database\Seeds\....   to  \Database\Seeders\....

**Comment by TonyTheDev1919** [comment]
I am also having that issue changed it to seeders but not working.

**Comment by lolsamcute** [comment]
Got to vendor\jeremykenedy\laravel-blocker\src\LaravelBlockerServiceProvider.php in your Vendor package

Locate line 84,88 from

*Change from*
 if (config('laravelblocker.useSeededBlockedTypes')) {
            $this->app['seed.handler']->register(
                \Database\Seeds\BlockedTypeTableSeeder::class
            );
        }

 *To*
 if (config('laravelblocker.useSeededBlockedTypes')) {
            $this->app['seed.handler']->register(
                \Database\Seeders\BlockedTypeTableSeeder::class
            );
        }

*Change from*

        if (config('laravelblocker.useSeededBlockedItems')) {
            $this->app['seed.handler']->register(
                \Database\Seeds\BlockedItemsTableSeeder::class
            );
        }

 *To*
        if (config('laravelblocker.useSeededBlockedItems')) {
            $this->app['seed.handler']->register(
                \Database\Seeders\BlockedItemsTableSeeder::class
            );
        }

Then go and php artisan db:seed in your terminal

Enjoy

**Comment by jeremykenedy** [comment]
Thanks,

That has been changed in the package repo so its possible its pulling a cached version of the package. To be safe I added another version to make sure it pulls in the most recent version of the package.

https://github.com/jeremykenedy/laravel-blocker/blob/master/src/LaravelBlockerServiceProvider.php#L84

**Comment by jeremykenedy** [comment]
Confirmed as fixed. Thanks for reporting.

**Comment by warmwhisky** [comment]
I have this issue with adding my own seed to an already installed version. I cannot seed my table because ` Target class [Database\Seeds\BlockedTypeTableSeeder] does not exist.`

I'm using Laravel 6 version of your app so I am using the old directory "seeds" not "seeder"

Is there anything I can do about this?

**Comment by jeremykenedy** [comment]
Yeah, you can publish the seed and then move the file to a new Seeders folder

**Comment by warmwhisky** [comment]
> Yeah, you can publish the seed and then move the file to a new Seeders folder

I still get the same error. When you say Seeders folder where is the new folder and what would its name be?

**Comment by jeremykenedy** [comment]
Check out the namespace in published file. You may also have to do a computer dump auto load to pick up the updated seed

**Comment by warmwhisky** [comment]
Every time its the same error
`Target class [Database\Seeds\BlockedTypeTableSeeder] does not exist.`
