### ISSUE TITLE
Error when run composer update

### ISSUE THREAD

**Issue by starofsky** [jeremykenedy/laravel-auth#364]
It only happened today when run "composer update" 
![image](https://user-images.githubusercontent.com/5322431/94146017-8e5cfa00-fe9d-11ea-916a-88b593614585.png)

Thanks

**Comment by petruatanasiu** [comment]
Hello, Sir!
Same error here:

![composerError](https://user-images.githubusercontent.com/43036860/94158880-9449df80-fe8b-11ea-9822-8f607b434331.png)

Can you please tell us how to bypass this one?

Kind Regards

**Comment by jeremykenedy** [comment]
You need to run

```
composer self-update
```
