### ISSUE TITLE
Suggestion: run laravel-shift to detect code improvement possiblities

### ISSUE THREAD

**Issue by RobertGasch** [jeremykenedy/laravel-auth#367]
**First, take a look at:**
OK

**Did you star the repo?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Consider running [https://laravelshift.com/opinionated-laravel-way-shift](https://laravelshift.com/opinionated-laravel-way-shift) over the laravel-auth repository. I did this for a project based on your project and it found a number of issues, some of which may be good ideas to fix (not in the sense that something is broken but that the code could be improved).

Don't misunderstand what I'm saying here: your package is great ...

**Comment by jeremykenedy** [comment]
Cool, I ran it. Thank you!
