### ISSUE TITLE
Easy way to disable individual social network logins

### ISSUE THREAD

**Issue by judgej** [jeremykenedy/laravel-auth#37]
The social network login icons are all displayed through views, and can be easily removed by editing those views.

However, just removing the account details from `.env` ought to remove the facility for logging in using those networks too. A github ID of "YOURIDHERE" is fine for demonstration out of the box, and takes the user to a 404 page with that ID, as you would expect. But if I set the Github ID to "", then it makes sense for Gibhub authentication to simply be disabled - no icons, no links, no Guthub registration.

Does that sound a sensible approach?

**Comment by judgej** [comment]
Also those URLs in the `.env` for all the social logins, do they all need the same website domain and path hard-coded in there? Can a placeholder of some sort not be used here `https://{sitedomain}{rootpath}/social/handle/github` or suchlike?

**Comment by judgej** [comment]
Ta :-) I'll have a look at those URLs before creating a PR.

**Comment by jeremykenedy** [comment]
Thank you. Please make a P.R. with code review.
