### ISSUE TITLE
Adding a new layout for only Admin login

### ISSUE THREAD

**Issue by wattsie** [jeremykenedy/laravel-auth#373]
Hi Jeremy et al,
  Thanks for an excellent project.
  Have recently created a new clone to do some testing. Works well.
  However, I was testing out adding a new base layout for only the admin user login.

**Describe the bug**
Exception:
resources/views/layouts/main.blade.php:49
$theme is undefined - Make the variable optional in the blade template. Replace {{ $theme }} with {{ $theme ?? '' }}
(Please keep in mind, this is an unedited copy of "app.blade.php")

**To Reproduce**
Clone Repo, do all base setups and confirm everything is working.
Make a copy of the app layout blade to any other name:
   cp "resources/views/layouts/app.blade.php" "resources/views/layouts/main.blade.php"
Then modify "resources/views/pages/admin/home.blade.php" change first line to "@extends('layouts.main')"
Error.
If one simply changes back to "@extends('layouts.app')" it works again.
PS: Have tried using "app2, main, fred, derf" no matter the file name, still gives a theme error.
PPS: also tried clearing caches no luck.

**Expected behavior**
Page to render exactly as would with "app.blade.php" layout.

Am I going loopy... I cannot find why when extending "layout.app" has a working "theme" variable, yet an exact copy of the file, simply with a different name, does not work...

Pointers most welcome.

**Comment by jeremykenedy** [comment]
You need to run a publish and seed for the themes.

**Comment by wattsie** [comment]
Cool thanks.
By simply adding the new layout appears to have fixed it...

        View::composer(
            'layouts.app',
            \App\Http\ViewComposers\ThemeComposer::class
        );
to
        View::composer(
            ['layouts.app', 'layouts.main']
            \App\Http\ViewComposers\ThemeComposer::class
        );
