### ISSUE TITLE
how to use username instead of email for login

### ISSUE THREAD

**Issue by krutsednar** [jeremykenedy/laravel-auth#374]
hello. i'm new to laravel. it would be great if you could direct me to whichever steps i need to make.

**Comment by jeremykenedy** [comment]
Not sure off the top of my head.

**Comment by jeremykenedy** [comment]
https://laracasts.com/discuss/channels/laravel/how-to-use-authentication-using-username-instead-of-email

https://laraveldaily.com/auth-login-with-username-instead-of-email/
