### ISSUE TITLE
Laravel Passport Api redirecto lo loginpage

### ISSUE THREAD

**Issue by sorwartbb** [jeremykenedy/laravel-auth#375]
Hello good afternoon
Authentication with Laravel passport is not working in api.php. When the user makes a request to a route protected by auth: api and with a Bearer token, it redirects to the login page.

I have implemented Laravel Passport to a Laravel 8 and it has worked correctly.

I have checked the issues, and added an access token row and it still hasn't worked. I also tried it with Sanctum and the same problem, redirect to Login page.

**Comment by tyago343** [comment]
Hi, I have this same problem too. You were able to solve this problem, sorwartbb? Jeremy?

**Comment by jeremykenedy** [comment]
Laravel passport isn’t even installed in this project.

**Comment by sorwartbb** [comment]
Se que no esta instalado. Lo he instalado para autenticacion de la api.

Once implemented, I make a request with a token to an api route that goes through the middleware and instead of returning a json with data, it redirects me to the login page
I would like to know how I could solve this problem

Thank you

**Comment by adityaps13** [comment]
@sorwartbb @tyago343 Were you able to resolve this. I am also getting the same login page after authentication using passport. I am guessing this has to do with with session for api.
