### ISSUE TITLE
Parse Error when running php artisan route:list

### ISSUE THREAD

**Issue by SuperNoobi** [jeremykenedy/laravel-auth#376]
**Did you star the repo?**
Yes

**Describe the bug**
Parse Error when running php artisan route:list

**To Reproduce**
Run php artisan route:list on a fresh install

**Expected behavior**
A list of routes

**Screenshots**
![image](https://user-images.githubusercontent.com/61006209/98346591-26c7cc00-2051-11eb-87d7-8b70752df6b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - N/A
 - N/A

**Comment by jeremykenedy** [comment]
Cannot replicate
