### ISSUE TITLE
PLEASE WHAT CAN I DO THIS.. I CANT INSTALL ANY OTHER DEPENDENCIES 

### ISSUE THREAD

**Issue by lolsamcute** [jeremykenedy/laravel-auth#377]
<img width="1198" alt="Screen Shot 2020-11-09 at 9 30 51 AM" src="https://user-images.githubusercontent.com/20316857/98517591-70413280-226e-11eb-8cdf-1fcfbf3f9f34.png">

**Comment by jeremykenedy** [comment]
1. Dont type in all caps. 
2. Read the readme.
