### ISSUE TITLE
I can't get the username via social networks

### ISSUE THREAD

**Issue by KitaXvost** [jeremykenedy/laravel-auth#378]
Through all social networks - the same thing.
The app is located at - https://22zz.ru/l8-auth/public
I redirect to the same address, and if I redirect to `home`, I get a message 'Please login'.

The connection to social networks is error-free, and there are no errors in the console. 
But code in address row I getting.
Tell me how to get the username after logging in to social networks?

**Comment by jeremykenedy** [comment]
Check out this Class/Method: https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/SocialController.php#L50

**Comment by KitaXvost** [comment]
I checked the getSocialHandle function like this:
`public function getSocialHandle($provider, Request $request)
    {
      Log::info('Provider:'.$provider. ' Request:'.$request);
      /*   ...   
      */
      }`
But the function does not work at all, nothing fits in the logs
I didn't change anything in the routes, and I only added providers in the rest of the code.
Please tell me why this is happening?
