### ISSUE TITLE
Implementing File or Image upload

### ISSUE THREAD

**Issue by goodmuyis** [jeremykenedy/laravel-auth#379]
The default avatar upload works fine and for laziness sake I copied the image upload code from ProfileController.php. However, uploading the images to other locations besides `images/profile/{id}/avatar/` will return 404. I have tried something like `images/profile/4/document/` it's not working.

How get custom location to work apart from the avatar folder. Since the package is not using storage link.

Am on mobile presently and could not show working code

**Comment by jeremykenedy** [comment]
Look in profile controller

**Comment by goodmuyis** [comment]
Ok I got, it just a nice way
I have my Image uploaded in `/storage/users/id/4/documents/` below is my code and I get it to Work. Thank you so much. 


**Route**
```
    Route::get('document/{id}/get/{image}', [
        'uses' => 'App\Http\Controllers\ProfilesController@userDocView',
    ]);
```
**Image show function in the controller**
```
    public function userDocView($id, $image)  {
        return Image::make(storage_path().'/users/id/'.$id.'/documents/'.$image)->response();
    }
```

Snippet from uploading code
```
$getDoc = $request->file('file'); //bin fine
$docType = $request->docType; //doc type
$filename = $docType.'.'.$getDoc->getClientOriginalExtension();
$save_path = storage_path().'/users/id/'.$currentUser->id.'/documents/';
$public_path = '/images/profile/'.$currentUser->id.'/documents/'.$filename;
$public_path = '/document/'.$currentUser->id.'/get/'.$filename;
```

**Comment by jeremykenedy** [comment]
Yeah, that’s an older area of the project that can use a little cleanup :p
