### ISSUE TITLE
Issue with avatar file extension with DropZone upload

### ISSUE THREAD

**Issue by goodmuyis** [jeremykenedy/laravel-auth#380]
https://github.com/jeremykenedy/laravel-auth/blob/7713835de63134aa54710e2a727035c8bfbebfe1/resources/views/scripts/user-avatar-dz.blade.php#L45

The line above has a problem with static file extension created with the JS. 
=> Let say a uses upload `avatar.jpg` first and reload/refresh the page, that line will create a static JS code like below
``$('#user_selected_avatar, .user-avatar-nav').attr('src', '/images/profile/4/avatar/avatar.jpg?' + new Date().getTime());``

=> If a user now decide upload another image `avatar.png` the line above will not update to the new uploaded even if i reload the page it will be using old avatar.jpg and we may end-up having `avatar.jpg`, `avatar.png`, `avatar.jpeg`  in the same folder yet old avatar.jpg will be shown except your upload different .jpg file.

It doesn't make much sense when I tried changing the lines to below, which will require page reload for new image to show
``$('#user_selected_avatar, .user-avatar-nav').attr('src', '/images/profile/{{ $user->id }}/avatar/{{$user->profile->avatar}}?' + new Date().getTime());``

**Comment by goodmuyis** [comment]
So here is what I did:
``var url = response['path'];
var avatar = url.split('/').pop().split('#')[0].split('?')[0];
$('#user_selected_avatar, .user-avatar-nav').attr('src', '/images/profile/{{ $user->id }}/avatar/'+avatar+'?' + new Date().getTime());``

The two lines above is used to the file url from the ajax response, take out the filename and fixed it into image src url

**Comment by jeremykenedy** [comment]
It’s because the rules only accept one kind of file and if you want it different you have to adjust the method  in the profile controller
