### ISSUE TITLE
Route [laravelroles::roles.index] not defined

### ISSUE THREAD

**Issue by RobertGasch** [jeremykenedy/laravel-auth#382]
**Did you star the repo?**
Yes

**Describe the bug**
Accessing the admin section results in the following error: 

    Symfony\Component\Routing\Exception\RouteNotFoundException
    Route [laravelroles::roles.index] not defined. (View: /Users/robert.gasch/Code/tutor.lan/resources/views/partials/nav.blade.php)

**To Reproduce**
Log in as admin and attempt to access the admin section

**Expected behavior**
A properly rendered view

**Additional context**
Commenting out the reference to this route results in a working admin area, so it's specific to this route and my install is not fundamentally broken.

**Comment by Mokei-it** [comment]
I had the same problem.
I solved adding in .ENV the lines related to ROLES:
# Roles Default Models
# Roles database information
# Roles Misc Settings
# Roles GUI Settings
