### ISSUE TITLE
Enhancement Request: Multiple Roles Per User

### ISSUE THREAD

**Issue by MarkAusten** [jeremykenedy/laravel-auth#383]
The project I am currently developing will have around 250 separate permissions by the time it is completed and there are about 8 different type of user not including the admin and super-admin roles (it's a **big** project!). Many of the user groups will overlap with others in terms of permissions and it would vastly improved the system if users were able to have several roles, and not just the one assigned to the user on creation.

For example, I have Addresses, Customers, Magazines, Schedules and many more, but just using those four tables, that will be at least 6 permissions required per table, Create, Update, View, Delete, Import and Export. That's 24 separate permissions just for those 4 tables. 

The database has at least 50 tables and many other permissions will be required. Creating a new role for each user is going to be tiresome at best and downright impossible at worst with the system as it stands..

However, if I were able to create roles like this: 

address.maintenance, 
customer.maintenance, 
magazine.maintenance, 
schedule.maintenance 

and so on and assign more than one role to each user, then I will be able to reduce the maintenance burden considerably. One user may have the address and customer maintenance roles, another the magazine and address maintenance roles and so on.

Now that may well not be possible with the way you have structured laravel-auth, but I am suggesting this enhancement for consideration in the future.

As it stands, although a fine piece of work, it's too limited for the type of projects I develop.

Many thanks.

**Comment by jeremykenedy** [comment]
Thank you. It supports multiple roles, you can add them to your seeders as needed.

**Comment by MarkAusten** [comment]
Reseeding the tables whenever you need an new set of roles is a pretty daft idea. Okay if you have a static system that never changes but useless otherwise.

As far as I can tell the system you have developed assigns a role once and once only. If you want to change the role a user has you have to deleted and recreate the user record as there is no way in your system to edit the roles a user has been assigned.

Now, that would mean adding or modifying what you have done and if that is the case, then I'll be better off just rolling my own since I don not have the time on this project to figure out what you have done and why. Quicker and easier to start again and just build what I need for this project. However in future, I'd like to use this system as it is pretty comprehensive.

The enhancement request stands. Please add multi-role management to the system so that roles may be added and removed from the user using the user edit pages.

Thanks.
