### ISSUE TITLE
integrating laravel-auth into an existing laravel app -- best practice?

### ISSUE THREAD

**Issue by huna02** [jeremykenedy/laravel-auth#386]
I've an existing Laravel app

It's available on an nginx server at

	http://frontend.example.com

I've installed laravel-auth separately; It's available on the nginx server at

	http://backend-auth.example.com:10001

I'd like to integrate laravel-auth as the user/identity/auth mgmt solution for my main/existing app.

I suppose I can either drop laravel-auth into a subdir in nginx config, e.g.

	http://frontend.example.com/login

&/or add to

```
/routes/web.php

	Route::get('/login', function(){
		return redirect('http://backend-auth.example.com:10001');
	});
```	

I'm not yet clear re: the extent of what's needed/recommended.

Is there an available doc/example of integrating laravel-auth into an existing app?

**Comment by jeremykenedy** [comment]
It's not a package, but a project. You will have to take the code you wanted as needed.

**Comment by huna02** [comment]
not what I asked, but ok.  thanks anyway.

**Comment by jeremykenedy** [comment]
Socialcontroller.php is what you need to look at for what you want.
