### ISSUE TITLE
Composer update problem

### ISSUE THREAD

**Issue by marll** [jeremykenedy/laravel-auth#387]
Hi,
following the error with php 8:

Problem 1
    - Root composer.json requires socialiteproviders/generators >=4.6.1 -> satisfiable by socialiteproviders/generators[v4.6.1].
    - socialiteproviders/generators v4.6.1 requires php ^5.6 || ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires socialiteproviders/instagram ^3.0 -> satisfiable by socialiteproviders/instagram[v3.0.0].
    - socialiteproviders/instagram v3.0.0 requires php ^5.6 || ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires socialiteproviders/linkedin ^3.1 -> satisfiable by socialiteproviders/linkedin[v3.1].
    - socialiteproviders/linkedin v3.1 requires php ^5.6 || ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 4
    - jeremykenedy/laravel-roles[v3.5.0, ..., v3.8.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires jeremykenedy/laravel-roles ^3.5 -> satisfiable by jeremykenedy/laravel-roles[v3.5.0, v3.6.0, v3.7.0, v3.8.0].
    
Thanks

**Comment by jeremykenedy** [comment]
Issue in these repos:

```
socialiteproviders/generators
socialiteproviders/instagram
socialiteproviders/linkedin
```

and you are using an outdated version of `laravel-roles`

look at the composer.json to make sure you are using the most recent versions and run `composer dump-autoload`
