### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by moktan456** [jeremykenedy/laravel-auth#388]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes or No

**Describe the bug**
All installation works fine, except the login page. It give 404 page not found error

**Comment by moktan456** [comment]
I followed all the instructions carefully but still got error. Everythings works fine except when i open app and login, it gives an error 404 page not found

**Comment by jeremykenedy** [comment]
It's probably hour environment configuration. Cannot replicat.

**Comment by jeremykenedy** [comment]
I would suggest reading the Laravel documentation or taking a course on Laravel.
