### ISSUE TITLE
 LogicException    Unable to prepare route [logout] for serialization. Another route has already been assigned name [logout].

### ISSUE THREAD

**Issue by Mokei-it** [jeremykenedy/laravel-auth#389]
Hello there,

- a fresh Laravel-auth v8.2.0 installation.
- followed all 12 steps Installation Instructions.
- Npm and built cache.
- "php artisan route:cache" returns logic exception in the subject.

Does it happen to me only?
Am I missing something?

- PHP 7.4.1
- Windows 10, 20H2
- Wampserver 3.2.5

![UnableToPrepareRoute](https://user-images.githubusercontent.com/29811854/115039589-e22e3f80-9ed0-11eb-8c10-d4c03186e3a7.jpg)

**Comment by Occul77rick5** [comment]
It happened to me today as well, I havent dug into it too deeply yet, but I believe it is becausse in the resource for the logout route it is used twice in the core laravel-auth files. But havent dug into it deeply enough yet. I have other issues :)

**Comment by ImTheRealOne** [comment]
Hi all, does anyone have an update for this issue. Just ran into this issue as well.

**Comment by jeremykenedy** [comment]
Just comment out this line: 

https://github.com/jeremykenedy/laravel-auth/blob/master/routes/web.php#L50

It will be removed from the project later.

Thanks,

**Comment by ImTheRealOne** [comment]
Thank you.

I assume we remove 
  Unable to prepare route [profile/{username}/updateUserAccount] for serialization. Another route has already been assigned name [{username}].

**Comment by jeremykenedy** [comment]
Is this still an issue?
