### ISSUE TITLE
Translating plurals

### ISSUE THREAD

**Issue by judgej** [jeremykenedy/laravel-auth#39]
Laravel has a built-in way to translate plural text. At the moment you have this in a template:

```php
@php
  $levelAmount = trans('usersmanagement.labelUserLevel');
  if ($user->level() >= 2) {
      $levelAmount = trans('usersmanagement.labelUserLevels');
  }
@endphp
```

    {{ trans('usersmanagement.labelAccessLevel')}} {{ $levelAmount }}:

Several problems (if we are being pedantic, which we should be):

* The phrase is constructed from two parts put next to each other. That may not work in all languages as structure can change when phrases become plural.
* There is PHP in the view. *Yuch!*

Instead you can use this for the full phrase:

    {{ trans_choice('usersmanagement.labelAccessLevel', $user->level()) }}

Then the English string would look like this:

    'labelAccessLevel'  => '[0,1]Access Level|[2,*]Access Levels',

The first *[0,1]* may not be needed. No additional PHP is needed.

In addition , `__()` is a shortcut for `trans()`, which can sometimes look neater (takes some words out of a busy view). In views it can be shorted to `@lang()` (according to the docs, though never tried it):

    @lang('usersmanagement.labelStatus')

**Comment by jeremykenedy** [comment]
Please make P.R.'s with code reviews. Thanks you
