### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by deadlance** [jeremykenedy/laravel-auth#390]
Fresh install, went to do composer update, I get the following (I'll downgrade to PHP 7, just wanted to let you know, in case you hadn't see this yet. BTW, love this whole kit.  Makes my life so much easier when standing up simple apps with the need for permissions.)

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires socialiteproviders/generators ^4.6.1 -> satisfiable by socialiteproviders/generators[v4.6.1].
    - socialiteproviders/generators v4.6.1 requires php ^5.6 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires socialiteproviders/instagram ^3.0 -> satisfiable by socialiteproviders/instagram[v3.0.0].
    - socialiteproviders/instagram v3.0.0 requires php ^5.6 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires socialiteproviders/linkedin ^3.1 -> satisfiable by socialiteproviders/linkedin[v3.1].
    - socialiteproviders/linkedin v3.1 requires php ^5.6 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
  Problem 4
    - jeremykenedy/laravel-roles[v3.5.0, ..., v3.8.0] require php ^7.2 -> your php version (8.0.5) does not satisfy that requirement.
    - Root composer.json requires jeremykenedy/laravel-roles ^3.5 -> satisfiable by jeremykenedy/laravel-roles[v3.5.0, v3.6.0, v3.7.0, v3.8.0].

**Comment by jeremykenedy** [comment]
Just use --ignore-platform-reqs flag
