### ISSUE TITLE
Target class [jeremykenedy\LaravelRoles\Middleware\VerifyRole] does not exist.

### ISSUE THREAD

**Issue by rxng** [jeremykenedy/laravel-auth#391]
**Describe the bug**
After installing Laravel Sanctum, trying to access roles leads to this error

Illuminate\Contracts\Container\BindingResolutionException
Target class [jeremykenedy\LaravelRoles\Middleware\VerifyRole] does not exist.

**Screenshots**
<img width="1236" alt="Copied Image" src="https://user-images.githubusercontent.com/19649766/118084793-a2417600-b404-11eb-86e9-da391d7d1b15.png">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Safari
 - Version 13.0.5

**Additional context**
All instructions followed properly and laravelroles installed + published

**Comment by rxng** [comment]
@jeremykenedy why close? I have confirmed that roles stops working the moment laravel sanctum is installed. Isn’t this an issue?

**Comment by justinriddiough** [comment]
@rxng did you figure it out? I'm seeing the same thing

**Comment by rxng** [comment]
@justinriddiough i suggest not using the repo. It was an issue and the dev didn’t want to handle it so closed without any comments. I ended up using something else as the number of customisations in this would have caused issues in the long term

**Comment by jeremykenedy** [comment]
@rxng I'd suggest you choose another career path that doesn't involve solving problems and following instructions. Just because you cannot use something correctly doesn't mean it's other people's responsibility to solve things for you. Get a life.
