### ISSUE TITLE
Bug in "Remember me" functionality

### ISSUE THREAD

**Issue by cvlug** [jeremykenedy/laravel-auth#394]
**Did you star the repo?**
 No

**Describe the bug**
"Remember me" in clean install of laravel-auth does not work as expected. User is logged out, and when on login page, checkbox "remember me" is not checked, and both username and password fields are empty

**To Reproduce**
1. check "remember me" checkbox, and  enter username and password, and click login button
2. Logout
3. go to login page
4. See that username and password field are empty, and Remember me" checkbox is not checked

**Expected behavior**
Checkbox "remember me" is checked, and username field is not empty

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Browser chrome, 

**Smartphone (please complete the following information):**
 - Version 90.0.4430.212

**Additional context**
In user table, remember_token field has a value.
Occurs on both dev server and production server

**Comment by jeremykenedy** [comment]
That's out the box behavior

**Comment by cvlug** [comment]
?
There must be an misunderstanding.
The remember me" functionality does nothing, it is not there.
The Read me of Laravel-Auth says: "User Login with remember password".
The password, username, and checkbox are not remembered. 
If one sees  "User Login with remember password" in a Read me,  you expect at least the username is remembered.
Wheater it is a out of the box bug. or something else, a clue for a solution would be highly appreciated.

**Comment by jeremykenedy** [comment]
https://laravel.com/docs/master/authentication#remembering-users

**Comment by cvlug** [comment]
The information on https://laravel.com/docs/master/authentication#remembering-users refers to the attempt() function.
The is no  function attempt() in the php of Laravel-auth.
