### ISSUE TITLE
Serverless deployment Throws error on login/register

### ISSUE THREAD

**Issue by d3vilsn0w** [jeremykenedy/laravel-auth#395]
Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Http\Middleware\Authenticate::handle($request, Closure $next) must be compatible with Illuminate\Auth\Middleware\Authenticate::handle($request, Closure $next, ...$guards)

I am deploying one of my application based on Laravel, to Serverless and this error occured. Any idea?

**Comment by d3vilsn0w** [comment]
Fixed it by adding ...$auth to the handle function, please correct me if it is not a good approeach. 

Thank you! :) I will close it for now.

**Comment by jayomayan** [comment]
@d3vilsn0w  How and where did you add the $auth ? Mind providing the sample code?

**Comment by d3vilsn0w** [comment]
> @d3vilsn0w How and where did you add the $auth ? Mind providing the sample code?

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Middleware/Authenticate.php#L55

Replace 
`public function handle($request, Closure $next)`

With 
`public function handle($request, Closure $next, ...$auth)`
