### ISSUE TITLE
.hidepassword not a function

### ISSUE THREAD

**Issue by adityaps13** [jeremykenedy/laravel-auth#396]
**Did you star the repo?**
Yes

**Describe the bug**
I have been able to successfully integrate this project to my existing project. This is an awesome one saving hours of work. Everything works fine except for when editing user profile to update password or say last name, I get confirmation box and then nothing happens when clicking on submit. There is no console information too. Only thing I see is .hidepassword is not a function. I tried to include jquery cdn link but still it throws the same error. I manually installed passwordstrength meter and hideshow password package via npm after which error starting showing on selectpicker. Even after resolving this I am unable to call the submit button function routine. Your help would be greatly appreciated. I know I must be missing something.
**To Reproduce**
1. Go to edit profile -> click account setting
2. Edit any field like last name
3. Click Save Changes -> Click Confirm Submit
4. Nothing happens. It does not save change. and console error Uncaught TypeError: $(...).hidePassword is not a function

**Expected behavior**
Expected to update the user profile. 

**Screenshots**
NA
**Desktop (please complete the following information):**
Error on all OS

**Additional context**
I tried to integrate with existing app. Apologies if this is not supported but worth a shot.

**Comment by gcdeadee** [comment]
HI. I have the same issue. I need help ^^'

**Comment by adityaps13** [comment]
I am still waiting forr Jeremy to respond to me

**Comment by goodmuyis** [comment]
Have you tried to `npm run dev` again

can you send the screenshot where you are seeing `Uncaught TypeError: $(...).hidePassword` ?

**Comment by adityaps13** [comment]
Tried running npm run dev again and its the same issue.  This seems to be common issue with everyone.  

![image](https://user-images.githubusercontent.com/81495327/132257483-96a37905-bb56-40cd-b5cd-b4dd0ebbf0a7.png)

![image](https://user-images.githubusercontent.com/81495327/132257532-aa6efae3-d87c-4242-84ff-0183aba0c42d.png)

**Comment by goodmuyis** [comment]
> Tried running npm run dev again and its the same issue. This seems to be common issue with everyone.

 I just tried it again on one of my old local clones, I cannot see any problem. Password was saved successfully

The console error you are seeing does it appear before you **Click Save Changes -> Click Confirm Submit** or after? If that error appears before you click, that  I will assume it is a JQuery issue. 

You can try switch to **Account Administration Tab** and toggle the password reveal eye to see if it works, if it doesn't work then you might like be having issue with jquery.

You try to comment-out line [467 of edit.blade.php](https://github.com/jeremykenedy/laravel-auth/blob/e9fb8667291c2ca1983718263aca1e6c00ac3640/resources/views/profiles/edit.blade.php#L467) to see if that allows you to save the profile changes. You can find it in `../resources/views/profiles/edit.blade.php`

If you are using any custom JQuery code, try to check if you are not having any issues with it.

using `php artisan --version` below is my laravel version
Laravel Framework 8.11.2

**Comment by jeremykenedy** [comment]
I agree its a jquery conflict error on build. You may have to expore your build and render order off app.js and the inline blade script includes.

It's a combination of the config settings and query within your app.js if its built using npm.
