### ISSUE TITLE
401 unauthenticated using Laravel Passport

### ISSUE THREAD

**Issue by adityaps13** [jeremykenedy/laravel-auth#399]
**Did you star the repo?**
Yes

**Describe the bug**
I followed all the instructions by Jeremy to install Laravel Passport for api authentication from previous repo shared by him. I am able to generate login token and get through Token Bearer. However when trying to access /user api route it throws 401 error. I do understand that /user api call does not do authentication but instead check for activation. Is there a simple Laravel Passport example that we can refer to for API authentication??

![image](https://user-images.githubusercontent.com/81495327/132257780-cecefa65-d891-4628-b919-7fa0695d4b84.png)

**Comment by jeremykenedy** [comment]
Just off the top of my head I think the handler probably needs a conditional for expectsJSON.

**Comment by cybersecthreat** [comment]
May I know where is "previous repo shared" ? Thanks.
