### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by pruthvireddyp51** [jeremykenedy/laravel-auth#4]
http://localhost/sociallite.dev/public/auth/login
throwing 404 error page in starting page or index page,
after i am not able to redirect when i pressed login button => http://localhost/auth/auth/login
Not Found
The requested URL /auth/auth/login was not found on this server.
Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

if i pressed home button => redirected to wamp server page

**Comment by jeremykenedy** [comment]
1. Your path is wrong and should not be auth/auth.
2. It may also be an issue with your WAMP environment.
