### ISSUE TITLE
Not routing correctly on an Ubuntu Server

### ISSUE THREAD

**Issue by Creekmore108** [jeremykenedy/laravel-auth#40]
I cloned the project to my mac and everything works great but when I migrated to a Ubuntu server and click on Login or Register it is not routing to the Login view or Register view. Any idea what the issue is?

**Comment by jeremykenedy** [comment]
It is most likely the configuration of your environment. Is your virtualhost setup?

**Comment by Creekmore108** [comment]
I'm just using the IP address for now. I haven't touched the virtual host settings yet.  It's on Digital Ocean so I have full access to do what I want.

**Comment by jeremykenedy** [comment]
See this article here on the nginx config:

https://laravel.io/forum/05-08-2014-nginx-laravel-routing-shows-404

I believe your answer lies in the area of 
`try_files $uri $uri/ /index.php$is_args$args;`

I have seen this issue on a misconfigured nginx setup which is a server issue.
