### ISSUE TITLE
composer update failed after fresh clonned + edited .env (php 8.0 @ dockered webdevops/php-apache-dev)

### ISSUE THREAD

**Issue by triblax** [jeremykenedy/laravel-auth#401]
**Describe the bug**
bash-5.1# composer update
Xdebug: [Config] The setting 'xdebug.profiler_output_dir' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_output_dir (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_connect_back' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_connect_back (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires socialiteproviders/instagram ^3.0 -> satisfiable by socialiteproviders/instagram[v3.0.0].
    - socialiteproviders/instagram v3.0.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires socialiteproviders/linkedin ^3.1 -> satisfiable by socialiteproviders/linkedin[v3.1].
    - socialiteproviders/linkedin v3.1 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 3
    - jeremykenedy/laravel-roles[v3.5.0, ..., v3.8.0] require php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
    - Root composer.json requires jeremykenedy/laravel-roles ^3.5 -> satisfiable by jeremykenedy/laravel-roles[v3.5.0, v3.6.0, v3.7.0, v3.8.0].

**Comment by jeremykenedy** [comment]
Just do

composer install --ignore-platform-reqs
