### ISSUE TITLE
Class 'App\Uuid' not found

### ISSUE THREAD

**Issue by mnszaidi** [jeremykenedy/laravel-auth#402]
Facing the Same Issue, Even Updated Composer , Upgrade & downgraded versions too

**Comment by jeremykenedy** [comment]
More info is needed.

**Comment by mnszaidi** [comment]
class User extends Authenticatable implements MustVerifyEmail, CanResetPassword
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uuid',
        'fname',
        'mname',
        'lname',
        'username',
        'email', 
        'password',
    ];

    /*
     *
     *  Setup model event hooks
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->uuid = (string) Uuid::generate(3);
        });
    }

    /*
     *
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

**Comment by jeremykenedy** [comment]
In the User model add 

`use UUID;`

after the namespace declaration

**Comment by mnszaidi** [comment]
Thank you So Much it is use  Uuid; instead of UUID
