### ISSUE TITLE
Installation instructions are wrong

### ISSUE THREAD

**Issue by mauro-balades** [jeremykenedy/laravel-auth#415]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes

**Describe the bug**
Installation instructions are wrong. You will need to do `composer install` first then everything because commands require `vendor/autoload.php`

**To Reproduce**
Follow installation instructions

**Expected behavior**
An error saying "expected verndor/autoload.php file not found"

**Screenshots**
![Frame 1(1)](https://user-images.githubusercontent.com/91018726/150670588-650a21ad-fcd9-4183-9fc3-add72e96d4fe.png)

**Additional context**
Didn't put device info since it is not relevant.

**Comment by jeremykenedy** [comment]
Check step 5
