### ISSUE TITLE
Send verification code / link for email address change

### ISSUE THREAD

**Issue by justinriddiough** [jeremykenedy/laravel-auth#419]
**Did you star the repo?**
Yes

**Is your feature request related to a problem? Please describe.**
When a user registers, the email is verified through the process of verification. However, if changing the email, it accepts new input.

**Describe the solution you'd like**
An option in the config, to send code when updating email address

**Comment by jeremykenedy** [comment]
If you make a feature to handle this I will gladly accept the PR. Thank you.
