### ISSUE TITLE
Cant get passed 1st Step - Composer Install (PHP v to Dependency Clash)

### ISSUE THREAD

**Issue by AiFxApp** [jeremykenedy/laravel-auth#422]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

# DONE

**Did you star the repo?**
Yes or No

# NO - Cant view the build yet

**Describe the bug**

`composer install`
```
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jeremykenedy/laravel-roles ^3.5 -> satisfiable by jeremykenedy/laravel-roles[v3.5.0, v3.6.0, v3.7.0, v3.8.0].
    - jeremykenedy/laravel-roles[v3.5.0, ..., v3.8.0] require php ^7.2 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires socialiteproviders/instagram ^3.0 -> satisfiable by socialiteproviders/instagram[v3.0.0].
    - socialiteproviders/instagram v3.0.0 requires php ^5.6 || ^7.0 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires socialiteproviders/linkedin ^3.1 -> satisfiable by socialiteproviders/linkedin[v3.1].
    - socialiteproviders/linkedin v3.1 requires php ^5.6 || ^7.0 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 4
    - socialiteproviders/37signals[v3.0.0, ..., v3.1.0] require php ^5.6 || ^7.0 -> your php version (8.0.17) does not satisfy that requirement.
    - Root composer.json requires socialiteproviders/37signals ^3.0 -> satisfiable by socialiteproviders/37signals[v3.0.0, v3.1.0].
```

**To Reproduce**

1. Download Repo,
2. Run `composer install` 

Thats it..

**Expected behavior**

Was expecting php version and dependencies to be in order? 

**Screenshots**
 N.A

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: N.A
 - Version : N.A

**Comment by PauloBoaventura** [comment]
Several dependencies are out of date in their versions.


 Many of them are obsolete and without any replacement.  Express this clearly for a takedown.


 Even manually updating dependency versions always gives error.


 Unable to continue from composer update part.


 I don't understand how there are new update versions but compuser is deprecated.


 It is impossible to carry out the installation of the project

**Comment by jeremykenedy** [comment]
Use this branch for now:
https://github.com/jeremykenedy/laravel-auth/tree/laravel-10
