### ISSUE TITLE
Unable to install = Composer without dependencies update 

### ISSUE THREAD

**Issue by PauloBoaventura** [jeremykenedy/laravel-auth#428]
**Describe the bug**
Several dependencies are out of date in their versions.

 Many of them are obsolete and without any replacement.  Express this clearly for a takedown.
Some dependencies require php 5.6

 Even manually updating dependency versions always gives error.

 Unable to continue from composer update part.
 I don't understand how there are new update versions but compuser is deprecated.
 It is impossible to carry out the installation of the project
 
 And although the case was opened, no explanation or update information was given.
 https://github.com/jeremykenedy/laravel-auth/issues/422

**Comment by jeremykenedy** [comment]
I can get it working on php 8. What does clearly for a takedown mean? 

Just run composers with --ignore-platform-reqs flag.

**Comment by jeremykenedy** [comment]
I stood go up last month on Laravel-auth.com and consultjeremy.com

**Comment by jeremykenedy** [comment]
I haven't made any recent updates and this still is on Laravel 9

**Comment by jeremykenedy** [comment]
Try this branch for now:

https://github.com/jeremykenedy/laravel-auth/tree/laravel-10

**Comment by jeremykenedy** [comment]
This is now on master and the project stand up as described in the readme. A major overhaul on the backend was done to put Laravel 10 in place. Rather than follow the upgrade guide every single file was gone through to match Laravel 10.
