### ISSUE TITLE
CSS and font not linked properly

### ISSUE THREAD

**Issue by ajibari** [jeremykenedy/laravel-auth#43]
When i go to login and register page, the layout is messy. 
Then i change in `app.blade.php line 26` to 
`<link href="{{ url('/') . mix('/css/app.css') }}" rel="stylesheet">`
but font-awesome still don't show up in the button.

**Comment by jeremykenedy** [comment]
pull and compile the assets with `npm`.

**Comment by ajibari** [comment]
i did `npm install` and `npm run production`.
when i check the generated css in public/css, i see : 
`@font-face{font-family:FontAwesome;src:url(fonts/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713);`

it should be 
`@font-face{font-family:FontAwesome;src:url(../fonts/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713);`

it happened to glyphicons too.

**Comment by jeremykenedy** [comment]
Cannot duplicate.
