### ISSUE TITLE
versions are out of controll

### ISSUE THREAD

**Issue by timlaaan** [jeremykenedy/laravel-auth#442]
Hey, what's the matter with all the versions. 

Nothing is compatible, no documentation about dependences, i downgrade and update every third packages or pluging and just get a mess of errors.

npm WARN EBADENGINE   package: 'lru-cache@9.0.3',
npm WARN EBADENGINE   required: { node: '14 || >=16.14' },
npm WARN EBADENGINE   current: { node: 'v16.0.0', npm: '7.10.0' }

when having the correct node.js and npm version, vite are vite-legacy.pluging are the wrong versions, if vite is the right version, node.js and npm is wrong again.

Can´t delete this issue, right ? or am i just stupid.

_____________________________________________________________________________

i fixed it now, took me as beginner, with installing linux and so on 1 and a half day now to see the actually running laravel auth page.
_____________________________________________________________________________
As a beginner, i am facing often the same issues, the versions, if you would put more infos in readme about versions and dependences it would be nice. 

Further, the php.ini changes with all the added extensions and their routes  were difficult too and not documentated here, but maybe it is just a problem from my point of view, from a beginner ^^ 

kind regards

**Comment by jeremykenedy** [comment]
All problems with your environment that are on you.
