### ISSUE TITLE
edit user confirm modal dialog get 'data is undefined'

### ISSUE THREAD

**Issue by inforisorse** [jeremykenedy/laravel-auth#446]
**Describe the bug**

When trying to save user at /users/&lt;id&gt;/edit, the modal confirm dialog get an 'data is undefined' error on  $(this).**data**('form').submit();

**To Reproduce**
1) go to /users
2) click on the 'edit' button on a user row
3) modify some data
4) click on save

**Expected behavior**
Saving of the updated data

**Actual behavior**
The modal confirm dialog does not close and the console shows the 'data is undefined' error

**Desktop:**

-   OS: Xububto 22.10]
-   Browser firefox
-   Version 112.0.1

**Suggestion**
Just wrap then events statements of scripts/save-modal-script.blade.php into an $(document).ready(function() {...} as in delete-modal-script.blade.php

**Comment by inforisorse** [comment]
reverted and got screenshot

![issue-446](https://user-images.githubusercontent.com/11506325/234903555-271e1188-3268-4a84-bdd3-e9e2e3dce937.png)

The only difference with default environment is the use of Soketi as pusher service. The fault is due to the  <code>$('#confirmSave').on('show.bs.modal', function (e) {...}</code>  that is not executed unless wrapped in a  $(document).ready() function.

To fix i changed the code in:

<code>

<script type="text/javascript">
    // CONFIRMATION SAVE MODEL
    $(document).ready(function() {     // <== ensure event is registered
        $('#confirmSave').on('show.bs.modal', function (e) {
            var message = $(e.relatedTarget).attr('data-message');
            var title = $(e.relatedTarget).attr('data-title');
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-body p').text(message);
            $(this).find('.modal-title').text(title);
            $(this).find('.modal-footer #confirm').data('form', form);
        });
        $('\#confirmSave').find('.modal-footer #confirm').on('click', function(){
            $(this).data('form').submit();
        });
    });
</script>

</code>

**Comment by jeremykenedy** [comment]
If you make a PR I will honor it. Thank you 😊

**Comment by inforisorse** [comment]
I'm trying to understand how to fork the project and submit PR... I hope i will be able to submit it soon since there are some other issues i'm interested to investigate and some minor improvements i may propose.

**Comment by Jonnyenglish89** [comment]
Thank you for sharing this fix. I noticed the same issue in the form-modal-script.blade.php file.
Here's the corrected code:

`<script type="text/javascript">
    $(document).ready(function() {
        $('#confirmForm').on('show.bs.modal', function (e) {
            var modalClass = $(e.relatedTarget).attr('data-modalClass') || '';
            var submitText = $(e.relatedTarget).attr('data-submit');
            var message = $(e.relatedTarget).attr('data-message');
            var title = $(e.relatedTarget).attr('data-title');
            var form = $(e.relatedTarget).closest('form');
            var self = $(this);

            self.alterClass('modal-*', modalClass);
            self.find('.modal-body p').text(message);
            self.find('.modal-title').text(title);

            self.find('.modal-footer #confirm')
                .text(submitText)
                .data('form', form);
        });
        $('#confirmForm').find('.modal-footer #confirm').on('click', function(){
            $(this).data('form').submit();
        });
    });
</script>
`

Please review and apply this change to the repository if possible.
Cheers

**Comment by MaceEnterprises** [comment]
Confirm Save, Confirm Delete - all of the models do not work. Can't save anything
