### ISSUE TITLE
wrong path "jeremykenedy\\LaravelRoles\\": "packages/jeremykenedy/laravel-rosles/src/" in composer.json

### ISSUE THREAD

**Issue by inforisorse** [jeremykenedy/laravel-auth#449]
**Describe the bug**
The path specified in the autoload-dev section of composer.json is wrong because of a typo.

![bug-laravel-auth-composer](https://github.com/jeremykenedy/laravel-auth/assets/11506325/7c376503-99fd-4ab5-8270-8d573f1007ef)

Pull request is on the way

**Comment by jeremykenedy** [comment]
Thank you 😊 the PR fixed it :)
