### ISSUE TITLE
How to run without artisan.

### ISSUE THREAD

**Issue by Monilal** [jeremykenedy/laravel-auth#45]
Hi,

I want to run without **php artisan serve** laravel and webpack mix, how to do that.

**Comment by jeremykenedy** [comment]
Hello,
I do not use `php artisan serve` to run it. You need to setup an environment. Check out the Laravel documentation on Homestead for development and or production you may need to read up on Nginx configuration. https://laravel.com/docs/5.4/homestead

**Comment by jeremykenedy** [comment]
You can also try Laravel Valet ..... https://laravel.com/docs/5.4/valet

**Comment by Monilal** [comment]
Thanks, actually I'm trying to deploy my hosting server, but css, js not working.

**Comment by jeremykenedy** [comment]
The assets need to be compiled then you push the code to the server.

**Comment by jeremykenedy** [comment]
You can also call the assets directly once compiled.
