### ISSUE TITLE
Token mismatch on registration as well as login

### ISSUE THREAD

**Issue by CharlesKumar** [jeremykenedy/laravel-auth#46]
I installed laravel-auth, migrated and seeded (using laravel  5.4.27 and mysql  Ver 14.14 Distrib 5.6.21, for Win32 (x86))

when i tried to login, at first login looped back

then i created google+ sign in application and got credentials, changed my session_domain to http://localhost

next i tried to register via google+ but there arrived token mismatch error 
after that token mismatch error occurred on registration as well as login

I tried deleting cookies, cleared cache but couldn't make it work 

` <div class="panel-body">

                    {!! Form::open(['route' => 'register', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'POST'] ) !!}

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">`

I var_dumped in middlewares and pipeline files but couldn't make it work....

Thank you in advance!!

[localhost_8000_register.pdf](https://github.com/jeremykenedy/laravel-auth/files/1130065/localhost_8000_register.pdf)

**Comment by jeremykenedy** [comment]
Try running 
```
sudo rm -rf storage/framework/sessions/*
sudo php artisan cache:clear
```

**Comment by CharlesKumar** [comment]
i am using windows and i ran gitbash with administrator privilege

php artisan cache:clear && php artisan clear-compiled && composer dump-autoload

tried in two different browsers, still getting the same error

![err](https://user-images.githubusercontent.com/14817903/27958167-6673fb08-633f-11e7-8925-1eb7f8fa6835.png)

do debugbar errors has anything do with token mismatch

should i try a fresh installation and try again

**Comment by jeremykenedy** [comment]
I do not think a fresh install is the elegant solution and still may not work but its worth a go.

This is a known random environment issue with Laravel development that there is a lot of chatter out there about. Checkout out these threads:

https://github.com/laravel/framework/issues/15040

https://github.com/laravel/framework/issues/16064

https://laracasts.com/discuss/channels/laravel/laravel-54-tokenmismatchexception-in-verifycsrftokenphp-line-68-on-some-device?page=1

https://laravel.io/forum/01-30-2015-laravel5-tokenmismatchexception-in-verifycsrftoken

I feel it is something related to the SESSION...

**Comment by jeremykenedy** [comment]
Since it is environment related and you are going to need to debug your specific environment I am going to close the issue. Let me know if you still cannot figure it out.

Thanks!

**Comment by CharlesKumar** [comment]
I just switched to homestead, migrated and seeded

but getting same token mismatch error, creating a new file on storage/framework/sessions/  on every http request

my http cookie (authstrap_session) is mismatched with cookie xsrf token

next problem is config/session.php has no effect in server configuration, i had to ini_set every property on bootstrap/autoload.php

this doesn't seem an environment error, may be a config error ( i tried all config:clear clear-compiled)
![rtt](https://user-images.githubusercontent.com/14817903/28240261-e74f8d3e-699b-11e7-8313-1fd56eff3a49.png)
![erdr](https://user-images.githubusercontent.com/14817903/28240263-f211386c-699b-11e7-9baa-1e56df65d735.png)

**Comment by jeremykenedy** [comment]
This is a common environment issue with the storage directory not being writable or there is an ownership issue of the files between the host and the vm.

There are a couple of things to try:
`chmod 777 storage/framework/sessions/`
'rm -rf storage/framework/sessions/*'
'php artisan cache:clear' <- This may need to be ran within the virtual machine from the projects root directory.
`composer dump-autoload`

You can also bypass the write issues by changing the SESSION driver in the `.env` file:

`SESSION_DRIVER= cookie` or 
`SESSION_DRIVER= memcached` or
`SESSION_DRIVER= database`

https://laravel.com/docs/5.4/session

**Comment by CharlesKumar** [comment]
Thanks! it worked

but first cookie is saved as XSRF and first attempt results in token mismatch, from then it saved as authstrap_cookie (as is set in config/session.php) - or something i misunderstanding here as xsrf token is the main cause of this problem

it works fine with file and cookie session drivers but not working in array session driver (maybe something i'm missing)

**Comment by jeremykenedy** [comment]
It is an environment issue. This is a very well known issue people have with homestead that is a pain for many people.

**Comment by jeremykenedy** [comment]
Try SSHing into the Homestead machine and then cd to your projects folder then run the following:
```
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
sudo chmod -R 777 storage bootstrap/cache
```

**Comment by CharlesKumar** [comment]
I understand lot of laravel and platform of laravel (env) here. Your answers are very helpful and quick. Thank You jeremy
