### ISSUE TITLE
how to get diferents rows providers in  social_logins tables?

### ISSUE THREAD

**Issue by kossak31** [jeremykenedy/laravel-auth#5]
hey your code is very clean and good. some how i am newbie and i can't get the logic to get diferents providers to social_id and avatar rows in social_login. can you give the logic? just the concept

i has very near but the code was continued add new rows dont know how to check
[(http://pastebin.com/rPYtdgLd)]
thanks!

**Comment by kossak31** [comment]
not the best code but it works!

must create new row USERNAME in table SOCIAL_LOGINS.

just copy paste the  public function getSocialHandle($provider) in controller/auth/AuthController.php

[http://pastebin.com/CMhiqrcU]

**Comment by jeremykenedy** [comment]
Cool, you can create a seed that will add for you to make it part of your deployment process. Let me know if you need help.  Thanks.

**Comment by kossak31** [comment]
i only know the command "php artisan db:seed" for seed. i make a insert in sql with array but i didnt make very well

keep the good work i just learn a lot from your code thanks!

**Comment by jeremykenedy** [comment]
Thank you. I just realized that it's not a seed you would create but a migration to update the table. It is easy to do in command line, Here is the doc on how to: https://laravel.com/docs/5.1/migrations , about half way through there is a section on creating columns to existing tables via migration. It's pretty handy. Thank you again.
