### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by vuongdinhngoc** [jeremykenedy/laravel-auth#52]
Hi @jeremykenedy 
Any plan to update to Bootstrap 4?

**Comment by jeremykenedy** [comment]
If it ever gets out of alpha and once Laravel includes it in its preset. In Laravel 5.5 there is some more presets available but I do not think Bootstrap v4 is one of them.

I would imagine it wouldn't be very hard to switch out the bootstrap version on this for your project.

Thanks for checking the project out! :)
