### ISSUE TITLE
Does not show new user rights

### ISSUE THREAD

**Issue by SerhiiZahuba** [jeremykenedy/laravel-auth#559]
1) I create a new user
2) Log in to the system as a new user
3) The You have Access field should show user rights, but it is empty.
4) if you log in as a user created by the system during seeds, everything is fine, but with new roles - a problem.

![image](https://github.com/user-attachments/assets/79480c83-3379-4949-9ebd-b6c19e047694)
![image](https://github.com/user-attachments/assets/8a3f1e5a-ded3-4697-9825-fa48079687ca)

**Comment by jeremykenedy** [comment]
Did you assign a role?

**Comment by SerhiiZahuba** [comment]
![image](https://github.com/user-attachments/assets/c1934889-725e-4df9-b2f3-d56fbe75e6da)


yes

**Comment by jeremykenedy** [comment]
Take a look at the blade file and adjust as needed or loop for your project. 

https://github.com/jeremykenedy/laravel-auth/blob/master/resources/views/panels/welcome-panel.blade.php

**Comment by jeremykenedy** [comment]
You have declare the middleware.
