### ISSUE TITLE
 Method [throwValidationException] does not exist.

### ISSUE THREAD

**Issue by mdrashedulislam11** [jeremykenedy/laravel-auth#57]
great project we have some issue. 

/var/www/mydomain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php
"Method [throwValidationException] does not exist."

**Comment by jeremykenedy** [comment]
thats a real issue with L5.5.2+, I need to update the project.
thanks

**Comment by jeremykenedy** [comment]
This has been updated in commit https://github.com/jeremykenedy/laravel-auth/commit/5bfbed001e1a1dc2da67327a1697de292364ae6b.  Thank you again for letting me know.
