### ISSUE TITLE
Class 'Webpatser\Uuid\Uuid' not found

### ISSUE THREAD

**Issue by COTIGA** [jeremykenedy/laravel-auth#63]
Hi,
Whoops! There was an error when delete an user
/profile/***/deleteUserAccount

```
Class 'Webpatser\Uuid\Uuid' not found

app/Http/Controllers/ProfilesController.php350

$level2 = urlencode(Uuid::generate(4).$sepKey.$level1);
```

Should I install webpatser manually ?
Tks

**Comment by COTIGA** [comment]
It's OK after:
`
composer require "webpatser/laravel-uuid:^3.0"
`

**Comment by jeremykenedy** [comment]
No need to to do that, just do a composer update on this package. 
I have updated the profile controller. 
thanks for letting me know.
