### ISSUE TITLE
Connection could not be established with host smtp.mailtrap.io [Connection refused #111]

### ISSUE THREAD

**Issue by mdrashedulislam11** [jeremykenedy/laravel-auth#64]
Email activation issue. 

`      

 
        if (isset($this->params['stream_context_options'])) {
            $options = array_merge($options, $this->params['stream_context_options']);
        }
        $streamContext = stream_context_create($options);
        $this->stream = @stream_socket_client($host.':'.$this->params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
        if (false === $this->stream) {
            throw new Swift_TransportException(
                'Connection could not be established with host '.$this->params['host'].
                ' ['.$errstr.' #'.$errno.']'
                );
        }
        if (!empty($this->params['blocking'])) {
            stream_set_blocking($this->stream, 1);
        } else {
            stream_set_blocking($this->stream, 0);
        }
        stream_set_timeout($this->stream, $timeout);
        $this->in = &$this->stream;
        $this->out = &$this->stream;
    }
`

**Comment by jeremykenedy** [comment]
check your `.env` and your servers email configuration.

**Comment by mdrashedulislam11** [comment]
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=81UserIDd47b***
MAIL_PASSWORD=36ba146c85*****
MAIL_ENCRYPTION=null

MAIL_FROM_ADDRESS=support@mydomain.com
MAIL_FROM_NAME='My Domain'

**Comment by mdrashedulislam11** [comment]
I have did.

**Comment by jeremykenedy** [comment]
I am sure these are incorrect:
```
MAIL_PORT=2525
MAIL_ENCRYPTION=null
```

**Comment by mdrashedulislam11** [comment]
which mail need to ENCRYPTION?

**Comment by jeremykenedy** [comment]
try

```
MAIL_PORT=465
MAIL_ENCRYPTION=tls
```

**Comment by mdrashedulislam11** [comment]
Hi, 
Sorry I have configuration same as 
`MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=465
MAIL_USERNAME=81e768d4******8
MAIL_PASSWORD=36ba146c****2b
MAIL_ENCRYPTION=tls`

Same issue

**Comment by jeremykenedy** [comment]
Its something with your environment and the email setup. Its going to need to be debugged as to what the email setting should be and then if they emails are even getting out from your server/localhost.

**Comment by mdrashedulislam11** [comment]
I have on my live server. when I have configured using my own SMTP. it's say time out 
http://prntscr.com/gjzurl

**Comment by Tobaino1** [comment]
though the issue looks stale but what worked for me was changing 
mail driver from smtp to sendmail
encryption from null to ssl
then i did a reset to get new credentials (username and password) in my mailtrap account 

MAIL_DRIVER=sendmail
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=465
MAIL_USERNAME=deebbe6d***594
MAIL_PASSWORD=65beafc98d****
MAIL_FROM_ADDRESS="ancho****ello****@gmail.com"
MAIL_FROM_NAME="Anchor Support"
MAIL_ENCRYPTION=ssl

**Comment by kennblvnp** [comment]
Where did you guys get the username and password?

**Comment by lucky4life** [comment]
> 
> 
> Where did you guys get the username and password?

create an account from http://mailtrap.io

**Comment by thedevsbuddy** [comment]
Set the port to 587 and it will work
.....
MAIL_PORT=587
.......
