### ISSUE TITLE
login and register not found

### ISSUE THREAD

**Issue by whyrukter** [jeremykenedy/laravel-auth#65]
Hi,
I'm newbie laravel and interesting laravel for user manage.

I can't access Login and Register menu when i click are show 404 Not Found

Then i check route on routes/wep.php but haven't /register or /login.

Please help.

Thank you.

**Comment by jeremykenedy** [comment]
Hello,

Thanks for checking out the project and your interest.

I would suggest checking your environment to make sure it is setup correctly then run down the basics of Laravel to get a handle on learning it. You should also check out laracasts

Below are some links to get you started.

https://laravel.com/docs/5.5/installation
https://laravel.com/docs/5.5/homestead
https://laravel.com/docs/5.5/authentication
https://laracasts.com/series/laravel-from-scratch-2017

Good luck and have fun!

**Comment by whyrukter** [comment]
Working running laravel  with  php artisan serve --host=<ipaddress> but if using apache doesn't work

Thank you.

**Comment by Shujee** [comment]
This is a problem with current Laravel as well. Login and Register pages do not work on Apache (XAMPP), but work perfectly fine with `php artisan serve`.
