### ISSUE TITLE
is it possible to disable other user data access

### ISSUE THREAD

**Issue by mdrashedulislam11** [jeremykenedy/laravel-auth#66]
I've successfully run this app. 

Now I just want to know ->

user A can't view user B information.

but admin can view all information and edit access.

**Comment by jeremykenedy** [comment]
Cool, yes, you can use blade `if()` statements to compare and show the user.

The if statement would contain something comparing the current logged in users id against the user id of the record they are viewing and if it matches render the content.

https://laravel.com/docs/5.5/blade

Another slightly more complex approach could be to setup a view composer do this as well.

https://laravel.com/docs/5.0/views#view-composers
