### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rashedul' for key 'users_name_unique' (SQL: update `users` set `name` = rashedul, `updated_at` = 2017-09-24 19:26:45 where `id` = 6)

### ISSUE THREAD

**Issue by mdrashedulislam11** [jeremykenedy/laravel-auth#68]
Hi, 
I got another issue which is when user update his username and email. 
maybe be you need to check updateUserAccount functions 

Thanks

**Comment by jeremykenedy** [comment]
That error is telling you that the validation rules in the controller may need to be updated.

**Comment by creativewebcode** [comment]
@mdrashedulislam11   inside of ProfilesController controller under validator make change 

`
'name'              => 'required|max:255,
`
To
`
'name'              => 'required|max:255|unique:users',`
`
 'email'             => 'required|email|max:255|unique:users',`

It look like: 

   ` public function validator(array $data)`
    `{`
     `   return Validator::make($data, [`
         `   'name'              => 'required|max:255|unique:users',`
          `  'email'             => 'required|email|max:255|unique:users',`
       ` ]);`
   ` }`


Thanks
