### ISSUE TITLE
Twitter Argument 1 passed to League error

### ISSUE THREAD

**Issue by imkevinabraham** [jeremykenedy/laravel-auth#7]
I completed all the steps for the install and added my twitter details to the .env but when I try and login using twitter I get an error that reads 

`FatalThrowableError in Server.php line 146:
Type error: Argument 1 passed to League\OAuth1\Client\Server\Server::getTokenCredentials() must be an instance of League\OAuth1\Client\Credentials\TemporaryCredentials, null given, called in $File_path_to_folder/vendor/laravel/socialite/src/One/AbstractProvider.php on line 87`

not sure whats going on because when I look at the URL it looks like twitter is sending auth tokens back.

**Comment by imkevinabraham** [comment]
Figured out what was wrong. When I was passing the values to twitter I was using a http://localhost url and my callback URL is 127.0.0.1 so it returned to a different address and returned null by initiating the request from 127.0.0.1 it worked without issue.

**Comment by jeremykenedy** [comment]
Cool, I am glad it all worked out, please reach out if you have any further issues.
