### ISSUE TITLE
Controller don't have permission but can access

### ISSUE THREAD

**Issue by hikaru2838** [jeremykenedy/laravel-auth#72]
Hi, i'm thank about your source. But i try to test it, i create controller with name TestController and have content in below. I add route but user user@user.com can view but it doesn't have permission

`Route::group(['middleware' => ['auth', 'activated']], function () {
Route::get('/test', [
        'as'        => 'test.index',
        'uses'      => 'TestController@index',
    ]);
}`

`<?php

namespace App\Http\Controllers;

use Auth;

class TestController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        echo 'fdfdf';
    }
}
`

**Comment by jeremykenedy** [comment]
Check out the seed and how it assigns permissions. You need to include the permissions class in the head and then assign permissions within the method.

**Comment by hikaru2838** [comment]
I'm very sorry but can you give me file controller demo? I'm newbie with Laravel framework, i had read some topic about authoriation and your source and your package(laravel-roles), but i can't find excatly what i need to do in code?
Example in my TestController, i add new rows 'test.index' to table 'permissions' and 'permissions_role' but where code will check it in controller?
