### ISSUE TITLE
How can check permission in controller

### ISSUE THREAD

**Issue by hikaru2838** [jeremykenedy/laravel-auth#74]
I'm very sorry but can you give me file controller demo? I'm newbie with Laravel framework, i had read some topic about authoriation and your source and your package(laravel-roles), but i can't find excatly what i need to do in code?
Example in my TestController, i add new rows 'test.index' to table 'permissions' and 'permissions_role' but how code will check it in controller?

**Comment by jeremykenedy** [comment]
What are you trying to do? What does your code look like?

**Comment by jeremykenedy** [comment]
Please see this: https://github.com/jeremykenedy/laravel-auth/issues/76#issuecomment-334997505

**Comment by jeremykenedy** [comment]
Please see: https://github.com/jeremykenedy/laravel-auth/issues/76#issuecomment-335002652
