### ISSUE TITLE
activation by email , query error

### ISSUE THREAD

**Issue by jihadismail8** [jeremykenedy/laravel-auth#75]
i am getting this error  when i press on activate account  in the email sended to me , ! 

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`admin_multiauth`.`profiles`, CONSTRAINT `profiles_theme_id_foreign` FOREIGN KEY (`theme_id`) REFERENCES `themes` (`id`)) (SQL: insert into `profiles` (`user_id`, `updated_at`, `created_at`) values (2, 2017-10-07 15:26:00, 2017-10-07 15:26:00))

**Comment by jeremykenedy** [comment]
I cannot duplicate.

**Comment by jihadismail8** [comment]
why this can happen ?   what is the error means ? and how i can debug it further ? and to fix it 
any help is appreciated
thanks

**Comment by jeremykenedy** [comment]
Did you run the migration and seeds?

What does your tables look like?

**Comment by jihadismail8** [comment]
thank you :) you found the problem :) i texted you on facebook , could you answer please if you do not mind  ?

**Comment by jeremykenedy** [comment]
It means that the value for column `theme_id` on table `profiles` you are inserting doesn't exist on table `themes` or you are not inserting value for `theme_id` on table `user`. Bear in mind that the values of column `theme_id` on table `profiles` is dependent on the values of ID on table themes.
