### ISSUE TITLE
Another Laravel version

### ISSUE THREAD

**Issue by andriaripratama** [jeremykenedy/laravel-auth#77]
Hi Jeremy,

Can I use this with Laravel 5.3/5.4? I already seen your another laraver-user but there's no role and permission management.

Thank you!

**Comment by jeremykenedy** [comment]
Hello, 

There are 5.2 and 5.4 stable branches but there is no stable 5.3 branch

https://github.com/jeremykenedy/laravel-auth/tree/fivepointtwo
https://github.com/jeremykenedy/laravel-auth/tree/fivepointfour

Thanks for checking it out.
