### ISSUE TITLE
Social Login, user doesn't allow email, can't continue.

### ISSUE THREAD

**Issue by noreason** [jeremykenedy/laravel-auth#82]
<p>Currently, if i try and log in or register via Facebook (only one i've tested so far) and decide not to share my email address with the site, Gravatar squawks at me instantly and I cannot view anything because the email address is an incorrect format for Gravatar.</p>
<pre><code>"Please specify a valid email address (View: /Users/noreason/code/laravel-auth/resources/views/profiles/show.blade.php)"</code></pre>
<p>in</p>
<pre><code>/Users/noreason/code/laravel-auth/vendor/creativeorange/gravatar/src/Gravatar.php</code></pre>
<p>The email address generated for this specific login was</p>
<pre><code>missingb2IlmgQkPW</code></pre>
<p>I can solve the issue with workarounds, but I was just wondering if I am missing something somewhere?</p>

**Comment by jeremykenedy** [comment]
I tried to replicate and am unable to.

**Comment by noreason** [comment]
Here is a fresh installation and example of what I am talking about.

![laravel-auth-error](https://user-images.githubusercontent.com/421209/32995422-60e695f6-cd39-11e7-80ed-9144627e3650.gif)

vendor/creativeorange/gravatar/src/Gravatar.php requires an email in the correct format of a@b.xyz, but if you don't allow sharing of your email address,  the database gets filled with (in this example) "missingF0jaBjnU3w" which throws the error.

**Comment by philip** [comment]
FWIW, I see the same issue after adding and using the Yahoo provider.

**Comment by ajitdas123** [comment]
Sometime it happens that facebook doesn't return email address of an user when user set it not to share i found out that when i was working on an android application. 
In this case you are optinng not to share so it is not returning the email address.

So what you do is change line number 50 in SocialLoginController 
where it says  `$email = 'missing'.str_random(10);` to something like this ` $email = 'missing@example.com');`
That will fix the issue .

**Comment by azjezz** [comment]
@ajitdas123 better $email = 'missing'.str_random(10).'@'.str_random(10).'example.org'; so there will be no 2 users using the same email.

**Comment by jeremykenedy** [comment]
This has been fixed in https://github.com/jeremykenedy/laravel-auth/commit/58f026bda592b7afb551d0b1236209015d20081b

Thank you
