### ISSUE TITLE
PHP Artisan Migrate issue

### ISSUE THREAD

**Issue by godbagas** [jeremykenedy/laravel-auth#83]
[Illuminate\Database\QueryException]                                                
  could not find driver (SQL: select * from information_schema.tables where table_sc  
  hema = laravelAuth and table_name = migrations)                                     
                                                                                      

                                       
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver                
                                       

                         
  [PDOException]         
  could not find driver

**Comment by jeremykenedy** [comment]
You need to configure your database in the .env file and make sure that you have access to your database and table.
