### ISSUE TITLE
Authenticating user on API middleware

### ISSUE THREAD

**Issue by novakben** [jeremykenedy/laravel-auth#90]
How can I authenticate the users with API routes under the api middleware?
Usually you add api_token row to DB, and send that with the requests. I see a token col in DB does this can be used the same?

**Comment by jeremykenedy** [comment]
Currently, it's not setup to do that at the moment. The token in the database can be doubled for that if you wanted to add in that functionality.

I do think that it would be cool to get API authentication going.

**Comment by novakben** [comment]
When does the token refresh? on every login (even social) or only on sign up?
