### ISSUE TITLE
PostgreSQL support?

### ISSUE THREAD

**Issue by amarsahinovic** [jeremykenedy/laravel-auth#92]
Hi,

I'm reviewing this package for a potential project which uses PostgreSQL database, but I see in the readme that MySQL support is explicitly mentioned. Is there something that prevents this project from being used with PostgreSQL?

**Comment by jeremykenedy** [comment]
You can use any database you want, you just need to select the correct driver and enter the credentials in the .env file.

**Comment by XanderLuciano** [comment]
May I suggest updating the README? As it reads can be misleading to new / unfamiliar users.

>Uses MySQL Database

IMO that implies that this only supports MySQL even though Laravel out of the box supports MySQL, PostgreSQL, SQLite, and SQL Server.
