### ISSUE TITLE
Social Login, error when 'Socialiting' with Twitter 

### ISSUE THREAD

**Issue by lexxyungcarter** [jeremykenedy/laravel-auth#93]
After a successful login/signup with Twitter, the application throws in a error claiming `username` property is not available in the `$socialUserObject` collection around line no. 101. Had to use `nickname` since it is present in the `$socialUserObject` object acquired from Twitter.
![image](https://user-images.githubusercontent.com/19994360/33777897-9ac8cfb4-dc57-11e7-90a8-fd2ad79bcdf5.png)

**Comment by jeremykenedy** [comment]
What does the `$socialUserObject` returned look like?

**Comment by lexxyungcarter** [comment]
![laravel socialite twitter oauth info object unsensitized](https://user-images.githubusercontent.com/19994360/33880210-fdc8a048-df41-11e7-90d0-88cad98886b9.jpg)

**Comment by jeremykenedy** [comment]
Hmmm, I see the nickname returned in you object. I do not see it attempting to call username in the method. What’s the error you are getting.

**Comment by jeremykenedy** [comment]
This has been fixed in commit https://github.com/jeremykenedy/laravel-auth/commit/1f5b3a4369f8daf1dadbca30e1e08b7aad0aac2e Thank you for reporting it!
