### ISSUE TITLE
API Token authentication not working

### ISSUE THREAD

**Issue by ajitdas123** [jeremykenedy/laravel-auth#95]
hi, Currently i encounter an issue that authentication with API Token is not working . Even after passing correct token value it throwing an 401 error.

`api.php` route file

```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

I am using insomnia as rest api client. 
Url hit : http://localhost:8000/api/user

parameter passed in the header : 
```
Content-Type: application/json
Accept: application/json
token: iN0JpGJAx7l2MmkVQCUdZhZTgv7WyzXkhcuG2b5AE4gVgz8CEm2839mnvRD9cvyZ
```
To test i also added  in the query ` token: iN0JpGJAx7l2MmkVQCUdZhZTgv7WyzXkhcuG2b5AE4gVgz8CEm2839mnvRD9cvyZ` but the result is same 401 error.

![token2](https://user-images.githubusercontent.com/20204881/33818205-937b740a-de69-11e7-9521-6191d77222fd.png)

![token1](https://user-images.githubusercontent.com/20204881/33818233-c691af76-de69-11e7-96b8-40aa8f9eb781.png)

**Comment by jeremykenedy** [comment]
Its the same as issue https://github.com/jeremykenedy/laravel-auth/issues/94 you opened. That token is not designed for that purpose. 

You are going to need to make some changes to make it work or the quickest way is to use Laravel Passport.

The token you are using is for 2 step email authentication, its not an API token.

**Comment by jeremykenedy** [comment]
Here is a look at what that token does: https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L132

**Comment by jeremykenedy** [comment]
Since your not authing on HTML and making API requests that token just isn't go to do what your trying make it do. 

You can still use this project and just install laravel passport to use for the API calls.  

Examples:
https://laravel.com/docs/5.5/passport
https://scotch.io/@neo/getting-started-with-laravel-passport
https://mattstauffer.com/blog/introducing-laravel-passport/

Build of the examples above:
https://github.com/jeremykenedy/laravel-passport
https://github.com/jeremykenedy/laravel-consumer

**Comment by ajitdas123** [comment]
Yes thank you jeremykenedy.
I found a way to work around this without using passport :D.
But i am not sure if that right to do. 

For those who want to  use api token for api authentication , you will have to make some little changes here and there.
1. add it in user migration file 
 `  $table->string('api_token',60)->unique();`
2.Reset your migration table `php artisan migration:reset` This will wipe out all data. Then install migration table` php artisan migrate`
3. change in `user `model in the `fillable`  add` 'api_token',
4.In the controller `RegisterController`  inside auth add `'api_token'  => str_random(60),`  in the `create` method 
5.In the controller `SocialController`  inside auth add `'api_token'  => str_random(60),`   where its creating an user . I think its line number 75.

That's all . and you are set to go.

**Comment by jeremykenedy** [comment]
Very Cool! Very Cool!

**Comment by mateo2181** [comment]
I'm trying to get current user from a Vue component, but get `` {error: "Unauthenticated."} ``.

api.php
```

  Route::group(['namespace' => 'Api','middleware' => 'auth:api'], function () {

    Route::get('/user', 'UserController@getUser');
    Route::get('/user/media', 'UserController@getMediaUser');
  });
```
UserController.php
```
  
   public function getUser()
    {
        // if(Auth::guest()) return response()->json(['error' => 'Unauthenticated'],401);
        return response()->json(['user' => Auth::user()]);
    }

    public function getMediaUser()
    {
        $media = Auth::user()->getMedia();
        return response()->json(['media' => $media]);
    }

```

**Comment by jeremykenedy** [comment]
I would take a similar approach as to something here:
https://github.com/jeremykenedy/laravel-roles/issues/27
