### ISSUE TITLE
Multiple Social Login w/ Same e-mail Issue

### ISSUE THREAD

**Issue by mtran020** [jeremykenedy/laravel-auth#96]
Hi,

Issue with multiple social account using the same email.  This can cause a potential hack account.  It seems like you have a "same social id checker" but you put it in the incorrect spot, and should check only after if e-mail is found.

**Comment by jeremykenedy** [comment]
I was just able to use Facebook and Twitch to authorize the same account with the same email. I am unable to replicate this issue.

**Comment by mtran020** [comment]
It is more of a security issue and accounts can get hacked.

Ex. If I have a facebook account and no twitch account, and then some hacker creates a twitch account that uses the same e-mail, they can use the api login and hack and take over my account.

social login is independent of each other and should not allow from one socialnetwork to sign into an account using a different socialid even though e-mail is the same.

**Comment by jeremykenedy** [comment]
Thinking through this, one can sign up with different service providers where the email is the same with that provider. 

However, with Oauth and Social Media Authentication is think the security verification for the user saying who they are in that situation falls on the service provide the login.

Example: Facebook needs to verify your email to proceed with using their services as does Twitter. If a provider does not do that you cannot change that provider but simply do not offer them as a social login provider.
