### ISSUE TITLE
sudo git clone is really bad...

### ISSUE THREAD

**Issue by fake-fur** [jeremykenedy/laravel-auth#98]
you closed the other comment thread without answering the question, so i repeat it here:

running git clone using sudo gives the cloned repo root privileges, which is a very bad thing that has potentially very bad consequences, so i ask again, why do you suggest people do that to use your codebase?

thank you

**Comment by jeremykenedy** [comment]
Please do not open duplicate non-relevant issues. Please take the time to read the readme on issues. Sudo is only bad if you do not know how to use it.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-auth#opening-an-issue

**Comment by jeremykenedy** [comment]
Looking over your gh timeline a cannot help but notice you are constantly creating issues on others people open source work but you have almost zero contributions. Give back to the community before bogging it down with the inabilities to figure it out. 

Good luck!
