### ISSUE TITLE
Social login causing issue

### ISSUE THREAD

**Issue by ajitdas123** [jeremykenedy/laravel-auth#99]
Hi jeremy,
I have been working on this project of yours for a while now, everything was working fine even the google social login was working fine too  but for past few days it been throwing an error 

`Type error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given`

I tried to solution mention https://github.com/cmgmyr/laravel-messenger/issues/82 but it didn't work.

Can you please take a look at the screenshot and let me know wha
![screenshot_4](https://user-images.githubusercontent.com/20204881/34511364-17de793a-f081-11e7-8e0c-82678802bf08.png)
t could the reason and possible fix

Thanks

**Comment by jeremykenedy** [comment]
When does this happen?

**Comment by jeremykenedy** [comment]
I am having trouble duplicating.
Can you please provide duplication steps.

What I did to try and duplicate:
1. Install the project fresh.
2. Add my Facebook app creds.
3. Logged in with facebook.

**Comment by ajitdas123** [comment]
I think this happened when i was trying to store user profile image  
i added these lines in SocialController  after line number 102  that where u checking for twitter name

```
$user->profile()->avatar = $socialUserObject->avatar_original;
                $user->profile()->avatar_status = 1;
```

That didn't work though.

But when i reset the complete migration table the problem got fix.
Don't know how :|

**Comment by jeremykenedy** [comment]
Did the issue come back after the database reset?

**Comment by ajitdas123** [comment]
nope it didnt

**Comment by jeremykenedy** [comment]
My thought is there was a data issue from before that fix applied where it saved something as a string when it should have been an object...

**Comment by jeremykenedy** [comment]
Thanks for checking out the project!

**Comment by ajitdas123** [comment]
Nah it didn't store anything 
Btw from where you storing social user data into profile table ? 
If i want to store social user avatar image and change the avatar status where to do ??
